{
  "hash": "3a622d40ff8abbddea0a07355ef88705",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Gazette's Published Record, Downloadable\"\n# subtitle: \"What ships in the notas-archivo release, and how it grows\"\n# date: 2026-07-18\n# author:\n#  - name: INGEOTEC\nabstract: >\n  The explorations and tools on this site are not built from a static\n  snapshot: they read from GitHub Releases this project publishes on top of\n  what the DOF and the SCJN already make public. This page is about the\n  first of those releases, notas-archivo, tagged from dofjson's --archivo\n  mode against the DOF's own open-data service: what it contains, what a\n  reader will actually find inside it, and the monthly workflow that keeps\n  it growing.\n---\n\n\n\n[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/INGEOTEC/LegalIA/blob/master/website/pages/dataset.ipynb)\n\n## Built on what the DOF and the SCJN already publish\n\nEverything on this site is built on top of institutions that already publish\nthis material themselves. The *Diario Oficial de la Federación* (DOF),\nMexico's official gazette, publishes through two systems: SIDOF, its JSON\nopen-data service (`sidof.segob.gob.mx`), and `www.dof.gob.mx`, its own\nwebsite — the second recovers whole publication days SIDOF sometimes drops\nsilently, reported as an empty, valid day, the same as a Sunday (see\n[`dofjson`](https://github.com/INGEOTEC/LegalIA/tree/master/packages/dofjson)).\nThe Suprema Corte de Justicia de la Nación (SCJN) separately publishes\nconsolidated legal text — a law's text as it read right after each reform —\nthrough its own search service, which\n[`nota2md`](https://github.com/INGEOTEC/LegalIA/tree/master/packages/nota2md)\ncrawls.\n\n**The DOF/SIDOF remains the official source of legal text.** The SCJN is\nnot: its consolidated texts are convenient, and mark their own editorial\ninsertions, but the gazette is still what the law actually says. Every file\nthis project writes from the SCJN corpus keeps a `fuente: scjn` header for\nexactly that reason — see [Federal Laws](leyes.ipynb).\n\n## What the project adds\n\nOn top of what the DOF and the SCJN publish, LegalIA maintains two GitHub\nReleases: [`notas-archivo`](https://github.com/INGEOTEC/LegalIA/releases/tag/notas-archivo),\nthe DOF's daily notes index — what the rest of this page documents — and\n[`scjn-leyes`](https://github.com/INGEOTEC/LegalIA/releases/tag/scjn-leyes),\nthe SCJN's consolidated law texts, documented on [Federal Laws](leyes.ipynb).\nBoth are downloadable in one step:\n\n```bash\nnota2md download all\n```\n\nwhich fetches `notas-archivo` into `dofjson`'s cache and `scjn-leyes` into\n`nota2md`'s own — each package keeps its own directory, so clearing one\nnever clears the other. `nota2md download gazette-metadata` and `nota2md\ndownload federal-laws` fetch them one at a time; the rest of this page reads\nthe first.\n\n## What can actually be read\n\nEvery note carries three flags — `existeHtml`, `existeImagen`, `existePdf`\n— saying which forms of it the gazette actually holds. They are the first\nthing to check before any downstream work, because they decide *how* a note\ncan be read at all: a note with HTML is converted directly by `nota2md`'s\ndefault path, cleanly and cheaply; a note that exists only as scanned pages\nor as a PDF has to go through OCR, which is what `nota2md` borrows\n[`dof2md`](dof2md.ipynb) for. And the answer changes drastically across the\ncentury.\n\nThe flags are not in the titles dataset described below — that keeps only\n`codNota`, `titulo`, `fecha` and `codOrgaUno` — so this reads the release\nassets themselves. One command puts them all in the per-user cache (~59 MB,\n116 assets; a second run downloads nothing):\n\n```bash\nnota2md download gazette-metadata\n```\n\nand the cell below aggregates every note in them. It is the slowest cell on\nthis site — it parses all 1.2 million records, a few minutes — which is why\nthe site renders this page from its frozen output rather than re-executing\nit.\n\n::: {#cell-coverage-data .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Reading the three flags out of every cached asset, aggregated by decade\"}\nimport collections\nimport datetime as dt\nfrom pathlib import Path\n\nimport dofjson\nimport pandas as pd\nfrom dofjson.titulos import CACHE_DIR\n\n# `existeImagen` is not a clean \"S\"/\"N\" domain: 48 notes (all of them in the\n# 2010s) carry \"Y\" instead. It reads as a data-entry variant of \"S\" -- those\n# notes all have HTML and a PDF as well, and nothing distinguishes them\n# otherwise -- so it is counted as present. What matters more than the\n# decision, on 48 records out of 1.2 million, is not assuming the domain is\n# binary and silently dropping them: compare against the truthy values\n# explicitly.\nPRESENTE = (\"S\", \"Y\")\nFLAGS = {\"HTML\": \"existeHtml\", \"Scanned images\": \"existeImagen\", \"PDF\": \"existePdf\"}\n\npor_decada = collections.defaultdict(collections.Counter)\nsin_nada = 0\npdf_sin_imagen = 0\nmas_antigua_pdf_sin_imagen = None\nfor asset in sorted(Path(CACHE_DIR).glob(\"*.tgz\")):\n    for nota in dofjson.notas_de_tgz(asset.read_bytes()):\n        # The note's own `fecha`, not the day file it is packed in: 160 notes\n        # disagree with their file, and for a handful the year does too.\n        dia, mes, anio = (int(x) for x in nota[\"fecha\"].split(\"-\"))\n        decada = anio // 10 * 10\n        fila = por_decada[decada]\n        fila[\"notes\"] += 1\n        presentes = 0\n        for etiqueta, campo in FLAGS.items():\n            if nota.get(campo) in PRESENTE:\n                fila[etiqueta] += 1\n                presentes += 1\n        if presentes == 0:\n            fila[\"none\"] += 1\n            sin_nada += 1\n        # Is the PDF series redundant with the images? Counted rather than\n        # assumed -- it is not, and the figure keeps all three because of it.\n        if nota.get(\"existePdf\") in PRESENTE and nota.get(\"existeImagen\") not in PRESENTE:\n            fila[\"pdf_only\"] += 1\n            pdf_sin_imagen += 1\n            clave = (dt.date(anio, mes, dia), nota[\"codNota\"])\n            if mas_antigua_pdf_sin_imagen is None or clave < mas_antigua_pdf_sin_imagen:\n                mas_antigua_pdf_sin_imagen = clave\n\ncobertura = pd.DataFrame(\n    [\n        {\"decade\": d, \"notes\": c[\"notes\"], \"none\": c[\"none\"],\n         \"pdf_only\": c[\"pdf_only\"],\n         **{etiqueta: 100 * c[etiqueta] / c[\"notes\"] for etiqueta in FLAGS}}\n        for d, c in sorted(por_decada.items())\n    ]\n).set_index(\"decade\")\ncobertura[[\"notes\", *FLAGS]].round(1)\n```\n\n::: {#coverage-data .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>notes</th>\n      <th>HTML</th>\n      <th>Scanned images</th>\n      <th>PDF</th>\n    </tr>\n    <tr>\n      <th>decade</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1910</th>\n      <td>8913</td>\n      <td>0.0</td>\n      <td>51.7</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1920</th>\n      <td>46968</td>\n      <td>0.0</td>\n      <td>99.1</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1930</th>\n      <td>41619</td>\n      <td>0.0</td>\n      <td>92.3</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1940</th>\n      <td>52391</td>\n      <td>0.0</td>\n      <td>99.1</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1950</th>\n      <td>51244</td>\n      <td>0.0</td>\n      <td>99.6</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1960</th>\n      <td>49634</td>\n      <td>0.0</td>\n      <td>99.1</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1970</th>\n      <td>66467</td>\n      <td>61.1</td>\n      <td>97.2</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1980</th>\n      <td>63565</td>\n      <td>88.7</td>\n      <td>98.2</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1990</th>\n      <td>107736</td>\n      <td>98.9</td>\n      <td>85.7</td>\n      <td>99.9</td>\n    </tr>\n    <tr>\n      <th>2000</th>\n      <td>265131</td>\n      <td>100.0</td>\n      <td>99.5</td>\n      <td>99.9</td>\n    </tr>\n    <tr>\n      <th>2010</th>\n      <td>323343</td>\n      <td>99.9</td>\n      <td>99.5</td>\n      <td>99.6</td>\n    </tr>\n    <tr>\n      <th>2020</th>\n      <td>160092</td>\n      <td>100.0</td>\n      <td>99.9</td>\n      <td>99.9</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-coverage .cell execution_count=3}\n``` {.python .cell-code}\nimport plotly.graph_objects as go\n\n# The site's validated categorical palette, in fixed assignment order -- the\n# same three hues, meaning the same three things, as on the other pages.\nBLUE, GREEN, MAGENTA = \"#2a78d6\", \"#008300\", \"#e87ba4\"\nINK, MUTED, GRID = \"#52514e\", \"#898781\", \"#e1e0d9\"\nPLOTLY_FONT = \"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif\"\n\n# Colour is never the only thing carrying identity: each series also has its\n# own marker shape and dash pattern, so the figure survives greyscale, print\n# and colour-vision deficiency -- and the table above it is the same data.\nSERIES = [\n    (\"HTML\", BLUE, \"circle\", \"solid\"),\n    (\"Scanned images\", GREEN, \"square\", \"dash\"),\n    (\"PDF\", MAGENTA, \"diamond\", \"dot\"),\n]\n\netiquetas = [\n    f\"{d}s<br><span style='font-size:11px'>{n:,}</span>\"\n    for d, n in zip(cobertura.index, cobertura[\"notes\"])\n]\n\nfig = go.Figure()\nfor nombre, color, simbolo, guion in SERIES:\n    fig.add_trace(\n        go.Scatter(\n            x=etiquetas, y=cobertura[nombre], name=nombre, mode=\"lines+markers\",\n            line=dict(color=color, width=2, dash=guion),\n            marker=dict(color=color, size=9, symbol=simbolo,\n                        line=dict(color=\"white\", width=2)),\n            hovertemplate=f\"{nombre}: %{{y:.1f}}%<extra></extra>\",\n        )\n    )\n\nfig.update_layout(\n    font=dict(family=PLOTLY_FONT, size=13, color=INK),\n    paper_bgcolor=\"white\", plot_bgcolor=\"white\", height=470,\n    # A roomier top margin than the site's other figures: this is the one\n    # with a horizontal legend sitting above the plot area, and 16px clips it.\n    margin=dict(l=64, r=24, t=52, b=56),\n    hovermode=\"x unified\",\n    hoverlabel=dict(bgcolor=\"white\", bordercolor=GRID, font=dict(color=INK, size=12)),\n    legend=dict(font=dict(size=12, color=INK), orientation=\"h\",\n                yanchor=\"bottom\", y=1.0, xanchor=\"left\", x=0),\n)\nfig.update_xaxes(showgrid=False, showline=False, zeroline=False, ticks=\"\",\n                 tickfont=dict(color=MUTED), title_text=\"\")\nfig.update_yaxes(range=[0, 103], dtick=25, ticksuffix=\"%\", showgrid=True,\n                 gridcolor=GRID, gridwidth=1, showline=False, zeroline=False,\n                 ticks=\"\", tickfont=dict(color=MUTED),\n                 title_text=\"Notes with this form available\",\n                 title_font=dict(color=INK, size=13))\n# The one editorial point the eye should not have to hunt for.\nfig.add_annotation(\n    x=etiquetas[6], y=61.1, text=\"HTML begins\", showarrow=True, arrowhead=0,\n    arrowcolor=MUTED, ax=-4, ay=48, font=dict(color=INK, size=12), xanchor=\"left\",\n)\nfig\n```\n\n::: {#fig-coverage .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script type=\"text/javascript\">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.3.1.min.js\" integrity=\"sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=\" crossorigin=\"anonymous\"></script>                <div id=\"c920ab9f-b4d9-4b18-ac64-4debdd304604\" class=\"plotly-graph-div\" style=\"height:470px; width:100%;\"></div>            <script type=\"text/javascript\">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"c920ab9f-b4d9-4b18-ac64-4debdd304604\")) {                    Plotly.newPlot(                        \"c920ab9f-b4d9-4b18-ac64-4debdd304604\",                        [{\"hovertemplate\":\"HTML: %{y:.1f}%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#2a78d6\",\"dash\":\"solid\",\"width\":2},\"marker\":{\"color\":\"#2a78d6\",\"line\":{\"color\":\"white\",\"width\":2},\"size\":9,\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"HTML\",\"x\":[\"1910s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e8,913\\u003c\\u002fspan\\u003e\",\"1920s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e46,968\\u003c\\u002fspan\\u003e\",\"1930s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e41,619\\u003c\\u002fspan\\u003e\",\"1940s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e52,391\\u003c\\u002fspan\\u003e\",\"1950s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e51,244\\u003c\\u002fspan\\u003e\",\"1960s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e49,634\\u003c\\u002fspan\\u003e\",\"1970s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e66,467\\u003c\\u002fspan\\u003e\",\"1980s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e63,565\\u003c\\u002fspan\\u003e\",\"1990s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e107,736\\u003c\\u002fspan\\u003e\",\"2000s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e265,131\\u003c\\u002fspan\\u003e\",\"2010s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e323,343\\u003c\\u002fspan\\u003e\",\"2020s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e160,092\\u003c\\u002fspan\\u003e\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAAAAAAB3KKDJEHFhP7606OjtrmM\\u002fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjel2YoGNTkDwK+rb\\u002fy5WQOXa3wCWt1hAhqtIBrz\\u002fWEClEqu7rPxYQAAAAAAAAFlA\"},\"type\":\"scatter\"},{\"hovertemplate\":\"Scanned images: %{y:.1f}%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#008300\",\"dash\":\"dash\",\"width\":2},\"marker\":{\"color\":\"#008300\",\"line\":{\"color\":\"white\",\"width\":2},\"size\":9,\"symbol\":\"square\"},\"mode\":\"lines+markers\",\"name\":\"Scanned images\",\"x\":[\"1910s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e8,913\\u003c\\u002fspan\\u003e\",\"1920s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e46,968\\u003c\\u002fspan\\u003e\",\"1930s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e41,619\\u003c\\u002fspan\\u003e\",\"1940s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e52,391\\u003c\\u002fspan\\u003e\",\"1950s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e51,244\\u003c\\u002fspan\\u003e\",\"1960s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e49,634\\u003c\\u002fspan\\u003e\",\"1970s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e66,467\\u003c\\u002fspan\\u003e\",\"1980s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e63,565\\u003c\\u002fspan\\u003e\",\"1990s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e107,736\\u003c\\u002fspan\\u003e\",\"2000s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e265,131\\u003c\\u002fspan\\u003e\",\"2010s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e323,343\\u003c\\u002fspan\\u003e\",\"2020s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e160,092\\u003c\\u002fspan\\u003e\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"BoKB80LVSUA\\u002fvlu4RMhYQObMO6LDEVdADd\\u002fQiqHEWEDKgFkjpehYQKiy6ZGvxFhANHceHvxPWEBHeybhm4tYQL9hXgGoblVA6gfxrA7jWEBt4YU7feBYQMM3XnrD+VhA\"},\"type\":\"scatter\"},{\"hovertemplate\":\"PDF: %{y:.1f}%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#e87ba4\",\"dash\":\"dot\",\"width\":2},\"marker\":{\"color\":\"#e87ba4\",\"line\":{\"color\":\"white\",\"width\":2},\"size\":9,\"symbol\":\"diamond\"},\"mode\":\"lines+markers\",\"name\":\"PDF\",\"x\":[\"1910s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e8,913\\u003c\\u002fspan\\u003e\",\"1920s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e46,968\\u003c\\u002fspan\\u003e\",\"1930s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e41,619\\u003c\\u002fspan\\u003e\",\"1940s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e52,391\\u003c\\u002fspan\\u003e\",\"1950s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e51,244\\u003c\\u002fspan\\u003e\",\"1960s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e49,634\\u003c\\u002fspan\\u003e\",\"1970s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e66,467\\u003c\\u002fspan\\u003e\",\"1980s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e63,565\\u003c\\u002fspan\\u003e\",\"1990s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e107,736\\u003c\\u002fspan\\u003e\",\"2000s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e265,131\\u003c\\u002fspan\\u003e\",\"2010s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e323,343\\u003c\\u002fspan\\u003e\",\"2020s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e160,092\\u003c\\u002fspan\\u003e\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAAAAAAAAAAAAAABZQAAAAAAAAFlAAAAAAAAAWUAAAAAAAABZQAAAAAAAAFlAAAAAAAAAWUAAAAAAAABZQATc\\u002fnMe+lhAmqRIWkD4WEBofWu2d+RYQM8EcMFS+lhA\"},\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"font\":{\"family\":\"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif\",\"size\":13,\"color\":\"#52514e\"},\"margin\":{\"l\":64,\"r\":24,\"t\":52,\"b\":56},\"hoverlabel\":{\"font\":{\"color\":\"#52514e\",\"size\":12},\"bgcolor\":\"white\",\"bordercolor\":\"#e1e0d9\"},\"legend\":{\"font\":{\"size\":12,\"color\":\"#52514e\"},\"orientation\":\"h\",\"yanchor\":\"bottom\",\"y\":1.0,\"xanchor\":\"left\",\"x\":0},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"height\":470,\"hovermode\":\"x unified\",\"xaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"text\":\"\"},\"showgrid\":false,\"showline\":false,\"zeroline\":false,\"ticks\":\"\"},\"yaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"font\":{\"color\":\"#52514e\",\"size\":13},\"text\":\"Notes with this form available\"},\"range\":[0,103],\"dtick\":25,\"ticksuffix\":\"%\",\"showgrid\":true,\"gridcolor\":\"#e1e0d9\",\"gridwidth\":1,\"showline\":false,\"zeroline\":false,\"ticks\":\"\"},\"annotations\":[{\"arrowcolor\":\"#898781\",\"arrowhead\":0,\"ax\":-4,\"ay\":48,\"font\":{\"color\":\"#52514e\",\"size\":12},\"showarrow\":true,\"text\":\"HTML begins\",\"x\":\"1970s\\u003cbr\\u003e\\u003cspan style='font-size:11px'\\u003e66,467\\u003c\\u002fspan\\u003e\",\"xanchor\":\"left\",\"y\":61.1}]},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('c920ab9f-b4d9-4b18-ac64-4debdd304604');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nShare of each decade's notes for which the gazette holds HTML, scanned images, or a PDF. The note count under each decade is the weight behind its percentages — the 1910s' 51.7% is half of 8,913 notes, the 2010s' of 323,343. Series are distinguished by marker shape and dash as well as colour; hover for exact values.\n:::\n:::\n\n\n::: {#cell-coverage-summary .cell execution_count=4}\n``` {.python .cell-code code-summary=\"The numbers cited below, computed rather than written\"}\nfrom IPython.display import Markdown\n\n# A decade is \"in the HTML era\" at 1% or more, not at any non-zero value: a\n# few dozen stray records carry `existeHtml: \"S\"` in decades that are\n# otherwise entirely pre-digital, and taking the first non-zero decade would\n# put the boundary half a century too early.\nUMBRAL_ERA_HTML = 1.0\nen_la_era = cobertura[cobertura[\"HTML\"] >= UMBRAL_ERA_HTML]\nprimer_html = int(en_la_era.index.min())\nantes = cobertura.loc[: primer_html - 10]\nsueltas = int((antes[\"HTML\"] / 100 * antes[\"notes\"]).round().sum())\ndecada_vacia = int(cobertura[\"none\"].idxmax())\nMarkdown(\n    f\"Three things the figure says. **The HTML era begins in the \"\n    f\"{primer_html}s** — {cobertura.loc[primer_html, 'HTML']:.0f}% of that \"\n    f\"decade's notes, against {sueltas} stray records in the whole half-century \"\n    f\"before it — and is only effectively universal from the 2000s on. Before \"\n    f\"that boundary, every note is an OCR job. **The gap is in the imaging, not \"\n    f\"the HTML**: scanned images are near-complete for most of the century, but \"\n    f\"the {decada_vacia}s sit at \"\n    f\"{cobertura.loc[decada_vacia, 'Scanned images']:.1f}% and the 1990s dip to \"\n    f\"{cobertura.loc[1990, 'Scanned images']:.1f}%, which is why the PDF series \"\n    f\"is worth plotting separately rather than assumed to track it. And \"\n    f\"**{sin_nada:,} notes have no content at all** — no HTML, no image, no PDF \"\n    f\"— every one of them in the {decada_vacia}s, where they are exactly the \"\n    f\"half of the decade that was never imaged. They exist in the index, with a \"\n    f\"title and a date, and no path to their text.\"\n)\n```\n\n::: {#coverage-summary .cell-output .cell-output-display .cell-output-markdown execution_count=4}\nThree things the figure says. **The HTML era begins in the 1970s** — 61% of that decade's notes, against 2 stray records in the whole half-century before it — and is only effectively universal from the 2000s on. Before that boundary, every note is an OCR job. **The gap is in the imaging, not the HTML**: scanned images are near-complete for most of the century, but the 1910s sit at 51.7% and the 1990s dip to 85.7%, which is why the PDF series is worth plotting separately rather than assumed to track it. And **4,308 notes have no content at all** — no HTML, no image, no PDF — every one of them in the 1910s, where they are exactly the half of the decade that was never imaged. They exist in the index, with a title and a date, and no path to their text.\n:::\n:::\n\n\n::: {#cell-pdf-only-summary .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Why the PDF series is not redundant with the images\"}\nsolo_pdf = cobertura[\"pdf_only\"].sort_values(ascending=False)\nfecha_mas_antigua, cod_mas_antigua = mas_antigua_pdf_sin_imagen\nMarkdown(\n    f\"The PDF series is not redundant with the images. **{pdf_sin_imagen:,} \"\n    f\"notes have a PDF and no scanned image**, concentrated in the \"\n    f\"{int(solo_pdf.index[0])}s ({int(solo_pdf.iloc[0]):,}) and the \"\n    f\"{int(solo_pdf.index[1])}s ({int(solo_pdf.iloc[1]):,}), the oldest of them \"\n    f\"`codNota` {cod_mas_antigua}, published \"\n    f\"{fecha_mas_antigua:%-d %B %Y}. A pipeline that treated \\\"has an image\\\" \"\n    f\"as the OCR-eligibility test would drop every one of them.\"\n)\n```\n\n::: {#pdf-only-summary .cell-output .cell-output-display .cell-output-markdown execution_count=5}\nThe PDF series is not redundant with the images. **25,500 notes have a PDF and no scanned image**, concentrated in the 1990s (15,276) and the 1930s (3,214), the oldest of them `codNota` 4438455, published 26 November 1921. A pipeline that treated \"has an image\" as the OCR-eligibility test would drop every one of them.\n:::\n:::\n\n\nRead downstream, the three series are a routing table. A note the HTML series\ncovers takes `legal_provisions`' cheap path — `nota2md` converts its HTML\ndirectly, no OCR and no page-boundary guessing. A note the HTML series\nmisses but one of the other two covers is an OCR job: `nota2md` downloads the\nscanned pages, or the note's own PDF sliced out of the edition, and runs them\nthrough [`dof2md`](dof2md.ipynb)/mineru before cutting the note out of the\npage. A note none of the three covers cannot be built from this archive at all,\nwhichever tool is pointed at it.\n\n## How the archive grows\n\nThe release is kept current by a scheduled workflow, [`notas-archivo.yml`](https://github.com/INGEOTEC/LegalIA/blob/master/.github/workflows/notas-archivo.yml), that runs once a month, at 09:00 UTC on the 1st and updates the release [notas-archivo](https://github.com/INGEOTEC/LegalIA/releases/tag/notas-archivo). In the ordinary case it downloads the month that just ended with `dofjson --archivo --desde ... --hasta ...` and uploads it as `notas-YYYY-MM.tgz`, overwriting any asset of the same name (`--clobber`), so a re-run of the same month is harmless. \n\nJanuary 1st is a special case: the month that just ended is December, so\ninstead of one more monthly asset the workflow downloads the *entire year*\nthat just closed, publishes it as a single `notas-YYYY.tgz`, and deletes the\ntwelve monthly assets that covered it — folding a year's worth of monthly\narchives into the one closed-year asset the pattern above expects. The\nworkflow can also be run by hand, for a specific month, through its\n`workflow_dispatch` input — useful for backfilling or forcing a re-run.\nNone of this depends on the workflow always succeeding: `dofjson --archivo`\nresumes from where a previous attempt left off, so a failed or partial run\nis picked up cleanly the next time it fires.\n\n## One release, one file per publication day\n\nThe [repository](https://github.com/INGEOTEC/LegalIA) keeps its collected\nDiario Oficial data out of git and in a single GitHub Release instead,\n[notas-archivo](https://github.com/INGEOTEC/LegalIA/releases/tag/notas-archivo):\nthe raw archive is large, grows every month, and would not sit comfortably\nas committed files. Each asset in that release is a `.tgz` of one JSON file\nper publication day, produced by [dofjson](https://pypi.org/project/dofjson/)'s\nincremental `--archivo` mode against the DOF's open-data service — the\nday's index of what was published, never a note's full content or its\nscanned images.\n\n::: {.fronts}\n::: {.front}\n### One asset, one span of time {.unnumbered .unlisted}\n\nA closed year packs into a single `notas-YYYY.tgz`; the year under way\nships instead as one `notas-YYYY-MM.tgz` per finished month, until it\ncloses.\n:::\n::: {.front}\n### One file, one day {.unnumbered .unlisted}\n\nInside each archive, one JSON file per publication day —\n`DDMMYYYY-notas.json` — holding that day's morning, evening and\nextraordinary editions.\n:::\n::: {.front}\n### One record, one note {.unnumbered .unlisted}\n\nEach note carries its `codNota` identifier, `titulo`, the section and page\nit was printed on, its issuing branch, and whether HTML, PDF or scanned\nimages exist for it.\n:::\n:::\n\nA single note record looks like this (trimmed to the fields the site's\npages actually use):\n\n```json\n{\n  \"codNota\": 5793639,\n  \"titulo\": \"Acuerdo por el que se establecen acciones para la primera etapa...\",\n  \"fecha\": \"15-07-2026\",\n  \"codOrgaUno\": \"PE\",\n  \"nombreCodOrgaUno\": \"PODER EJECUTIVO\",\n  \"codSeccion\": \"UNICA\",\n  \"pagina\": 5,\n  \"existeHtml\": \"S\",\n  \"existeImagen\": \"S\",\n  \"existePdf\": \"S\"\n}\n```\n\nStub entries without a title — an internal bookkeeping artifact of the\nservice — are filtered out before the file is written, using the same\n`quita_notas_sin_titulo` helper `dofjson` uses elsewhere.\n\n## The release today\n\nRather than describe the current contents in prose — which would be stale\nthe day after this page is rendered — the cell below asks GitHub directly:\n\n::: {#cell-16 .cell execution_count=6}\n``` {.python .cell-code}\nimport re\nimport pandas as pd\nimport requests\n\nresp = requests.get(\n    \"https://api.github.com/repos/INGEOTEC/LegalIA/releases/tags/notas-archivo\",\n    timeout=30,\n)\nrelease = resp.json()\nassets = sorted(release[\"assets\"], key=lambda a: a[\"name\"])\n\nrows = []\nfor a in assets:\n    m = re.match(r\"notas-(\\d{4})(?:-(\\d{2}))?\\.tgz\", a[\"name\"])\n    year, month = m.group(1), m.group(2)\n    rows.append(\n        {\n            \"asset\": a[\"name\"],\n            \"span\": year if month is None else f\"{year}-{month}\",\n            \"kind\": \"year\" if month is None else \"month\",\n            \"size_MB\": round(a[\"size\"] / 1_000_000, 2),\n        }\n    )\ntable = pd.DataFrame(rows)\nprint(\n    f\"{len(table)} assets, spanning {table.span.min()}\\u2013{table.span.max()}: \"\n    f\"{(table.kind == 'year').sum()} closed years, \"\n    f\"{(table.kind == 'month').sum()} months of the year under way \"\n    f\"({table.size_MB.sum():.0f} MB total).\"\n)\ntable.tail(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n117 assets, spanning 1917–2026-08: 109 closed years, 8 months of the year under way (59 MB total).\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>asset</th>\n      <th>span</th>\n      <th>kind</th>\n      <th>size_MB</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>109</th>\n      <td>notas-2026-01.tgz</td>\n      <td>2026-01</td>\n      <td>month</td>\n      <td>0.05</td>\n    </tr>\n    <tr>\n      <th>110</th>\n      <td>notas-2026-02.tgz</td>\n      <td>2026-02</td>\n      <td>month</td>\n      <td>0.07</td>\n    </tr>\n    <tr>\n      <th>111</th>\n      <td>notas-2026-03.tgz</td>\n      <td>2026-03</td>\n      <td>month</td>\n      <td>0.09</td>\n    </tr>\n    <tr>\n      <th>112</th>\n      <td>notas-2026-04.tgz</td>\n      <td>2026-04</td>\n      <td>month</td>\n      <td>0.09</td>\n    </tr>\n    <tr>\n      <th>113</th>\n      <td>notas-2026-05.tgz</td>\n      <td>2026-05</td>\n      <td>month</td>\n      <td>0.09</td>\n    </tr>\n    <tr>\n      <th>114</th>\n      <td>notas-2026-06.tgz</td>\n      <td>2026-06</td>\n      <td>month</td>\n      <td>0.11</td>\n    </tr>\n    <tr>\n      <th>115</th>\n      <td>notas-2026-07.tgz</td>\n      <td>2026-07</td>\n      <td>month</td>\n      <td>0.10</td>\n    </tr>\n    <tr>\n      <th>116</th>\n      <td>notas-2026-08.tgz</td>\n      <td>2026-08</td>\n      <td>month</td>\n      <td>0.08</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe tail of the table is the interesting part: it is exactly the boundary\ndescribed above, the last couple of closed years followed by the monthly\nassets accumulated so far for the year in progress. Run this page again\nnext month and one more row will have appeared there.\n\n## Getting the raw archive yourself\n\nAny asset can be pulled without cloning the repository:\n\n```bash\ngh release download notas-archivo -p notas-2025.tgz\ntar xzf notas-2025.tgz\n```\n\nWithout `gh`, every entry of the `assets` list in the API response used\nabove carries a `browser_download_url` — a direct link to that `.tgz`. Pick\nthe one you want out of that same response:\n\n```python\nurl = next(\n    a[\"browser_download_url\"] for a in assets if a[\"name\"] == \"notas-2025.tgz\"\n)\n# https://github.com/INGEOTEC/LegalIA/releases/download/notas-archivo/notas-2025.tgz\n```\n\nand follow it with any HTTP client:\n\n```bash\ncurl -LO https://github.com/INGEOTEC/LegalIA/releases/download/notas-archivo/notas-2025.tgz\ntar xzf notas-2025.tgz\n```\n\nTo extend a local copy going forward instead of downloading a fixed\nsnapshot, `dofjson --archivo` is the same tool the monthly workflow runs,\nand it is resumable in the same way: interrupt it and rerun it, and it\npicks up only the days it is still missing.\n\n## Streaming every title in the archive\n\nBeyond browsing one release asset at a time, `dofjson` yields a compact\n`codNota` + `titulo` + `fecha` + `codOrgaUno` record for every note ever\npublished: `legal_provisions_titles` reads each `notas-archivo` asset in the\nlocal cache in turn and keeps only those fields from every titled note\n(`titulo` is Spanish for \"title\", `fecha` for \"date\") — `codNota` to fetch\nthe note's full content later (`dofjson.get_nota`), `titulo` for exploratory\nanalysis of the titles themselves with other techniques (in the spirit of\n[DOF Titles](titles.ipynb)), `fecha` to place each title in time, and\n`codOrgaUno` to group by issuing branch.\n\nNothing is written to disk: the titles are a projection of the cache the rest\nof the packages already share, so the archive is never copied a second time.\nPopulate that cache once and every pass afterwards is local:\n\n```bash\nnota2md download gazette-metadata\n```\n\nThen the titles are a plain iterable, with no dataset file in between:\n\n::: {#cell-22 .cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\"}\nfrom dofjson import legal_provisions_titles\n\ntitulos = legal_provisions_titles(log=lambda x: None)\n```\n:::\n\n\nIn the following line, the first title is retrieved. These titles are not sorted globally by the `codNota` field; the ordering applies only at the day level. \n\n::: {#cell-24 .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\"}\nnext(titulos)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n{'codNota': 4430696,\n 'titulo': 'ES ACEPTADO por esta Secretaría el nombramiento del C. Lic. Agustín Ruiz Olloqui, como adscrito a la Notaría nº 9 de esta ciudad',\n 'fecha': '02-01-1917',\n 'codOrgaUno': 'PE'}\n```\n:::\n:::\n\n\n## Methodological note {.unnumbered .appendix}\n\nThis page is a Jupyter notebook that queries the GitHub REST API for the\n`notas-archivo` release at render time; the table above reflects the\nrelease's contents at the moment this page was last rendered, not\nnecessarily today. The archive, the workflow that maintains it and the\naggregation script that feeds the DOF Titles page are all part of the\n[repository](https://github.com/INGEOTEC/LegalIA).\n\nThe archive is itself a product of the collaboration that runs through the\nwhole project: the incremental `--archivo` downloader and the titles\nreader in `dofjson`, the monthly workflow that packages and publishes each\nrelease, and this page were written by the LegalIA team together with\nClaude, Anthropic's coding assistant, through\n[Claude Code](https://claude.com/claude-code), with the authors reviewing\nand validating each contribution before it landed.\n\n",
    "supporting": [
      "dataset_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script type=\"text/javascript\">\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.3.1.min\"</script>\n\n"
      ]
    }
  }
}