{
  "hash": "234b8860a6d952988f3f8ae1e8bafb73",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Federal Laws Corpus: Mexico's Statute Book, One Text per Reform\"\nsubtitle: \"How 3,724 dated reform texts of 315 federal instruments were assembled, and what can be trusted about them\"\ndate: 2026-09-02\nabstract: >\n  Mexico's federal legislation is easy to read today and hard to read\n  historically. What is published is the text of each federal law as it stands\n  right now, not the intermediate wording each reform left behind; the Diario\n  Oficial de la Federación publishes each reform decree and nothing else, so\n  the consolidated text of a law on a given date exists only as the sum of\n  everything published before it. This page documents a corpus that closes\n  that gap: 3,724 reform texts covering 315 of the 316 federal instruments in\n  the project's catalogue, each one the complete text of an instrument as it\n  read after a particular reform, taken from the Supreme Court's legislative\n  database and, for most of them, linked back to the Diario Oficial provision\n  that caused the change. We describe where the material comes from, how the\n  collection is checked for completeness against the project's own catalogue\n  of federal laws, and how it is published and can be downloaded.\n---\n\n[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/INGEOTEC/LegalIA/blob/master/website/pages/leyes.ipynb)\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Imports, the styling shared by every figure, and the aggregate summary this page reads\"}\nimport json\nfrom pathlib import Path\nfrom urllib.request import urlopen\n\nimport pandas as pd\nimport plotly.graph_objects as go\nfrom IPython.display import Markdown\n\n# Validated categorical palette (light mode), in fixed assignment order — the\n# same one `DOF Titles` and `Archive` use, so a colour means the same thing\n# across the site.\nBLUE, GREEN, MAGENTA, YELLOW = \"#2a78d6\", \"#008300\", \"#e87ba4\", \"#eda100\"\nLIGHT_BLUE = \"#9ec5f4\"  # step 200 of the blue sequential ramp\nINK, MUTED, GRID, AXIS = \"#52514e\", \"#898781\", \"#e1e0d9\", \"#c3c2b7\"\n\nPLOTLY_FONT = \"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif\"\n\n\ndef style_plotly(fig, *, yaxis_title=\"\", height=430):\n    fig.update_layout(\n        font=dict(family=PLOTLY_FONT, size=13, color=INK),\n        paper_bgcolor=\"white\",\n        plot_bgcolor=\"white\",\n        height=height,\n        margin=dict(l=64, r=24, t=16, b=40),\n        hoverlabel=dict(bgcolor=\"white\", bordercolor=GRID, font=dict(color=INK, size=12)),\n        legend=dict(font=dict(size=12, color=INK)),\n    )\n    fig.update_xaxes(\n        showgrid=False, showline=False, zeroline=False,\n        ticks=\"\", tickfont=dict(color=MUTED), title_text=\"\",\n    )\n    fig.update_yaxes(\n        showgrid=True, gridcolor=GRID, gridwidth=1,\n        showline=False, zeroline=False,\n        ticks=\"\", tickfont=dict(color=MUTED),\n        title_text=yaxis_title, title_font=dict(color=INK, size=13),\n    )\n    return fig\n\n\nPLOTLY_CONFIG = {\n    \"displaylogo\": False,\n    \"displayModeBar\": \"hover\",\n    \"modeBarButtonsToRemove\": [\"lasso2d\", \"select2d\", \"autoScale2d\"],\n}\n\n# Every figure and every number in the prose below comes from this one file.\n# The corpus itself lives in the `scjn-leyes` release — one tarball per\n# instrument — and is never committed to git, so, unlike `Archive`, which\n# queries the GitHub API live, this page reads the aggregate summary\n# `scripts/resume_scjn_leyes.py` distils from the crawl the release was\n# packaged from: counts, per-year totals and one row per instrument,\n# regenerated by re-running that script and versioned alongside the page.\nRESUMEN = \"data/scjn-leyes-summary.json\"\nRAW = \"https://raw.githubusercontent.com/INGEOTEC/LegalIA/master/website/pages/\" + RESUMEN\nlocal = Path(RESUMEN)\nif local.is_file():  # rendering the site\n    resumen = json.loads(local.read_text(encoding=\"utf-8\"))\nelse:               # running the notebook on Colab\n    with urlopen(RAW) as respuesta:\n        resumen = json.loads(respuesta.read().decode(\"utf-8\"))\n\ninstrumentos = pd.DataFrame(resumen[\"instruments\"])\npor_anio = pd.Series(\n    {int(anio): n for anio, n in resumen[\"snapshots_per_year\"].items()}\n).sort_index()\n\n# Headline figures, named once here and reused by the prose, the table and the\n# figure captions so no number on this page is typed by hand twice.\nSNAPSHOTS = resumen[\"snapshots\"]\nCATALOGO = resumen[\"catalogue_entries\"]\nCON_DIRECTORIO = resumen[\"instruments_with_directory\"]\nESTADOS = resumen[\"title_link_status\"]\nPOR_CONFIRMACION = resumen[\"title_link_status_by_confirmation\"]\nENLAZADOS = resumen[\"linked_by_title\"]\nCONFIRMADOS = resumen[\"content_diff_confirmed\"]\n# A date is identified when a same-day title match resolved it *or* when the\n# content diff resolved a date the title match left ambiguous — the two checks\n# are complementary, and this is the coverage figure that matters to a reader.\nRESCATADOS = POR_CONFIRMACION.get(\"ambiguous|confirmed\", 0)\nIDENTIFICADOS = ENLAZADOS + RESCATADOS\n\n```\n:::\n\n\n::: {#3 .cell execution_count=2}\n``` {.python .cell-code}\n# On Colab, install the packages this notebook needs:\n# %pip install pandas plotly\n\n```\n:::\n\n\n## What a reform text is\n\nThe unit of this collection is not a law and not a decree: it is a **reform\ntext** — one plain-text file holding the *complete* text of one federal\ninstrument as it read after one particular reform. The file is named after\nthe date that reform took effect (`01-04-2025.md`) and lives in a directory\nnamed after the instrument (`cpeum/` for the Constitution, `lft/` for the\nFederal Labour Law), so an instrument's directory is its own history laid out\nin files: as many files as there are dates on which its wording changed.\n\nThis matters because it is the version of the statute book that is otherwise\nmissing. To know what the Federal Labour Law said in 1998 one can consult the\n1998 reform decree in the *Diario Oficial* — but a decree only says which\narticles were replaced and by what, not what the resulting law read like as a\nwhole, and for anything published before roughly 1999 that decree exists only\nas scanned images that have to be read by OCR before it can even be compared\nagainst anything. A reform text sidesteps all of that, because somebody has\nalready done the consolidation: it *is* the law as of that date, in one piece.\n\nThe format is Markdown, and that choice is deliberate. Markdown is plain text,\nso the files are readable in any editor, searchable with `grep`, diffable line\nby line against each other, and stable in version control — the same reasons\nthe rest of LegalIA converts legal texts to Markdown rather than keeping PDFs\nor `.docx` files around. It also keeps just enough structure to be useful — a\nheading is a heading, an emphasized run stays emphasized — without pretending\nto a legal-document schema the source never had. Each file opens with a short\nYAML header recording where it came from, which is described in detail below;\neverything after the header is the text of the law.\n\n## Why the Supreme Court's legislative database\n\nThe *Diario Oficial* is the authoritative source, and it publishes reform\ndecrees: each one says what changes, not what the law then reads. Consolidated\ncurrent text of a federal law is published elsewhere, but only as it stands\ntoday — which tells you what a law says now and not what it said in between.\n\nThe Supreme Court's legislative database\n([legislacion.scjn.gob.mx](https://legislacion.scjn.gob.mx/Buscador/)) is\norganized the other way around. For each instrument it keeps a table of\nreforms, and for each row of that table it serves the consolidated text of the\ninstrument **as it stood after that reform** — a full document, not a summary\nof the change. The Court maintains this because its own work requires it: a\ncase is decided under the law in force at the relevant time, not under the law\nin force today. That editorial effort, undertaken for judicial reasons, is\nexactly what a historical corpus needs, and it is why the Court is this\ncollection's primary source of *content*. Its *scope* — which instruments\nexist, what each is called, and when each was last reformed — comes from the\ncollection's own published index plus the gazette itself, described in the\nnext section.\n\n### A caveat about the source\n\nThe Court's database is a source of convenience, not the source of authority.\nThe authoritative text of Mexican federal law is what the *Diario Oficial de la\nFederación* published; the Court's consolidated versions are an editorial\nproduct built on top of it, and they behave like one:\n\n- **Instruments are addressable, individual searches are not.** The Court's\n  own JSON API gives each instrument a stable identifier, recorded in every\n  file's header, so a later crawl can go straight back to it instead of\n  searching again. What still has no citable address is a search itself —\n  there is no results page to link to — so the only reproducible record of\n  *how* an instrument was first found is what was searched for and what came\n  back, which is why the header keeps that pair.\n- **The search can return the wrong document entirely.** A query for one law\n  can rank a different law, or an internal court agreement that merely\n  mentions the law, above the law itself. Two mechanisms guard against this: a\n  similarity score between what was searched and what was found, recorded in\n  every file, and a filter that discards the Court's own internal agreements.\n  Neither is infallible, which is why publication of this collection is a\n  manual act, described at the end of this page.\n- **Editorial matter is mixed into the text.** The Court annotates its\n  consolidated texts with editor's notes (\"N. DE E.\") explaining, for example,\n  that a reform was later invalidated. These are the Court speaking, not the\n  legislature, and are stripped at conversion time so they never masquerade as\n  statutory text.\n\nBecause the source is editorial, every file declares its provenance in its own\nheader — `fuente: scjn` — and nothing in LegalIA ever silently mixes these\ntexts with Markdown built from the *Diario Oficial* itself.\n\n## From the two sources to one corpus\n\nThe pipeline that builds the collection has four stages, run in order, each\none a separate script under\n[`scripts/`](https://github.com/INGEOTEC/LegalIA/tree/master/scripts)\n([@fig-pipeline]). What follows describes not only what each stage does but\nwhat it *decides*, since the decisions are where a corpus of this kind either\nearns or loses a reader's trust.\n\n::: {#fig-pipeline}\n\n```{mermaid}\nflowchart TD\n    D[scjn-leyes release<br/>indice-global.json.gz] -->|nombre, abrev fallback| C[estado.json per law<br/>fetch_scjn_legislacion.py --plan]\n    C -->|search by nombre| S[SCJN SCOW API<br/>fetch_scjn_legislacion.py]\n    S -->|BusquedaFrase, Reforma, Articulos| M[Markdown texts<br/>DD-MM-YYYY.md + YAML header]\n    A[notas-archivo release] -->|codNota + titulo + fecha| T[titles stream<br/>legal_provisions_titles]\n    M --> L[enlaza_scjn_legislacion.py]\n    T --> L\n    N[dofjson.get_nota<br/>DOF Markdown] --> L\n    L -->|indice.json per instrument| P[empaqueta_scjn_leyes.py<br/>one slug.tgz + MANIFEST.md]\n    P -.->|manual review, manual upload| R[(scjn-leyes release)]\n```\n\nThe pipeline. Two things enter — the catalogue of instruments, read back off\nthe collection's own release, and the DOF's archive of published provision\ntitles — and one corpus of dated reform texts, each linked to the provision\nthat produced it, comes out. The catalogue's own `actualizado` is the newer of\nthe Court's reform table and those same DOF titles. The dotted arrow is the\nonly step no script performs.\n\n:::\n\n### Seeding: which instruments exist\n\nThe first stage answers one question — which instruments exist? — and keeps\nthree fields per entry: the instrument's official `nombre`, its short slug\n(`abrev`, which becomes the directory name), and `actualizado`, the date of\nits most recent reform. It asks no third-party catalogue for any of them. The\nlist of instruments is **read back out of the collection's own release**: the\npublished `indice-global.json.gz` already carries every law's slug and name,\nso the seed is re-read rather than rebuilt. `actualizado` is the **newer** of\ntwo independent answers — the Court's own reform table and the newest DOF\nprovision whose title names the law — because each misses what the other sees:\nthe gazette alone under-dates a law reformed by an omnibus decree that names\nnone of them, and the Court alone freezes a law it has not indexed yet. A law\nneither can date carries no `actualizado` at all, which the refresh planner\nreads as \"always re-check\".\n\nA federal law nobody has entered yet is found rather than waited for: the\nCourt's catalogue of laws and codes is listed and diffed against the\ncatalogue, each candidate is confirmed against a DOF title that names it, and\nthe survivors are **reported, not added** — a new federal law is a handful a\nyear, and its `abrev` is a release asset name, so adding one is a human's\ndecision.\n\n`actualizado` earns its place by making refreshes cheap. Once the whole\ncollection has been crawled start to finish, a later run can skip an\ninstrument that has not been reformed since — but only if it already has\nreform texts on disk. An instrument with none is retried on every single\nrefresh, forever, which is what makes the collection self-healing for laws the\nCourt has not indexed yet: when the Court catches up, the next refresh picks\nthe law up with nothing to configure by hand.\n\n### Crawling: finding the right document\n\nThe second stage searches the Court's own JSON API for each catalogue name —\na relevance-ranked list of documents comes back, and the crawler has to\ndecide which one, if any, is the instrument it was looking for. It discards\nthe Court's own internal Pleno agreements outright, since one of those merely\nmentioning a law in passing is not the law: a name search for the Income Tax\nLaw once surfaced only such agreements, no actual law, which is the failure\nmode this guard exists for. It also rejects a candidate of the wrong kind — a\nreglamento is never the ley it regulates, even when its title does not say\nso — keeps only federal, currently-in-force instruments when any exist, and\npicks the highest-ranked survivor by name similarity. The winner still has to\nclear a minimum similarity floor to be accepted at all, and is flagged\n`sospechoso` (*suspect*) when it clears that floor but not a stricter\nconfidence one — a signal for manual review, not a rejection. For the winner,\nthe crawler walks its reform table through the API and converts each reform's\nown text to Markdown, stripping the editorial notes.\n\nA law the API does not index at all is a different failure mode from a wrong\nmatch, and it used to be a real gap: a search for the LEY Federal de Cine y el\nAudiovisual once returned nothing at all, twice, live. The fix was not a\nsmarter query — an instrument is now addressed by the Court's own stable\nidentifier once it is indexed, and the name search is simply retried on every\nrefresh until then, since a brand-new law can be indexed at any time with no\nsignal that it happened.\n\nThe stage is resumable at two levels — a file already on disk is never\nre-downloaded, and the index of the last instrument attempted is checkpointed,\nso an interrupted run resumes rather than restarts — and rate-limited, out of\ncourtesy to an unofficial service that was never designed to be crawled.\n\n### The header as a provenance record\n\nEvery reform text opens with a YAML header. It is short, and each line is\nthere to answer a question a sceptical reader would ask:\n\n```yaml\n---\nfuente: scjn\nnombre_buscado: CONSTITUCIÓN Política de los Estados Unidos Mexicanos\nordenamiento: CONSTITUCION POLITICA DE LOS ESTADOS UNIDOS MEXICANOS\nfecha_publicacion: 01-04-2025\nfecha_expedicion: 01-04-2025\ncategoria: DECRETO\nratio_similitud: 1.000\nsospechoso: false\n---\n```\n\n- **`fuente`** — where the text came from: `scjn` for the Court's\n  consolidated version, `dof` for the handful of files taken directly from the\n  *Diario Oficial*, when the Court has not indexed an instrument yet. This is\n  the field that keeps an editorial text from ever being mistaken for the\n  official one.\n- **`ordenamiento`** — the title of the document the **Supreme Court**\n  actually served, verbatim.\n- **`nombre_buscado`** — the exact string that was searched for, which is the\n  instrument's name as the **catalogue** gives it (the `nombre` seeded in the\n  first stage) or, for the one entry that needs it, the `nombre_scjn` override\n  described below. The pair is therefore not only *what was asked* / *what came\n  back*: it is **the catalogue's name for the law against the Court's own name\n  for the same law**, which is why the two can differ at all and why the\n  similarity score below is worth recording. Because an individual search has\n  no citable address of its own, the pair is also the only way to reproduce by\n  hand how a given file was reached. It is written only when the two differ\n  after normalizing accents, case and whitespace — so its mere presence marks a\n  file whose identification deserves a second look, and\n  `grep -l nombre_buscado:` is a complete audit.\n- **`ratio_similitud`** and **`sospechoso`** — how close those two strings are\n  (1.000 meaning identical after normalization) and whether that closeness\n  fell into the band where a match is kept but flagged. They record the\n  crawler's confidence rather than hiding it behind a yes/no decision.\n- **`fecha_publicacion`** and **`fecha_expedicion`** — the date the reform was\n  published and the date it was issued, as the Court's reform table gives\n  them; the first is the reform text's identity and its file name.\n- **`categoria`** — the kind of instrument that produced the reform, typically\n  `DECRETO`.\n\nA file crawled through the Court's JSON API also carries the instrument's own\nstable `id_ordenamiento` and a `reforma_id` for this specific reform — the pair\nthat lets a later run address it directly instead of searching by name again.\n\nThe header plays the same role here that the raw JSON record of a note plays\non the `Archive` page: it is the level at which a reader can check the data\nrather than take it on faith.\n\n### Linking each text to the provision that caused it\n\nThe Court's database does not say which *Diario Oficial* provision produced a\ngiven reform text. A last stage adds that link where it can: for a text, it\nfirst looks at what the gazette published that same day, and — when several\nsame-day provisions all plausibly name the instrument — falls back to\ncomparing the candidates' own text against what actually changed. The result\nis one `indice.json` per instrument, pairing each text with a `codNota`, the\nDOF's own identifier for the provision, whenever the pipeline is confident\nenough to commit to one.\n\nThis is the most laborious part of the whole pipeline, and it is still\nchanging, so a full account of how it decides is deliberately left for when it\nsettles. [@fig-link-status] and [@tbl-overview] below show what it currently\nachieves, in numbers rather than mechanism; the link itself is what makes a\nreform text checkable against the official record, joinable with the rest of\nLegalIA by `codNota`, and orderable on days the gazette published more than\none reform to the same law.\n\n## What the corpus looks like today\n\n[@tbl-overview] gives the size of the collection as it stands. Every figure on\nthis page is computed from the summary file described in the methodological\nnote, not typed in by hand.\n\n::: {#tbl-overview .cell tbl-cap='The federal laws corpus at a glance. Percentages of reform texts are over the 3,724 total.' execution_count=3}\n``` {.python .cell-code}\nfilas = [\n    (\"Instruments in the catalogue\", f\"{CATALOGO:,}\", \"\"),\n    (\"With a directory of reform texts\", f\"{CON_DIRECTORIO:,}\",\n     f\"{CON_DIRECTORIO / CATALOGO * 100:.1f}% of the catalogue\"),\n    (\"Markdown reform texts\", f\"{SNAPSHOTS:,}\", \"\"),\n    (\"Taken from the SCJN\", f\"{resumen['snapshots_by_source'].get('scjn', 0):,}\",\n     f\"{resumen['snapshots_by_source'].get('scjn', 0) / SNAPSHOTS * 100:.1f}%\"),\n    (\"Taken directly from the DOF (Court has not indexed the instrument yet)\",\n     f\"{resumen['snapshots_by_source'].get('dof', 0):,}\",\n     f\"{resumen['snapshots_by_source'].get('dof', 0) / SNAPSHOTS * 100:.2f}%\"),\n    (\"Identified by a same-day title match alone\", f\"{ENLAZADOS:,}\",\n     f\"{ENLAZADOS / SNAPSHOTS * 100:.1f}%\"),\n    (\"Ambiguous dates resolved by the content-diff check\", f\"{RESCATADOS:,}\",\n     f\"{RESCATADOS / SNAPSHOTS * 100:.1f}%\"),\n    (\"Identified either way\", f\"{IDENTIFICADOS:,}\",\n     f\"{IDENTIFICADOS / SNAPSHOTS * 100:.1f}%\"),\n    (\"Confirmed by content diff (any state)\", f\"{CONFIRMADOS:,}\",\n     f\"{CONFIRMADOS / SNAPSHOTS * 100:.1f}%\"),\n    (\"Still unidentified\", f\"{SNAPSHOTS - IDENTIFICADOS:,}\",\n     f\"{(SNAPSHOTS - IDENTIFICADOS) / SNAPSHOTS * 100:.1f}%\"),\n    (\"Years covered\", f\"{por_anio.index.min()}\\u2013{por_anio.index.max()}\", \"\"),\n]\nMarkdown(\"\\n\".join(\n    [\"| | | |\", \"|---|---:|---|\"]\n    + [f\"| {etiqueta} | {valor} | {nota} |\" for etiqueta, valor, nota in filas]\n))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n| | | |\n|---|---:|---|\n| Instruments in the catalogue | 316 |  |\n| With a directory of reform texts | 315 | 99.7% of the catalogue |\n| Markdown reform texts | 3,724 |  |\n| Taken from the SCJN | 3,722 | 99.9% |\n| Taken directly from the DOF (Court has not indexed the instrument yet) | 2 | 0.05% |\n| Identified by a same-day title match alone | 2,474 | 66.4% |\n| Ambiguous dates resolved by the content-diff check | 793 | 21.3% |\n| Identified either way | 3,267 | 87.7% |\n| Confirmed by content diff (any state) | 2,634 | 70.7% |\n| Still unidentified | 457 | 12.3% |\n| Years covered | 1889–2026 |  |\n:::\n:::\n\n\n### How deep the history goes\n\n[@fig-snapshots-per-year] plots the reform texts by the year of the reform\nthat produced them, and it is the clearest available picture of when Mexico's\nfederal statute book actually changed. Three things stand out. The first\nhalf-century is thin: the Court's database reaches back to 1917 and beyond —\nthe oldest text in the collection is the Commercial Code of 1889, older than\nthe *Diario Oficial* coverage this project is built on — but reforms before\nthe 1970s are recorded in ones and tens per year, partly because there were\nfewer and partly because the Court's retrospective coverage of them is\nincomplete. Volume then rises through the last quarter of the century and\nsettles, from the 1990s onward, into a regime of well over a hundred reforms a\nyear across the collection. The final year is partial: it covers only the\nmonths already elapsed when the crawl ran.\n\n::: {#cell-fig-snapshots-per-year .cell execution_count=4}\n``` {.python .cell-code}\nultimo = por_anio.index.max()\ncolores = [LIGHT_BLUE if anio == ultimo else BLUE for anio in por_anio.index]\nfig = go.Figure(\n    go.Bar(\n        x=por_anio.index, y=por_anio.values,\n        marker=dict(color=colores, cornerradius=2),\n        hovertemplate=\"%{x}: %{y:,} reform texts<extra></extra>\",\n    )\n)\nstyle_plotly(fig, yaxis_title=\"Reform texts\")\nfig.update_layout(bargap=0.2, showlegend=False, hovermode=\"x unified\")\nfig.add_annotation(x=ultimo, y=por_anio.iloc[-1], text=\"partial year\",\n                   yshift=14, showarrow=False, font=dict(color=MUTED, size=11))\nfig.show(config=PLOTLY_CONFIG)\n```\n\n::: {#fig-snapshots-per-year .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script type=\"text/javascript\">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.3.1.min.js\" integrity=\"sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=\" crossorigin=\"anonymous\"></script>                <div id=\"9cc776a0-e704-44ac-850a-5393daa26372\" class=\"plotly-graph-div\" style=\"height:430px; width:100%;\"></div>            <script type=\"text/javascript\">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"9cc776a0-e704-44ac-850a-5393daa26372\")) {                    Plotly.newPlot(                        \"9cc776a0-e704-44ac-850a-5393daa26372\",                        [{\"hovertemplate\":\"%{x}: %{y:,} reform texts\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":[\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#2a78d6\",\"#9ec5f4\"],\"cornerradius\":2},\"x\":{\"dtype\":\"i2\",\"bdata\":\"YQd9B4EHgweGB4cHiAeJB4sHjAeNB44HjweQB5EHkgeTB5QHlQeWB5cHmAeZB5oHmwecB50HngefB6AHoQeiB6MHpAelB6cHqAepB6oHqwesB60HrgevB7AHsQeyB7MHtAe1B7YHtwe4B7kHuge7B7wHvQe+B78HwAfBB8IHwwfEB8UHxgfHB8gHyQfKB8sHzAfNB84HzwfQB9EH0gfTB9QH1QfWB9cH2AfZB9oH2wfcB90H3gffB+AH4QfiB+MH5AflB+YH5wfoB+kH6gc=\"},\"y\":{\"dtype\":\"i2\",\"bdata\":\"AQACAAEAAQABAAEABQABAAQABQAIABEACgAEAAQABQADAAoABAAKAAgACwAKAAsACAAGAAUABAAJAAMAAQAFAAIAAgABAAEABgACAAMACAABAAMACAAIAAMABAAIAAUACwAFAB4AFAAKAAYADAAHABMAFQAaABwADwAVAC0AEQARAA0AEQAVACgAOAAiACsANgAYACQAMgArABoANAA1ADgAUwBnAEgAQgBhAEMAdgCdAHEApwBqAHsAXQCyAFEAVQClAIoAiwCvALAAMwA=\"},\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"font\":{\"family\":\"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif\",\"size\":13,\"color\":\"#52514e\"},\"margin\":{\"l\":64,\"r\":24,\"t\":16,\"b\":40},\"hoverlabel\":{\"font\":{\"color\":\"#52514e\",\"size\":12},\"bgcolor\":\"white\",\"bordercolor\":\"#e1e0d9\"},\"legend\":{\"font\":{\"size\":12,\"color\":\"#52514e\"}},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"height\":430,\"xaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"text\":\"\"},\"showgrid\":false,\"showline\":false,\"zeroline\":false,\"ticks\":\"\"},\"yaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"font\":{\"color\":\"#52514e\",\"size\":13},\"text\":\"Reform texts\"},\"showgrid\":true,\"gridcolor\":\"#e1e0d9\",\"gridwidth\":1,\"showline\":false,\"zeroline\":false,\"ticks\":\"\"},\"bargap\":0.2,\"showlegend\":false,\"hovermode\":\"x unified\",\"annotations\":[{\"font\":{\"color\":\"#898781\",\"size\":11},\"showarrow\":false,\"text\":\"partial year\",\"x\":2026,\"y\":51,\"yshift\":14}]},                        {\"displaylogo\": false, \"displayModeBar\": \"hover\", \"modeBarButtonsToRemove\": [\"lasso2d\", \"select2d\", \"autoScale2d\"], \"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('9cc776a0-e704-44ac-850a-5393daa26372');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nReform texts per year of publication. The last year, in a lighter shade, is partial — it ends when the crawl ran. Hover on a bar for the exact count.\n:::\n:::\n\n\n### How much of it is identified, and what the content-diff check adds\n\n[@fig-link-status] is the figure to read before using this collection for\nanything. It breaks the 3,724 reform texts down by the state a same-day title\nmatch left them in, and splits each state by whether the content-diff check\nconfirmed a provision. The stacked pair is the point: the `ambiguous` bar's\nconfirmed segment counts dates the title match could not resolve and the\ncontent-diff check could — the concrete return on the more expensive\ncomputation.\n\n::: {#cell-fig-link-status .cell execution_count=5}\n``` {.python .cell-code}\norden = [\"linked\", \"ambiguous\", \"claimed\", \"none\"]\netiquetas = {\n    \"linked\": \"linked<br/>(one candidate)\",\n    \"ambiguous\": \"ambiguous<br/>(several candidates)\",\n    \"claimed\": \"claimed<br/>(taken by another text)\",\n    \"none\": \"none<br/>(no candidate that day)\",\n}\nconfirmados = [POR_CONFIRMACION.get(f\"{e}|confirmed\", 0) for e in orden]\nsin_confirmar = [POR_CONFIRMACION.get(f\"{e}|unconfirmed\", 0) for e in orden]\nfig = go.Figure()\nfig.add_bar(\n    x=[etiquetas[e] for e in orden], y=confirmados, name=\"confirmed by content diff\",\n    marker=dict(color=BLUE), hovertemplate=\"%{y:,} reform texts<extra>confirmed</extra>\",\n)\nfig.add_bar(\n    x=[etiquetas[e] for e in orden], y=sin_confirmar, name=\"not confirmed\",\n    marker=dict(color=LIGHT_BLUE), hovertemplate=\"%{y:,} reform texts<extra>not confirmed</extra>\",\n)\nstyle_plotly(fig, yaxis_title=\"Reform texts\", height=440)\nfig.update_layout(barmode=\"stack\", bargap=0.35, hovermode=\"x unified\",\n                  legend=dict(orientation=\"h\", y=1.12, x=0))\nfig.update_yaxes(tickformat=\",\")\nfig.show(config=PLOTLY_CONFIG)\n```\n\n::: {#fig-link-status .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script type=\"text/javascript\">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.3.1.min.js\" integrity=\"sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=\" crossorigin=\"anonymous\"></script>                <div id=\"cea112e7-3fc2-4f2f-b925-5976be086b48\" class=\"plotly-graph-div\" style=\"height:440px; width:100%;\"></div>            <script type=\"text/javascript\">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"cea112e7-3fc2-4f2f-b925-5976be086b48\")) {                    Plotly.newPlot(                        \"cea112e7-3fc2-4f2f-b925-5976be086b48\",                        [{\"hovertemplate\":\"%{y:,} reform texts\\u003cextra\\u003econfirmed\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#2a78d6\"},\"name\":\"confirmed by content diff\",\"x\":[\"linked\\u003cbr\\u002f\\u003e(one candidate)\",\"ambiguous\\u003cbr\\u002f\\u003e(several candidates)\",\"claimed\\u003cbr\\u002f\\u003e(taken by another text)\",\"none\\u003cbr\\u002f\\u003e(no candidate that day)\"],\"y\":[1839,793,2,0],\"type\":\"bar\"},{\"hovertemplate\":\"%{y:,} reform texts\\u003cextra\\u003enot confirmed\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#9ec5f4\"},\"name\":\"not confirmed\",\"x\":[\"linked\\u003cbr\\u002f\\u003e(one candidate)\",\"ambiguous\\u003cbr\\u002f\\u003e(several candidates)\",\"claimed\\u003cbr\\u002f\\u003e(taken by another text)\",\"none\\u003cbr\\u002f\\u003e(no candidate that day)\"],\"y\":[635,373,14,68],\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"font\":{\"family\":\"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif\",\"size\":13,\"color\":\"#52514e\"},\"margin\":{\"l\":64,\"r\":24,\"t\":16,\"b\":40},\"hoverlabel\":{\"font\":{\"color\":\"#52514e\",\"size\":12},\"bgcolor\":\"white\",\"bordercolor\":\"#e1e0d9\"},\"legend\":{\"font\":{\"size\":12,\"color\":\"#52514e\"},\"orientation\":\"h\",\"y\":1.12,\"x\":0},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"height\":440,\"xaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"text\":\"\"},\"showgrid\":false,\"showline\":false,\"zeroline\":false,\"ticks\":\"\"},\"yaxis\":{\"tickfont\":{\"color\":\"#898781\"},\"title\":{\"font\":{\"color\":\"#52514e\",\"size\":13},\"text\":\"Reform texts\"},\"showgrid\":true,\"gridcolor\":\"#e1e0d9\",\"gridwidth\":1,\"showline\":false,\"zeroline\":false,\"ticks\":\"\",\"tickformat\":\",\"},\"barmode\":\"stack\",\"bargap\":0.35,\"hovermode\":\"x unified\"},                        {\"displaylogo\": false, \"displayModeBar\": \"hover\", \"modeBarButtonsToRemove\": [\"lasso2d\", \"select2d\", \"autoScale2d\"], \"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('cea112e7-3fc2-4f2f-b925-5976be086b48');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nReform texts by title-match state, split by whether the content diff confirmed a provision. The confirmed part of the `ambiguous` bar is what the content-diff check recovers on its own.\n:::\n:::\n\n\n::: {#cell-link-summary .cell execution_count=6}\n``` {.python .cell-code code-summary=\"The two sentences of the paragraph below, computed rather than written\"}\namb = ESTADOS.get(\"ambiguous\", 0)\nsin_ident = {int(a): n for a, n in resumen[\"unidentified_per_year\"].items()}\nSIN_IDENT_TOTAL = sum(sin_ident.values())\nRECIENTES = sum(n for a, n in sin_ident.items() if a >= 2000)\nANTIGUOS = sum(n for a, n in sin_ident.items() if a < 1990)\nMarkdown(\n    f\"Read together, the title match and the content-diff check identify \"\n    f\"{IDENTIFICADOS:,} of the {SNAPSHOTS:,} reform texts \"\n    f\"({IDENTIFICADOS / SNAPSHOTS * 100:.1f}%): \"\n    f\"{ENLAZADOS:,} where a single same-day provision named the instrument, plus \"\n    f\"{RESCATADOS:,} of the {amb:,} ambiguous dates where the content diff picked \"\n    f\"one candidate out of several. That leaves {SNAPSHOTS - IDENTIFICADOS:,} \"\n    f\"reform texts ({(SNAPSHOTS - IDENTIFICADOS) / SNAPSHOTS * 100:.1f}%) whose \"\n    f\"originating provision is still unknown, and — against intuition — these are not \"\n    f\"mostly the oldest ones: {RECIENTES:,} of them ({RECIENTES / max(SIN_IDENT_TOTAL, 1) * 100:.0f}%) \"\n    f\"fall in 2000 or later, and only {ANTIGUOS:,} before 1990. The reason is that the \"\n    f\"unresolved cases are dominated by days on which the gazette published several \"\n    f\"provisions all naming the same law — a modern habit, since a single reform \"\n    f\"package now often arrives as several decrees — and the content diff was not \"\n    f\"decisive between them. The genuinely old failures are of the other kind: \"\n    f\"{ESTADOS.get('none', 0):,} reform texts have no same-day candidate at all. \"\n    f\"Note also that confirmation is not the same as agreement: of the \"\n    f\"{ENLAZADOS:,} title-matched reform texts, \"\n    f\"{POR_CONFIRMACION.get('linked|confirmed', 0):,} were independently confirmed by \"\n    f\"content, and the rest simply had no digital candidate text to check against.\"\n)\n```\n\n::: {#link-summary .cell-output .cell-output-display .cell-output-markdown execution_count=6}\nRead together, the title match and the content-diff check identify 3,267 of the 3,724 reform texts (87.7%): 2,474 where a single same-day provision named the instrument, plus 793 of the 1,166 ambiguous dates where the content diff picked one candidate out of several. That leaves 457 reform texts (12.3%) whose originating provision is still unknown, and — against intuition — these are not mostly the oldest ones: 268 of them (59%) fall in 2000 or later, and only 135 before 1990. The reason is that the unresolved cases are dominated by days on which the gazette published several provisions all naming the same law — a modern habit, since a single reform package now often arrives as several decrees — and the content diff was not decisive between them. The genuinely old failures are of the other kind: 68 reform texts have no same-day candidate at all. Note also that confirmation is not the same as agreement: of the 2,474 title-matched reform texts, 1,839 were independently confirmed by content, and the rest simply had no digital candidate text to check against.\n:::\n:::\n\n\n### Instrument by instrument\n\n[@tbl-instruments] lists the twenty-five instruments with the most reform\ntexts, which is a reasonable proxy for the most heavily reformed pieces of\nMexican federal law. It is the same information the collection's\n`MANIFEST.md` carries — the file a human reads in full before publishing —\nreordered by size rather than by confidence.\n\nTwo columns beyond the instrument's own name and slug are worth explaining.\n**Reform texts** is how many dated versions of that instrument the collection\nholds, and therefore how many times its text changed within the Court's\ncoverage; the Constitution leads by a wide margin, which is itself a\nsubstantive fact about Mexican constitutionalism. **Span** gives the first\nand last year covered, which is where the Court's retrospective reach shows:\nan instrument may be older than its span suggests. How well each instrument's\nown texts are individually tied back to the *Diario Oficial* is a separate\nquestion from how many it has, and is not broken out here — [@fig-link-status]\nabove answers it for the collection as a whole.\n\n::: {#tbl-instruments .cell tbl-cap='The twenty-five instruments with the most reform texts.' execution_count=7}\n``` {.python .cell-code}\nTOPN = 25\ntabla = instrumentos.head(TOPN)\nlineas = [\n    \"| Instrument | Slug | Reform texts | Span |\",\n    \"|---|---|---:|---|\",\n]\nfor fila in tabla.itertuples():\n    span = (\n        f\"{fila.first_year}\\u2013{fila.last_year}\"\n        if fila.first_year and fila.last_year and fila.first_year != fila.last_year\n        else (str(fila.first_year) if fila.first_year else \"\\u2014\")\n    )\n    nombre = fila.nombre if len(fila.nombre) <= 70 else fila.nombre[:67] + \"\\u2026\"\n    lineas.append(f\"| {nombre} | `{fila.slug}` | {fila.snapshots:,} | {span} |\")\nMarkdown(\"\\n\".join(lineas))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=7}\n| Instrument | Slug | Reform texts | Span |\n|---|---|---:|---|\n| CONSTITUCIÓN Política de los Estados Unidos Mexicanos | `cpeum` | 300 | 1917–2026 |\n| CÓDIGO Penal Federal | `cpf` | 166 | 1931–2026 |\n| LEY General de Salud | `lgs` | 146 | 1984–2026 |\n| CÓDIGO Fiscal de la Federación | `cff` | 118 | 1981–2026 |\n| LEY Federal de Derechos | `lfd` | 92 | 1981–2025 |\n| LEY Orgánica de la Administración Pública Federal | `loapf` | 82 | 1976–2026 |\n| CÓDIGO de Comercio | `ccom` | 74 | 1889–2026 |\n| CÓDIGO Civil Federal | `ccf` | 62 | 1928–2025 |\n| LEY del Impuesto Especial sobre Producción y Servicios | `lieps` | 60 | 1980–2025 |\n| LEY Federal de Protección al Consumidor | `lfpc` | 57 | 1992–2025 |\n| LEY Federal del Trabajo | `lft` | 55 | 1970–2026 |\n| LEY del Impuesto al Valor Agregado | `liva` | 54 | 1978–2021 |\n| LEY de Instituciones de Crédito | `lic` | 53 | 1990–2025 |\n| LEY General del Equilibrio Ecológico y la Protección al Ambiente | `lgeepa` | 53 | 1988–2026 |\n| LEY de Vías Generales de Comunicación | `lvgc` | 51 | 1940–2025 |\n| LEY Orgánica del Congreso General de los Estados Unidos Mexicanos | `locg` | 47 | 1999–2025 |\n| LEY del Seguro Social | `lss` | 44 | 1995–2026 |\n| LEY Monetaria de los Estados Unidos Mexicanos | `lmeum` | 44 | 1931–2026 |\n| LEY Aduanera | `ladua` | 40 | 1995–2025 |\n| LEY de Coordinación Fiscal | `lcf` | 40 | 1978–2024 |\n| REGLAMENTO de la Cámara de Diputados | `reg-diputados` | 40 | 2010–2025 |\n| LEY Federal del Impuesto sobre Automóviles Nuevos | `lfisan` | 34 | 1996–2025 |\n| LEY del Instituto del Fondo Nacional de la Vivienda para los Trabaj… | `lifnvt` | 31 | 1972–2025 |\n| LEY Federal de los Trabajadores al Servicio del Estado, Reglamentar… | `lftse` | 31 | 1963–2026 |\n| REGLAMENTO del Senado de la República | `reg-senado` | 31 | 2010–2024 |\n:::\n:::\n\n\n::: {#cell-tail-summary .cell execution_count=8}\n``` {.python .cell-code code-summary=\"The distribution behind the table's long tail\"}\nun_solo = int((instrumentos[\"snapshots\"] == 1).sum())\ntodo_enlazado = int((instrumentos[\"snapshots\"] == instrumentos[\"linked\"]).sum())\nsin_enlace = int((instrumentos[\"linked\"] == 0).sum())\nmediana = int(instrumentos[\"snapshots\"].median())\nMarkdown(\n    f\"Beyond the top of the table the distribution is very uneven: the median \"\n    f\"instrument has {mediana} reform texts, {un_solo} of the {CON_DIRECTORIO} \"\n    f\"instruments have exactly one — laws never reformed since they were enacted, \"\n    f\"or enacted so recently that the Court's table holds a single row — \"\n    f\"{todo_enlazado} have every one of their reform texts resolved by a same-day \"\n    f\"title match alone, and {sin_enlace} have none resolved by it at all.\"\n)\n```\n\n::: {#tail-summary .cell-output .cell-output-display .cell-output-markdown execution_count=8}\nBeyond the top of the table the distribution is very uneven: the median instrument has 5 reform texts, 66 of the 315 instruments have exactly one — laws never reformed since they were enacted, or enacted so recently that the Court's table holds a single row — 119 have every one of their reform texts resolved by a same-day title match alone, and 9 have none resolved by it at all.\n:::\n:::\n\n\n## Every federal law is in the release\n\nThe catalogue lists 316 federal instruments; 315 have a directory in the\ncollection today. The one gap, the General Ordinance of the Navy (`oga`), was\npublished between 1 and 8 January 1912 — five years before the *Diario\nOficial*'s own coverage begins in 1917 — and the Court does not index it\neither, so there is nothing in either source to build it from. Every\ninstrument the two sources between them can date, this collection has.\n\nCompleteness here is not asserted, it is checked, and the check is cheap\nbecause of how the release is shaped: one tarball per catalogue entry, named\nafter its `abrev`, and nothing else. So \"does the release have every law\"\nreduces to comparing two lists — the catalogue's own `abrev` column against\nthe tarballs the release actually publishes. That same list of tarballs is\nwhat a downstream reader walks to *use* the collection: `nota2md`'s\n`iter_current_federal_laws()` opens one at a time and yields the current text\nof the law inside, so consuming the whole collection and confirming it is\ncomplete are the same pass over the data, not two.\n\n```python\nfrom nota2md import iter_current_federal_laws\n\ntexts = list(iter_current_federal_laws())\nlen(texts)  # one per instrument the release currently publishes a tarball for\n```\n\n## How this collection is published\n\nThe corpus is published, since August 2026, as the\n[`scjn-leyes`](https://github.com/INGEOTEC/LegalIA/releases/tag/scjn-leyes)\nGitHub release.\n\n**One reproducible tarball per instrument.** The packaging step writes one\n`<slug>.tgz` for each instrument rather than a single archive for the whole\ncollection, because a consumer almost always wants one law, and a later run\nthen has to re-upload only the laws that changed. Every member is prefixed\nwith the instrument's slug, so a tarball unpacks anywhere without stepping on\nanything:\n\n```\n<slug>/<date>.md            the reform texts, each with its provenance header\n<slug>/indice.json          the codNota link and how it was decided\n<slug>/notas/nota-<cod>.md  the DOF text of every candidate considered\n```\n\nThe gazette notes travel *with* the reform texts on purpose: they are the text\neach link was decided against, so shipping both makes a link auditable without\ngoing back to the network. Two small text assets accompany the tarballs — a\n`MANIFEST.md` ranking every instrument by confidence, and a `SHA256SUMS.txt`.\nEach tarball is **byte-reproducible**: gzip is stamped with a zero timestamp,\nmembers are added in sorted order, and their times, modes and ownership are\nfixed. Identical data therefore yields an identical file, which is what makes\nit possible to tell an unchanged instrument from a changed one by comparing\nbytes rather than guessing, which is what makes \"re-upload only the laws that\nchanged\" a byte comparison instead of a guess.\n\n**Published as GitHub release assets**, like the DOF notes archive, and for\nthe same reason: data is never committed to this repository.\n\n**Published by hand, always, by design.** This is the one operational\ndifference between this collection and the others, and it is a statement about\nthe source rather than a gap in automation. The notes archive is rebuilt and\nrepublished monthly by a workflow with no human in the loop, because its source\nis the gazette's own service and an error there is the gazette's error. The\nCourt's search, by contrast, can return a completely wrong document, and a\nwrong document would enter the corpus looking exactly like a right one — so\nthe packaging script never invokes `gh`, no workflow may publish this\ncollection, and `MANIFEST.md` is read in full before anything is uploaded.\nSeparating packaging from publishing keeps the human judgement where the risk\nactually is.\n\n**Reading it back.** Because one instrument is one asset, downloading a law\nneeds no library at all:\n\n```bash\ngh release download scjn-leyes --repo INGEOTEC/LegalIA --pattern 'lft.tgz'\ntar xzf lft.tgz          # -> lft/<date>.md, lft/indice.json, lft/notas/\n```\n\nReading the corpus from Python is a call rather than an exercise:\n`nota2md.download_scjn_leyes_corpus(\"lft\")` gives one law's reform texts and\ntheir `codNota` links, `download_scjn_leyes_index()` the reverse index\n`codNota → (law, reform text)`, `download_scjn_leyes_catalog()` the catalogue\nof every law the release publishes, and `iter_current_federal_laws()` the\ncurrent text of every law, one at a time, without loading any of their\nhistory.\n\n**Licensing and attribution are still open.** The reform texts are the\nSupreme Court's editorial work over public legal texts, and the terms on\nwhich they may be redistributed have yet to be settled; this page is where\nthe answer will be recorded. Nothing about the pipeline depends on that\nanswer — the scripts reconstruct the corpus from the sources on any machine —\nbut what the release carries does.\n\n## Methodological note {.unnumbered .appendix}\n\nThe material described here is built by four scripts in\n[`scripts/`](https://github.com/INGEOTEC/LegalIA/tree/master/scripts) —\n`discover_federal_laws.py`, `fetch_scjn_legislacion.py`,\n`enlaza_scjn_legislacion.py` and `empaqueta_scjn_leyes.py` — plus a small\nnumber of single-law scripts for instruments the Court does not index yet\n(e.g. `fetch_lfiiedb_dof.py`), whose text is taken directly from the DOF\ninstead. The SCJN-specific logic they share lives in its own package,\n[`scjn`](https://pypi.org/project/scjn/) — the transport (`scjn.api`) and\nthe disk-first release readers (`scjn.release`); the *Diario Oficial* side\ncomes from [`dofjson`](https://pypi.org/project/dofjson/), and\n[`nota2md`](https://pypi.org/project/nota2md/) links a snapshot to the DOF\n`codNota` that produced it.\n\nThe corpus is published as release assets and is never committed to git, so\nthis page does not read it directly — downloading 315 tarballs to draw two\nfigures would be a poor trade. It reads\n[`data/scjn-leyes-summary.json`](https://github.com/INGEOTEC/LegalIA/blob/master/website/pages/data/scjn-leyes-summary.json),\nan aggregate summary produced by `scripts/resume_scjn_leyes.py` from the crawl\nthat the August 2026 release was packaged from: headline counts, reform texts\nper year, the title-match states crossed with content confirmation, and one\nrow per instrument. That script reuses the very function\n`empaqueta_scjn_leyes.py` uses to build `MANIFEST.md`, so the numbers on this\npage, the numbers a human reads before publishing, and the manifest shipped\nwith the release cannot drift apart. Regenerating the summary after a fresh\ncrawl is one command:\n\n```bash\n./scripts/resume_scjn_leyes.py --outdir scripts/scjn \\\n    --destino website/pages/data/scjn-leyes-summary.json\n```\n\nThis page was written by the LegalIA team together with Claude, Anthropic's\ncoding assistant, through [Claude Code](https://claude.com/claude-code): the\nassistant implemented the summary step, produced the figures and drafted the\naccompanying text. The authors verified the numbers against the corpus on disk\nand are responsible for the interpretations advanced here.\n\n",
    "supporting": [
      "leyes_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script type=\"text/javascript\">\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.3.1.min\"</script>\n\n"
      ]
    }
  }
}