<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-28">

<title>The Federal Laws Corpus: Mexico’s Statute Book, One Snapshot per Reform – LegalIA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-15b7c4a5ef1133b45a72edd940cf6f53.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script type="text/javascript">
window.PlotlyConfig = {MathJaxConfig: 'local'};
if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
</script>
<script type="module">import "https://cdn.plot.ly/plotly-3.3.1.min"</script>



</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">LegalIA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/dataset.html"> 
<span class="menu-text">Dataset</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/titles.html"> 
<span class="menu-text">DOF Titles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../pages/leyes.html" aria-current="page"> 
<span class="menu-text">Federal Laws</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/tools.html"> 
<span class="menu-text">Tools</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/dof2md.html"> 
<span class="menu-text">dof2md</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/references.html"> 
<span class="menu-text">References</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/INGEOTEC/LegalIA/issues/views/8351"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://legalia.readthedocs.io/"> 
<span class="menu-text">Docs</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/INGEOTEC/LegalIA"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-a-snapshot-is" id="toc-what-a-snapshot-is" class="nav-link active" data-scroll-target="#what-a-snapshot-is"><span class="header-section-number">1</span> What a snapshot is</a></li>
  <li><a href="#why-the-supreme-court-and-not-only-the-chamber-of-deputies" id="toc-why-the-supreme-court-and-not-only-the-chamber-of-deputies" class="nav-link" data-scroll-target="#why-the-supreme-court-and-not-only-the-chamber-of-deputies"><span class="header-section-number">2</span> Why the Supreme Court and not only the Chamber of Deputies</a>
  <ul class="collapse">
  <li><a href="#a-caveat-about-the-source" id="toc-a-caveat-about-the-source" class="nav-link" data-scroll-target="#a-caveat-about-the-source"><span class="header-section-number">2.1</span> A caveat about the source</a></li>
  </ul></li>
  <li><a href="#from-two-catalogues-to-one-corpus" id="toc-from-two-catalogues-to-one-corpus" class="nav-link" data-scroll-target="#from-two-catalogues-to-one-corpus"><span class="header-section-number">3</span> From two catalogues to one corpus</a>
  <ul class="collapse">
  <li><a href="#seeding-which-instruments-exist" id="toc-seeding-which-instruments-exist" class="nav-link" data-scroll-target="#seeding-which-instruments-exist"><span class="header-section-number">3.1</span> Seeding: which instruments exist</a></li>
  <li><a href="#crawling-finding-the-right-document" id="toc-crawling-finding-the-right-document" class="nav-link" data-scroll-target="#crawling-finding-the-right-document"><span class="header-section-number">3.2</span> Crawling: finding the right document</a></li>
  <li><a href="#the-header-as-a-provenance-record" id="toc-the-header-as-a-provenance-record" class="nav-link" data-scroll-target="#the-header-as-a-provenance-record"><span class="header-section-number">3.3</span> The header as a provenance record</a></li>
  <li><a href="#linking-each-snapshot-to-the-provision-that-caused-it" id="toc-linking-each-snapshot-to-the-provision-that-caused-it" class="nav-link" data-scroll-target="#linking-each-snapshot-to-the-provision-that-caused-it"><span class="header-section-number">3.4</span> Linking each snapshot to the provision that caused it</a></li>
  </ul></li>
  <li><a href="#what-the-corpus-looks-like-today" id="toc-what-the-corpus-looks-like-today" class="nav-link" data-scroll-target="#what-the-corpus-looks-like-today"><span class="header-section-number">4</span> What the corpus looks like today</a>
  <ul class="collapse">
  <li><a href="#how-deep-the-history-goes" id="toc-how-deep-the-history-goes" class="nav-link" data-scroll-target="#how-deep-the-history-goes"><span class="header-section-number">4.1</span> How deep the history goes</a></li>
  <li><a href="#how-much-of-it-is-identified-and-what-the-second-signal-adds" id="toc-how-much-of-it-is-identified-and-what-the-second-signal-adds" class="nav-link" data-scroll-target="#how-much-of-it-is-identified-and-what-the-second-signal-adds"><span class="header-section-number">4.2</span> How much of it is identified, and what the second signal adds</a></li>
  <li><a href="#instrument-by-instrument" id="toc-instrument-by-instrument" class="nav-link" data-scroll-target="#instrument-by-instrument"><span class="header-section-number">4.3</span> Instrument by instrument</a></li>
  </ul></li>
  <li><a href="#cases-the-pipeline-could-not-handle-on-its-own" id="toc-cases-the-pipeline-could-not-handle-on-its-own" class="nav-link" data-scroll-target="#cases-the-pipeline-could-not-handle-on-its-own"><span class="header-section-number">5</span> Cases the pipeline could not handle on its own</a>
  <ul class="collapse">
  <li><a href="#lisipl-a-catalogue-name-no-search-can-match" id="toc-lisipl-a-catalogue-name-no-search-can-match" class="nav-link" data-scroll-target="#lisipl-a-catalogue-name-no-search-can-match"><span class="header-section-number">5.1</span> <code>lisipl</code> — a catalogue name no search can match</a></li>
  <li><a href="#lfca-a-new-law-that-repeals-an-indexed-one" id="toc-lfca-a-new-law-that-repeals-an-indexed-one" class="nav-link" data-scroll-target="#lfca-a-new-law-that-repeals-an-indexed-one"><span class="header-section-number">5.2</span> <code>lfca</code> — a new law that repeals an indexed one</a></li>
  <li><a href="#lfiiedb-the-same-pattern-without-the-history" id="toc-lfiiedb-the-same-pattern-without-the-history" class="nav-link" data-scroll-target="#lfiiedb-the-same-pattern-without-the-history"><span class="header-section-number">5.3</span> <code>lfiiedb</code> — the same pattern, without the history</a></li>
  <li><a href="#oga-outside-the-gazettes-reach" id="toc-oga-outside-the-gazettes-reach" class="nav-link" data-scroll-target="#oga-outside-the-gazettes-reach"><span class="header-section-number">5.4</span> <code>oga</code> — outside the gazette’s reach</a></li>
  <li><a href="#what-these-cases-have-in-common" id="toc-what-these-cases-have-in-common" class="nav-link" data-scroll-target="#what-these-cases-have-in-common"><span class="header-section-number">5.5</span> What these cases have in common</a></li>
  </ul></li>
  <li><a href="#how-this-collection-is-published" id="toc-how-this-collection-is-published" class="nav-link" data-scroll-target="#how-this-collection-is-published"><span class="header-section-number">6</span> How this collection is published</a></li>
  
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Federal Laws Corpus: Mexico’s Statute Book, One Snapshot per Reform</h1>
<p class="subtitle lead">How 3,724 dated versions of 315 federal instruments were assembled, and what can be trusted about them</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Mexico’s federal legislation is easy to read today and hard to read historically. The Chamber of Deputies publishes the text of every federal law as it stands right now, together with the list of decrees that produced it, but not the intermediate wording those decrees left behind; the Diario Oficial de la Federación publishes each reform decree and nothing else, so the consolidated text of a law on a given date exists only as the sum of everything published before it. This page documents a corpus that closes that gap: 3,724 Markdown snapshots covering 315 of the 316 federal instruments in the Chamber’s catalogue, each one the complete text of an instrument as it read on the day a particular reform took effect, taken from the Supreme Court’s legislative database, and — for 87.7% of them — tied to the specific Diario Oficial provision that caused the change. We describe where the material comes from, the two independent signals used to identify that provision, the four catalogue entries that no unattended crawl could handle, and how the collection is published and can be downloaded.</p>
  </div>
</div>


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://colab.research.google.com/github/INGEOTEC/LegalIA/blob/master/website/pages/leyes.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid figure-img"></a></p>
<figcaption>Open in Colab</figcaption>
</figure>
</div>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Imports, the styling shared by every figure, and the aggregate summary this page reads</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> urllib.request <span class="im">import</span> urlopen</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.graph_objects <span class="im">as</span> go</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Validated categorical palette (light mode), in fixed assignment order — the</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># same one `DOF Titles` and `Dataset` use, so a colour means the same thing</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># across the site.</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>BLUE, GREEN, MAGENTA, YELLOW <span class="op">=</span> <span class="st">"#2a78d6"</span>, <span class="st">"#008300"</span>, <span class="st">"#e87ba4"</span>, <span class="st">"#eda100"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>LIGHT_BLUE <span class="op">=</span> <span class="st">"#9ec5f4"</span>  <span class="co"># step 200 of the blue sequential ramp</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>INK, MUTED, GRID, AXIS <span class="op">=</span> <span class="st">"#52514e"</span>, <span class="st">"#898781"</span>, <span class="st">"#e1e0d9"</span>, <span class="st">"#c3c2b7"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>PLOTLY_FONT <span class="op">=</span> <span class="st">"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> style_plotly(fig, <span class="op">*</span>, yaxis_title<span class="op">=</span><span class="st">""</span>, height<span class="op">=</span><span class="dv">430</span>):</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    fig.update_layout(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        font<span class="op">=</span><span class="bu">dict</span>(family<span class="op">=</span>PLOTLY_FONT, size<span class="op">=</span><span class="dv">13</span>, color<span class="op">=</span>INK),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>        paper_bgcolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>        plot_bgcolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        height<span class="op">=</span>height,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        margin<span class="op">=</span><span class="bu">dict</span>(l<span class="op">=</span><span class="dv">64</span>, r<span class="op">=</span><span class="dv">24</span>, t<span class="op">=</span><span class="dv">16</span>, b<span class="op">=</span><span class="dv">40</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>        hoverlabel<span class="op">=</span><span class="bu">dict</span>(bgcolor<span class="op">=</span><span class="st">"white"</span>, bordercolor<span class="op">=</span>GRID, font<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>INK, size<span class="op">=</span><span class="dv">12</span>)),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        legend<span class="op">=</span><span class="bu">dict</span>(font<span class="op">=</span><span class="bu">dict</span>(size<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span>INK)),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    fig.update_xaxes(</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        showgrid<span class="op">=</span><span class="va">False</span>, showline<span class="op">=</span><span class="va">False</span>, zeroline<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>        ticks<span class="op">=</span><span class="st">""</span>, tickfont<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>MUTED), title_text<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    fig.update_yaxes(</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>        showgrid<span class="op">=</span><span class="va">True</span>, gridcolor<span class="op">=</span>GRID, gridwidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>        showline<span class="op">=</span><span class="va">False</span>, zeroline<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>        ticks<span class="op">=</span><span class="st">""</span>, tickfont<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>MUTED),</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>        title_text<span class="op">=</span>yaxis_title, title_font<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>INK, size<span class="op">=</span><span class="dv">13</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>PLOTLY_CONFIG <span class="op">=</span> {</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"displaylogo"</span>: <span class="va">False</span>,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">"displayModeBar"</span>: <span class="st">"hover"</span>,</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"modeBarButtonsToRemove"</span>: [<span class="st">"lasso2d"</span>, <span class="st">"select2d"</span>, <span class="st">"autoScale2d"</span>],</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Every figure and every number in the prose below comes from this one file.</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co"># The corpus itself lives in the `scjn-leyes` release — one tarball per</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="co"># instrument — and is never committed to git, so, unlike `Dataset`, which</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="co"># queries the GitHub API live, this page reads the aggregate summary</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co"># `scripts/resume_scjn_leyes.py` distils from the crawl the release was</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="co"># packaged from: counts, per-year totals and one row per instrument,</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="co"># regenerated by re-running that script and versioned alongside the page.</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>RESUMEN <span class="op">=</span> <span class="st">"data/scjn-leyes-summary.json"</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>RAW <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/INGEOTEC/LegalIA/master/website/pages/"</span> <span class="op">+</span> RESUMEN</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>local <span class="op">=</span> Path(RESUMEN)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> local.is_file():  <span class="co"># rendering the site</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>    resumen <span class="op">=</span> json.loads(local.read_text(encoding<span class="op">=</span><span class="st">"utf-8"</span>))</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:               <span class="co"># running the notebook on Colab</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> urlopen(RAW) <span class="im">as</span> respuesta:</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>        resumen <span class="op">=</span> json.loads(respuesta.read().decode(<span class="st">"utf-8"</span>))</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>instrumentos <span class="op">=</span> pd.DataFrame(resumen[<span class="st">"instruments"</span>])</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>por_anio <span class="op">=</span> pd.Series(</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    {<span class="bu">int</span>(anio): n <span class="cf">for</span> anio, n <span class="kw">in</span> resumen[<span class="st">"snapshots_per_year"</span>].items()}</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>).sort_index()</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="co"># Headline figures, named once here and reused by the prose, the table and the</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="co"># figure captions so no number on this page is typed by hand twice.</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>SNAPSHOTS <span class="op">=</span> resumen[<span class="st">"snapshots"</span>]</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>CATALOGO <span class="op">=</span> resumen[<span class="st">"catalogue_entries"</span>]</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>CON_DIRECTORIO <span class="op">=</span> resumen[<span class="st">"instruments_with_directory"</span>]</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>ESTADOS <span class="op">=</span> resumen[<span class="st">"title_link_status"</span>]</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>POR_CONFIRMACION <span class="op">=</span> resumen[<span class="st">"title_link_status_by_confirmation"</span>]</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>ENLAZADOS <span class="op">=</span> resumen[<span class="st">"linked_by_title"</span>]</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>CONFIRMADOS <span class="op">=</span> resumen[<span class="st">"content_diff_confirmed"</span>]</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="co"># A date is identified when the title signal resolved it *or* when the content</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="co"># diff resolved a date the title signal left ambiguous — the two signals are</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="co"># complementary, and this is the coverage figure that matters to a reader.</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>RESCATADOS <span class="op">=</span> POR_CONFIRMACION.get(<span class="st">"ambiguous|confirmed"</span>, <span class="dv">0</span>)</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>IDENTIFICADOS <span class="op">=</span> ENLAZADOS <span class="op">+</span> RESCATADOS</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="3" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On Colab, install the packages this notebook needs:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># %pip install pandas plotly</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="what-a-snapshot-is" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="what-a-snapshot-is"><span class="header-section-number">1</span> What a snapshot is</h2>
<p>The unit of this collection is not a law and not a decree: it is a <strong>snapshot</strong> — one plain-text file holding the <em>complete</em> text of one federal instrument as it read on one particular date. The file is named after that date (<code>01-04-2025.md</code>) and lives in a directory named after the instrument (<code>cpeum/</code> for the Constitution, <code>lft/</code> for the Federal Labour Law), so an instrument’s directory is its own history laid out in files: as many files as there are dates on which its wording changed.</p>
<p>This matters because it is the version of the statute book that is otherwise missing. To know what the Federal Labour Law said in 1998 one can consult the 1998 reform decree in the <em>Diario Oficial</em> — but a decree only says which articles were replaced and by what, not what the resulting law read like as a whole. Reconstructing the whole from the parts means replaying every decree in order, which the <a href="https://pypi.org/project/nota2md/"><code>nota2md</code></a> package can do (<code>reconstruct_legal_provisions</code>) but which depends on every intermediate decree being available as digital text — and for anything published before roughly 1999 it is not: it exists only as scanned images that have to be read by OCR. A snapshot sidesteps the reconstruction entirely, because somebody has already done the consolidation: it <em>is</em> the law as of that date, in one piece.</p>
<p>The format is Markdown, and that choice is deliberate. Markdown is plain text, so the files are readable in any editor, searchable with <code>grep</code>, diffable line by line against each other, and stable in version control — the same reasons the rest of LegalIA converts legal texts to Markdown rather than keeping PDFs or <code>.docx</code> files around. It also keeps just enough structure to be useful — a heading is a heading, an emphasized run stays emphasized — without pretending to a legal-document schema the source never had. Each file opens with a short YAML header recording where it came from, which is described in detail below; everything after the header is the text of the law.</p>
</section>
<section id="why-the-supreme-court-and-not-only-the-chamber-of-deputies" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="why-the-supreme-court-and-not-only-the-chamber-of-deputies"><span class="header-section-number">2</span> Why the Supreme Court and not only the Chamber of Deputies</h2>
<p>The obvious place to look for federal legislation is the Chamber of Deputies’ own <a href="https://www.diputados.gob.mx/LeyesBiblio/index.htm">LeyesBiblio</a>, and LegalIA does use it — but for a different purpose than one might expect. What LeyesBiblio offers is the <strong>current</strong> text of each law, plus the list of reform decrees that produced it. That is a catalogue and a bibliography: it tells you which instruments exist and which <em>Diario Oficial</em> publications changed them, but not what any of them said in between.</p>
<p>The Supreme Court’s legislative database (<a href="https://legislacion.scjn.gob.mx/Buscador/">legislacion.scjn.gob.mx</a>) is organized the other way around. For each instrument it keeps a table of reforms, and for each row of that table it serves the consolidated text of the instrument <strong>as it stood after that reform</strong> — a full document, not a summary of the change. The Court maintains this because its own work requires it: a case is decided under the law in force at the relevant time, not under the law in force today. That editorial effort, undertaken for judicial reasons, is exactly what a historical corpus needs, and it is why the Court is this collection’s primary source of <em>content</em> while the Chamber remains its source of <em>scope</em> — which instruments exist, what each is called, and when each was last reformed.</p>
<section id="a-caveat-about-the-source" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="a-caveat-about-the-source"><span class="header-section-number">2.1</span> A caveat about the source</h3>
<p>The Court’s database is a source of convenience, not the source of authority. The authoritative text of Mexican federal law is what the <em>Diario Oficial de la Federación</em> published; the Court’s consolidated versions are an editorial product built on top of it, and they behave like one:</p>
<ul>
<li><strong>There is no stable address for a document.</strong> The search interface hands out URLs whose <code>?q=</code> token belongs to the session that generated it, so a link cannot be cited, bookmarked, or re-fetched later. The only reproducible record of how a file was obtained is what was searched for and what came back — which is precisely why every snapshot carries that pair in its header.</li>
<li><strong>The search can return the wrong document entirely.</strong> A query for one law can rank a different law, or an internal court agreement that merely mentions the law, above the law itself. Two mechanisms guard against this: a similarity score between what was searched and what was found, recorded in every file, and a filter that discards the Court’s own internal agreements. Neither is infallible, which is why publication of this collection is a manual act, described at the end of this page.</li>
<li><strong>Editorial matter is mixed into the text.</strong> The Court annotates its consolidated texts with editor’s notes (“N. DE E.”) explaining, for example, that a reform was later invalidated. These are the Court speaking, not the legislature, and are stripped at conversion time so they never masquerade as statutory text.</li>
</ul>
<p>Because the source is editorial, every file declares its provenance in its own header — <code>fuente: scjn</code> — and nothing in LegalIA ever silently mixes these texts with Markdown built from the <em>Diario Oficial</em> itself.</p>
</section>
</section>
<section id="from-two-catalogues-to-one-corpus" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="from-two-catalogues-to-one-corpus"><span class="header-section-number">3</span> From two catalogues to one corpus</h2>
<p>The pipeline that builds the collection has four stages, run in order, each one a separate script under <a href="https://github.com/INGEOTEC/LegalIA/tree/master/scripts"><code>scripts/</code></a> (<a href="#fig-pipeline" class="quarto-xref">Figure&nbsp;1</a>). What follows describes not only what each stage does but what it <em>decides</em>, since the decisions are where a corpus of this kind either earns or loses a reader’s trust.</p>
<div id="fig-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    D[Cámara de Diputados&lt;br/&gt;LeyesBiblio] --&gt;|nombre, abrev, actualizado| C[catalogo.json&lt;br/&gt;extract_scjn_titles.py]
    C --&gt;|search by nombre| S[SCJN buscador&lt;br/&gt;fetch_scjn_legislacion.py]
    S --&gt;|one .docx per reform| M[Markdown snapshots&lt;br/&gt;DD-MM-YYYY.md + YAML header]
    A[notas-archivo release] --&gt;|codNota + titulo + fecha| T[titles dataset&lt;br/&gt;download_legal_provisions_titles]
    M --&gt; L[enlaza_scjn_legislacion.py]
    T --&gt; L
    N[dofjson.get_nota&lt;br/&gt;DOF Markdown] --&gt; L
    L --&gt;|indice.json per instrument| P[empaqueta_scjn_leyes.py&lt;br/&gt;one slug.tgz + MANIFEST.md]
    P -.-&gt;|manual review, manual upload| R[(scjn-leyes release)]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The pipeline. Two catalogues enter — the Chamber of Deputies’ list of instruments and the DOF’s own archive of published provision titles — and one corpus of dated snapshots, each linked to the provision that produced it, comes out. The dotted arrow is the only step no script performs.
</figcaption>
</figure>
</div>
<section id="seeding-which-instruments-exist" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="seeding-which-instruments-exist"><span class="header-section-number">3.1</span> Seeding: which instruments exist</h3>
<p>The first stage asks the Chamber of Deputies one question — what is in the catalogue? — and keeps three fields per entry: the instrument’s official <code>nombre</code>, its short slug (<code>abrev</code>, which becomes the directory name), and <code>actualizado</code>, the date of its most recent reform. The catalogue’s own list of reform provisions is deliberately <strong>not</strong> carried forward. That is a design correction, not an oversight: an earlier design linked snapshots to <em>Diario Oficial</em> provisions by trusting the Chamber’s list of them, which makes the corpus inherit whatever gaps and errors that list has. The current design derives the link independently, from the DOF’s own archive, and uses the Chamber only for scope. Where the two disagree, the disagreement is visible instead of absorbed.</p>
<p><code>actualizado</code> earns its place by making refreshes cheap. Once the whole collection has been crawled start to finish, a later run can skip an instrument that has not been reformed since — but only if it already has snapshots on disk. An instrument with no snapshots is retried on every single refresh, forever, which is what makes the collection self-healing for laws the Court has not indexed yet: when the Court catches up, the next refresh picks the law up with nothing to configure by hand.</p>
</section>
<section id="crawling-finding-the-right-document" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="crawling-finding-the-right-document"><span class="header-section-number">3.2</span> Crawling: finding the right document</h3>
<p>The second stage searches the Court’s database for each catalogue name, and this is where most of the difficulty lives. A search returns a ranked list of documents; the crawler has to decide which one, if any, is the instrument it was looking for. It discards the Court’s own internal agreements, rejects candidates whose title is too far from what was searched for, flags as <code>sospechoso</code> (<em>suspect</em>) the ones that are close but not close enough, and picks the best remaining match. For the winner it walks the reform table, downloads one <code>.docx</code> per row, converts it to Markdown and strips the editorial notes.</p>
<p>One limit of this stage is worth stating plainly, because it is live rather than historical. The results grid paginates, and the crawler reads a single page — the largest the page-size dropdown offers, <strong>50 records</strong>. An instrument mentioned by more than 50 documents would therefore be invisible even though the Court holds it, and the failure looks like an ordinary absence rather than an error. That this is a real failure mode and not a hypothetical one is known from the Income Tax Law: searching for it returns 42 records, the top ten of which are internal agreements of the Court’s own plenary session that mention the law in passing, and while the crawler read only the first ten the statute itself sat at position 14, invisible. Reading 50 at once fixed that case and every other one in the catalogue — no entry in it exceeds 50 today — but the trade-off was taken knowingly, and the number is recorded here so that a future gap of this shape is recognized immediately instead of rediscovered.</p>
<p>The stage is resumable at two levels — a file already on disk is never re-downloaded, and the index of the last instrument attempted is checkpointed, so an interrupted run resumes rather than restarts — and rate-limited, out of courtesy to an unofficial service that was never designed to be crawled.</p>
</section>
<section id="the-header-as-a-provenance-record" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="the-header-as-a-provenance-record"><span class="header-section-number">3.3</span> The header as a provenance record</h3>
<p>Every snapshot opens with a YAML header. It is short, and each line is there to answer a question a sceptical reader would ask:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fuente</span><span class="kw">:</span><span class="at"> scjn</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nombre_buscado</span><span class="kw">:</span><span class="at"> CONSTITUCIÓN Política de los Estados Unidos Mexicanos</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ordenamiento</span><span class="kw">:</span><span class="at"> CONSTITUCION POLITICA DE LOS ESTADOS UNIDOS MEXICANOS</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fecha_publicacion</span><span class="kw">:</span><span class="at"> 01-04-2025</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">fecha_expedicion</span><span class="kw">:</span><span class="at"> 01-04-2025</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">categoria</span><span class="kw">:</span><span class="at"> DECRETO</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ratio_similitud</span><span class="kw">:</span><span class="at"> </span><span class="fl">1.000</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sospechoso</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><strong><code>fuente</code></strong> — where the text came from: <code>scjn</code> for the Court’s consolidated version, <code>dof</code> for the handful of files taken directly from the <em>Diario Oficial</em> (see the cases below). This is the field that keeps an editorial text from ever being mistaken for the official one.</li>
<li><strong><code>ordenamiento</code></strong> — the title of the document the <strong>Supreme Court</strong> actually served, verbatim.</li>
<li><strong><code>nombre_buscado</code></strong> — the exact string that was searched for, which is the instrument’s name as the <strong>Chamber of Deputies’ catalogue</strong> gives it (the <code>nombre</code> seeded in the first stage) or, for the one entry that needs it, the <code>nombre_scjn</code> override described below. The pair is therefore not only <em>what was asked</em> / <em>what came back</em>: it is <strong>one source’s name for the law against the other source’s name for the same law</strong>, which is why the two can differ at all and why the similarity score below is worth recording. Because the Court’s search has no citable URL, the pair is also the only way to reproduce by hand how a given file was reached. It is written only when the two differ after normalizing accents, case and whitespace — so its mere presence marks a file whose identification deserves a second look, and <code>grep -l nombre_buscado:</code> is a complete audit.</li>
<li><strong><code>ratio_similitud</code></strong> and <strong><code>sospechoso</code></strong> — how close those two strings are (1.000 meaning identical after normalization) and whether that closeness fell into the band where a match is kept but flagged. They record the crawler’s confidence rather than hiding it behind a yes/no decision.</li>
<li><strong><code>fecha_publicacion</code></strong> and <strong><code>fecha_expedicion</code></strong> — the date the reform was published and the date it was issued, as the Court’s reform table gives them; the first is the snapshot’s identity and its file name.</li>
<li><strong><code>categoria</code></strong> — the kind of instrument that produced the reform, typically <code>DECRETO</code>.</li>
</ul>
<p>The header plays the same role here that the raw JSON record of a note plays on the <code>Dataset</code> page: it is the level at which a reader can check the data rather than take it on faith.</p>
</section>
<section id="linking-each-snapshot-to-the-provision-that-caused-it" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="linking-each-snapshot-to-the-provision-that-caused-it"><span class="header-section-number">3.4</span> Linking each snapshot to the provision that caused it</h3>
<p>The final stage of the pipeline answers a question the Court’s database does not: <strong>which published provision produced this version of the law?</strong> Its output is one <code>indice.json</code> per instrument, pairing each snapshot with a <code>codNota</code> — the <em>Diario Oficial</em>’s own identifier for a legal provision.</p>
<p>It is worth being explicit about why this link is worth the trouble, since it is the most laborious part of the whole pipeline. Four things depend on it.</p>
<p>First, <strong>verification</strong>. A snapshot is an editorial product of the Court; the provision it points to is the official text. Having both means any claim about the corpus can be checked against the gazette — and, once digital text exists on both sides, checked automatically rather than by hand.</p>
<p>Second, <strong>joining</strong>. The <code>codNota</code> is the key that the rest of LegalIA is built around: it is what the DOF notes archive is indexed by, what the <a href="../pages/titles.html">titles dataset</a> carries for all 1.2 million published provisions, and what the reform-history release records. A linked snapshot therefore inherits everything already known about its provision — its official title, its issuing body, its full text where digitized — and lets this corpus be used together with the others instead of beside them.</p>
<p>Third, <strong>dating and ordering</strong>. A snapshot’s file name records a publication date, but a date is not an identifier: the gazette can publish several reforms to the same law on the same day, and an instrument’s history is not well-ordered until each version is tied to a specific provision.</p>
<p>Fourth, <strong>provenance for anything built downstream</strong>. Any dataset derived from these snapshots — a diff of what each reform changed, a training corpus, a citation graph — is only as citable as its link back to the official record.</p>
<p>Two independent signals produce the link, and both are always computed, because a weaker link is never what one actually wants.</p>
<p><strong>The title signal</strong> looks at every provision the gazette published on the snapshot’s own date and keeps those whose official title explicitly names the instrument. If exactly one candidate remains — after setting aside any provision an earlier snapshot of the same instrument already claimed — the date is linked. Each date therefore ends in one of four states: <code>linked</code> (one candidate, resolved), <code>ambiguous</code> (several plausible candidates, unresolved), <code>claimed</code> (the only candidate was already taken by another snapshot) or <code>none</code> (no provision that day names the instrument at all, which is what one expects for the years before the gazette’s metadata was catalogued in detail).</p>
<p><strong>The content signal</strong> attacks the <code>ambiguous</code> case, which the title alone cannot resolve. If several provisions published the same day all name the law, the one that actually caused <em>this</em> version is the one whose own text accounts for what changed between this snapshot and the previous one. So the pipeline takes the difference between consecutive snapshots, fetches each candidate provision’s own text from the gazette, and asks which candidate explains the difference. This is a comparatively expensive computation — it needs the full text of every candidate — and its intermediate results are not published: what is kept is the verdict, the identifier of the confirming provision and a score, not the diff itself.</p>
</section>
</section>
<section id="what-the-corpus-looks-like-today" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="what-the-corpus-looks-like-today"><span class="header-section-number">4</span> What the corpus looks like today</h2>
<p><a href="#tbl-overview" class="quarto-xref">Table&nbsp;1</a> gives the size of the collection as it stands. Every figure on this page is computed from the summary file described in the methodological note, not typed in by hand.</p>
<div class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>filas <span class="op">=</span> [</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Instruments in the Chamber of Deputies' catalogue"</span>, <span class="ss">f"</span><span class="sc">{</span>CATALOGO<span class="sc">:,}</span><span class="ss">"</span>, <span class="st">""</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"With a directory of snapshots"</span>, <span class="ss">f"</span><span class="sc">{</span>CON_DIRECTORIO<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>CON_DIRECTORIO <span class="op">/</span> CATALOGO <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of the catalogue"</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Markdown snapshots"</span>, <span class="ss">f"</span><span class="sc">{</span>SNAPSHOTS<span class="sc">:,}</span><span class="ss">"</span>, <span class="st">""</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Snapshots taken from the SCJN"</span>, <span class="ss">f"</span><span class="sc">{</span>resumen[<span class="st">'snapshots_by_source'</span>]<span class="sc">.</span>get(<span class="st">'scjn'</span>, <span class="dv">0</span>)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>resumen[<span class="st">'snapshots_by_source'</span>]<span class="sc">.</span>get(<span class="st">'scjn'</span>, <span class="dv">0</span>) <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Snapshots taken from the DOF (hand-built cases)"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>resumen[<span class="st">'snapshots_by_source'</span>]<span class="sc">.</span>get(<span class="st">'dof'</span>, <span class="dv">0</span>)<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>resumen[<span class="st">'snapshots_by_source'</span>]<span class="sc">.</span>get(<span class="st">'dof'</span>, <span class="dv">0</span>) <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Identified by the title signal alone"</span>, <span class="ss">f"</span><span class="sc">{</span>ENLAZADOS<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>ENLAZADOS <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Ambiguous dates resolved by the content signal"</span>, <span class="ss">f"</span><span class="sc">{</span>RESCATADOS<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>RESCATADOS <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Identified by either signal"</span>, <span class="ss">f"</span><span class="sc">{</span>IDENTIFICADOS<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>IDENTIFICADOS <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Confirmed by content diff (any state)"</span>, <span class="ss">f"</span><span class="sc">{</span>CONFIRMADOS<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>CONFIRMADOS <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Still unidentified"</span>, <span class="ss">f"</span><span class="sc">{</span>SNAPSHOTS <span class="op">-</span> IDENTIFICADOS<span class="sc">:,}</span><span class="ss">"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>     <span class="ss">f"</span><span class="sc">{</span>(SNAPSHOTS <span class="op">-</span> IDENTIFICADOS) <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>),</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Years covered"</span>, <span class="ss">f"</span><span class="sc">{</span>por_anio<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ch">\u2013</span><span class="sc">{</span>por_anio<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>, <span class="st">""</span>),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>Markdown(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"| | | |"</span>, <span class="st">"|---|---:|---|"</span>]</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> [<span class="ss">f"| </span><span class="sc">{</span>etiqueta<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>valor<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>nota<span class="sc">}</span><span class="ss"> |"</span> <span class="cf">for</span> etiqueta, valor, nota <span class="kw">in</span> filas]</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-overview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The federal laws corpus at a glance. Percentages of snapshots are over the 3,724 total.
</figcaption>
<div aria-describedby="tbl-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<table class="cell caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<td>Instruments in the Chamber of Deputies’ catalogue</td>
<td style="text-align: right;">316</td>
<td></td>
</tr>
<tr class="even">
<td>With a directory of snapshots</td>
<td style="text-align: right;">315</td>
<td>99.7% of the catalogue</td>
</tr>
<tr class="odd">
<td>Markdown snapshots</td>
<td style="text-align: right;">3,724</td>
<td></td>
</tr>
<tr class="even">
<td>Snapshots taken from the SCJN</td>
<td style="text-align: right;">3,722</td>
<td>99.9%</td>
</tr>
<tr class="odd">
<td>Snapshots taken from the DOF (hand-built cases)</td>
<td style="text-align: right;">2</td>
<td>0.05%</td>
</tr>
<tr class="even">
<td>Identified by the title signal alone</td>
<td style="text-align: right;">2,474</td>
<td>66.4%</td>
</tr>
<tr class="odd">
<td>Ambiguous dates resolved by the content signal</td>
<td style="text-align: right;">793</td>
<td>21.3%</td>
</tr>
<tr class="even">
<td>Identified by either signal</td>
<td style="text-align: right;">3,267</td>
<td>87.7%</td>
</tr>
<tr class="odd">
<td>Confirmed by content diff (any state)</td>
<td style="text-align: right;">2,634</td>
<td>70.7%</td>
</tr>
<tr class="even">
<td>Still unidentified</td>
<td style="text-align: right;">457</td>
<td>12.3%</td>
</tr>
<tr class="odd">
<td>Years covered</td>
<td style="text-align: right;">1889–2026</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="how-deep-the-history-goes" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="how-deep-the-history-goes"><span class="header-section-number">4.1</span> How deep the history goes</h3>
<p><a href="#fig-snapshots-per-year" class="quarto-xref">Figure&nbsp;2</a> plots the snapshots by the year of the reform that produced them, and it is the clearest available picture of when Mexico’s federal statute book actually changed. Three things stand out. The first half-century is thin: the Court’s database reaches back to 1917 and beyond — the oldest snapshot in the collection is the Commercial Code of 1889, older than the <em>Diario Oficial</em> coverage this project is built on — but reforms before the 1970s are recorded in ones and tens per year, partly because there were fewer and partly because the Court’s retrospective coverage of them is incomplete. Volume then rises through the last quarter of the century and settles, from the 1990s onward, into a regime of well over a hundred reforms a year across the collection. The final year is partial: it covers only the months already elapsed when the crawl ran.</p>
<div id="cell-fig-snapshots-per-year" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ultimo <span class="op">=</span> por_anio.index.<span class="bu">max</span>()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>colores <span class="op">=</span> [LIGHT_BLUE <span class="cf">if</span> anio <span class="op">==</span> ultimo <span class="cf">else</span> BLUE <span class="cf">for</span> anio <span class="kw">in</span> por_anio.index]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> go.Figure(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    go.Bar(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span>por_anio.index, y<span class="op">=</span>por_anio.values,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>colores, cornerradius<span class="op">=</span><span class="dv">2</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        hovertemplate<span class="op">=</span><span class="st">"%</span><span class="sc">{x}</span><span class="st">: %</span><span class="sc">{y:,}</span><span class="st"> snapshots&lt;extra&gt;&lt;/extra&gt;"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>style_plotly(fig, yaxis_title<span class="op">=</span><span class="st">"Snapshots"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>fig.update_layout(bargap<span class="op">=</span><span class="fl">0.2</span>, showlegend<span class="op">=</span><span class="va">False</span>, hovermode<span class="op">=</span><span class="st">"x unified"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>fig.add_annotation(x<span class="op">=</span>ultimo, y<span class="op">=</span>por_anio.iloc[<span class="op">-</span><span class="dv">1</span>], text<span class="op">=</span><span class="st">"partial year"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                   yshift<span class="op">=</span><span class="dv">14</span>, showarrow<span class="op">=</span><span class="va">False</span>, font<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>MUTED, size<span class="op">=</span><span class="dv">11</span>))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>fig.show(config<span class="op">=</span>PLOTLY_CONFIG)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-snapshots-per-year" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-snapshots-per-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.3.1.min.js" integrity="sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=" crossorigin="anonymous"></script>                <div id="51204df4-fff4-416d-a78f-0c95b4bed88d" class="plotly-graph-div" style="height:430px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("51204df4-fff4-416d-a78f-0c95b4bed88d")) {                    Plotly.newPlot(                        "51204df4-fff4-416d-a78f-0c95b4bed88d",                        [{"hovertemplate":"%{x}: %{y:,} snapshots\u003cextra\u003e\u003c\u002fextra\u003e","marker":{"color":["#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#2a78d6","#9ec5f4"],"cornerradius":2},"x":{"dtype":"i2","bdata":"YQd9B4EHgweGB4cHiAeJB4sHjAeNB44HjweQB5EHkgeTB5QHlQeWB5cHmAeZB5oHmwecB50HngefB6AHoQeiB6MHpAelB6cHqAepB6oHqwesB60HrgevB7AHsQeyB7MHtAe1B7YHtwe4B7kHuge7B7wHvQe+B78HwAfBB8IHwwfEB8UHxgfHB8gHyQfKB8sHzAfNB84HzwfQB9EH0gfTB9QH1QfWB9cH2AfZB9oH2wfcB90H3gffB+AH4QfiB+MH5AflB+YH5wfoB+kH6gc="},"y":{"dtype":"i2","bdata":"AQACAAEAAQABAAEABQABAAQABQAIABEACgAEAAQABQADAAoABAAKAAgACwAKAAsACAAGAAUABAAJAAMAAQAFAAIAAgABAAEABgACAAMACAABAAMACAAIAAMABAAIAAUACwAFAB4AFAAKAAYADAAHABMAFQAaABwADwAVAC0AEQARAA0AEQAVACgAOAAiACsANgAYACQAMgArABoANAA1ADgAUwBnAEgAQgBhAEMAdgCdAHEApwBqAHsAXQCyAFEAVQClAIoAiwCvALAAMwA="},"type":"bar"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"font":{"family":"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif","size":13,"color":"#52514e"},"margin":{"l":64,"r":24,"t":16,"b":40},"hoverlabel":{"font":{"color":"#52514e","size":12},"bgcolor":"white","bordercolor":"#e1e0d9"},"legend":{"font":{"size":12,"color":"#52514e"}},"paper_bgcolor":"white","plot_bgcolor":"white","height":430,"xaxis":{"tickfont":{"color":"#898781"},"title":{"text":""},"showgrid":false,"showline":false,"zeroline":false,"ticks":""},"yaxis":{"tickfont":{"color":"#898781"},"title":{"font":{"color":"#52514e","size":13},"text":"Snapshots"},"showgrid":true,"gridcolor":"#e1e0d9","gridwidth":1,"showline":false,"zeroline":false,"ticks":""},"bargap":0.2,"showlegend":false,"hovermode":"x unified","annotations":[{"font":{"color":"#898781","size":11},"showarrow":false,"text":"partial year","x":2026,"y":51,"yshift":14}]},                        {"displaylogo": false, "displayModeBar": "hover", "modeBarButtonsToRemove": ["lasso2d", "select2d", "autoScale2d"], "responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('51204df4-fff4-416d-a78f-0c95b4bed88d');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-snapshots-per-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Snapshots per year of publication. The last year, in a lighter shade, is partial — it ends when the crawl ran. Hover on a bar for the exact count.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="how-much-of-it-is-identified-and-what-the-second-signal-adds" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="how-much-of-it-is-identified-and-what-the-second-signal-adds"><span class="header-section-number">4.2</span> How much of it is identified, and what the second signal adds</h3>
<p><a href="#fig-link-status" class="quarto-xref">Figure&nbsp;3</a> is the figure to read before using this collection for anything. It breaks the 3,724 snapshots down by the state the title signal left them in, and splits each state by whether the content signal confirmed a provision. The stacked pair is the point: the <code>ambiguous</code> bar’s confirmed segment counts dates that the title signal could not resolve and the content signal could — the concrete return on the more expensive computation.</p>
<div id="cell-fig-link-status" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>orden <span class="op">=</span> [<span class="st">"linked"</span>, <span class="st">"ambiguous"</span>, <span class="st">"claimed"</span>, <span class="st">"none"</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>etiquetas <span class="op">=</span> {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"linked"</span>: <span class="st">"linked&lt;br/&gt;(one candidate)"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ambiguous"</span>: <span class="st">"ambiguous&lt;br/&gt;(several candidates)"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"claimed"</span>: <span class="st">"claimed&lt;br/&gt;(taken by another snapshot)"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"none"</span>: <span class="st">"none&lt;br/&gt;(no candidate that day)"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>confirmados <span class="op">=</span> [POR_CONFIRMACION.get(<span class="ss">f"</span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">|confirmed"</span>, <span class="dv">0</span>) <span class="cf">for</span> e <span class="kw">in</span> orden]</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>sin_confirmar <span class="op">=</span> [POR_CONFIRMACION.get(<span class="ss">f"</span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">|unconfirmed"</span>, <span class="dv">0</span>) <span class="cf">for</span> e <span class="kw">in</span> orden]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> go.Figure()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>fig.add_bar(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>[etiquetas[e] <span class="cf">for</span> e <span class="kw">in</span> orden], y<span class="op">=</span>confirmados, name<span class="op">=</span><span class="st">"confirmed by content diff"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>BLUE), hovertemplate<span class="op">=</span><span class="st">"%</span><span class="sc">{y:,}</span><span class="st"> snapshots&lt;extra&gt;confirmed&lt;/extra&gt;"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>fig.add_bar(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>[etiquetas[e] <span class="cf">for</span> e <span class="kw">in</span> orden], y<span class="op">=</span>sin_confirmar, name<span class="op">=</span><span class="st">"not confirmed"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span>LIGHT_BLUE), hovertemplate<span class="op">=</span><span class="st">"%</span><span class="sc">{y:,}</span><span class="st"> snapshots&lt;extra&gt;not confirmed&lt;/extra&gt;"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>style_plotly(fig, yaxis_title<span class="op">=</span><span class="st">"Snapshots"</span>, height<span class="op">=</span><span class="dv">440</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>fig.update_layout(barmode<span class="op">=</span><span class="st">"stack"</span>, bargap<span class="op">=</span><span class="fl">0.35</span>, hovermode<span class="op">=</span><span class="st">"x unified"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>                  legend<span class="op">=</span><span class="bu">dict</span>(orientation<span class="op">=</span><span class="st">"h"</span>, y<span class="op">=</span><span class="fl">1.12</span>, x<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>fig.update_yaxes(tickformat<span class="op">=</span><span class="st">","</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>fig.show(config<span class="op">=</span>PLOTLY_CONFIG)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-link-status" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-link-status-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.3.1.min.js" integrity="sha256-4rD3fugVb/nVJYUv5Ky3v+fYXoouHaBSP20WIJuEiWg=" crossorigin="anonymous"></script>                <div id="5af57183-ddfb-4cbc-bd65-0c2d352bae64" class="plotly-graph-div" style="height:440px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("5af57183-ddfb-4cbc-bd65-0c2d352bae64")) {                    Plotly.newPlot(                        "5af57183-ddfb-4cbc-bd65-0c2d352bae64",                        [{"hovertemplate":"%{y:,} snapshots\u003cextra\u003econfirmed\u003c\u002fextra\u003e","marker":{"color":"#2a78d6"},"name":"confirmed by content diff","x":["linked\u003cbr\u002f\u003e(one candidate)","ambiguous\u003cbr\u002f\u003e(several candidates)","claimed\u003cbr\u002f\u003e(taken by another snapshot)","none\u003cbr\u002f\u003e(no candidate that day)"],"y":[1839,793,2,0],"type":"bar"},{"hovertemplate":"%{y:,} snapshots\u003cextra\u003enot confirmed\u003c\u002fextra\u003e","marker":{"color":"#9ec5f4"},"name":"not confirmed","x":["linked\u003cbr\u002f\u003e(one candidate)","ambiguous\u003cbr\u002f\u003e(several candidates)","claimed\u003cbr\u002f\u003e(taken by another snapshot)","none\u003cbr\u002f\u003e(no candidate that day)"],"y":[635,373,14,68],"type":"bar"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"font":{"family":"system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif","size":13,"color":"#52514e"},"margin":{"l":64,"r":24,"t":16,"b":40},"hoverlabel":{"font":{"color":"#52514e","size":12},"bgcolor":"white","bordercolor":"#e1e0d9"},"legend":{"font":{"size":12,"color":"#52514e"},"orientation":"h","y":1.12,"x":0},"paper_bgcolor":"white","plot_bgcolor":"white","height":440,"xaxis":{"tickfont":{"color":"#898781"},"title":{"text":""},"showgrid":false,"showline":false,"zeroline":false,"ticks":""},"yaxis":{"tickfont":{"color":"#898781"},"title":{"font":{"color":"#52514e","size":13},"text":"Snapshots"},"showgrid":true,"gridcolor":"#e1e0d9","gridwidth":1,"showline":false,"zeroline":false,"ticks":"","tickformat":","},"barmode":"stack","bargap":0.35,"hovermode":"x unified"},                        {"displaylogo": false, "displayModeBar": "hover", "modeBarButtonsToRemove": ["lasso2d", "select2d", "autoScale2d"], "responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('5af57183-ddfb-4cbc-bd65-0c2d352bae64');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-link-status-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Snapshots by title-link state, split by whether the content diff confirmed a provision. The confirmed part of the <code>ambiguous</code> bar is what the second signal recovers on its own.
</figcaption>
</figure>
</div>
</div>
<div id="cell-link-summary" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>The two sentences of the paragraph below, computed rather than written</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>amb <span class="op">=</span> ESTADOS.get(<span class="st">"ambiguous"</span>, <span class="dv">0</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sin_ident <span class="op">=</span> {<span class="bu">int</span>(a): n <span class="cf">for</span> a, n <span class="kw">in</span> resumen[<span class="st">"unidentified_per_year"</span>].items()}</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>SIN_IDENT_TOTAL <span class="op">=</span> <span class="bu">sum</span>(sin_ident.values())</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>RECIENTES <span class="op">=</span> <span class="bu">sum</span>(n <span class="cf">for</span> a, n <span class="kw">in</span> sin_ident.items() <span class="cf">if</span> a <span class="op">&gt;=</span> <span class="dv">2000</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ANTIGUOS <span class="op">=</span> <span class="bu">sum</span>(n <span class="cf">for</span> a, n <span class="kw">in</span> sin_ident.items() <span class="cf">if</span> a <span class="op">&lt;</span> <span class="dv">1990</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>Markdown(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Read together, the two signals identify </span><span class="sc">{</span>IDENTIFICADOS<span class="sc">:,}</span><span class="ss"> of the "</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>SNAPSHOTS<span class="sc">:,}</span><span class="ss"> snapshots (</span><span class="sc">{</span>IDENTIFICADOS <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%): "</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>ENLAZADOS<span class="sc">:,}</span><span class="ss"> where a single same-day provision named the instrument, plus "</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>RESCATADOS<span class="sc">:,}</span><span class="ss"> of the </span><span class="sc">{</span>amb<span class="sc">:,}</span><span class="ss"> ambiguous dates where the content diff picked "</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"one candidate out of several. That leaves </span><span class="sc">{</span>SNAPSHOTS <span class="op">-</span> IDENTIFICADOS<span class="sc">:,}</span><span class="ss"> "</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"snapshots (</span><span class="sc">{</span>(SNAPSHOTS <span class="op">-</span> IDENTIFICADOS) <span class="op">/</span> SNAPSHOTS <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%) whose "</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"originating provision is still unknown, and — against intuition — these are not "</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"mostly the oldest ones: </span><span class="sc">{</span>RECIENTES<span class="sc">:,}</span><span class="ss"> of them (</span><span class="sc">{</span>RECIENTES <span class="op">/</span> <span class="bu">max</span>(SIN_IDENT_TOTAL, <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%) "</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"fall in 2000 or later, and only </span><span class="sc">{</span>ANTIGUOS<span class="sc">:,}</span><span class="ss"> before 1990. The reason is that the "</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"unresolved cases are dominated by days on which the gazette published several "</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"provisions all naming the same law — a modern habit, since a single reform "</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"package now often arrives as several decrees — and the content diff was not "</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"decisive between them. The genuinely old failures are of the other kind: "</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>ESTADOS<span class="sc">.</span>get(<span class="st">'none'</span>, <span class="dv">0</span>)<span class="sc">:,}</span><span class="ss"> snapshots have no same-day candidate at all. "</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Note also that confirmation is not the same as agreement: of the "</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>ENLAZADOS<span class="sc">:,}</span><span class="ss"> title-linked snapshots, "</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>POR_CONFIRMACION<span class="sc">.</span>get(<span class="st">'linked|confirmed'</span>, <span class="dv">0</span>)<span class="sc">:,}</span><span class="ss"> were independently confirmed by "</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"content, and the rest simply had no digital candidate text to check against."</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="link-summary" class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<p>Read together, the two signals identify 3,267 of the 3,724 snapshots (87.7%): 2,474 where a single same-day provision named the instrument, plus 793 of the 1,166 ambiguous dates where the content diff picked one candidate out of several. That leaves 457 snapshots (12.3%) whose originating provision is still unknown, and — against intuition — these are not mostly the oldest ones: 268 of them (59%) fall in 2000 or later, and only 135 before 1990. The reason is that the unresolved cases are dominated by days on which the gazette published several provisions all naming the same law — a modern habit, since a single reform package now often arrives as several decrees — and the content diff was not decisive between them. The genuinely old failures are of the other kind: 68 snapshots have no same-day candidate at all. Note also that confirmation is not the same as agreement: of the 2,474 title-linked snapshots, 1,839 were independently confirmed by content, and the rest simply had no digital candidate text to check against.</p>
</div>
</div>
</section>
<section id="instrument-by-instrument" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="instrument-by-instrument"><span class="header-section-number">4.3</span> Instrument by instrument</h3>
<p><a href="#tbl-instruments" class="quarto-xref">Table&nbsp;2</a> lists the twenty-five instruments with the most snapshots, which is a reasonable proxy for the most heavily reformed pieces of Mexican federal law. It is the same information the collection’s <code>MANIFEST.md</code> carries — the file a human reads in full before publishing — reordered by size rather than by confidence.</p>
<p>The table has four columns worth explaining. <strong>Snapshots</strong> is how many dated versions of that instrument the collection holds, and therefore how many times its text changed within the Court’s coverage; the Constitution leads by a wide margin, which is itself a substantive fact about Mexican constitutionalism. <strong>Span</strong> gives the first and last year covered, which is where the Court’s retrospective reach shows: an instrument may be older than its span suggests. <strong>Title-linked</strong> is the share of that instrument’s snapshots that a single same-day provision naming the law resolved on its own — the column to consult before relying on a particular law’s history, since coverage is far from uniform. <strong>Confirmed</strong> counts the snapshots whose provision was corroborated by comparing texts, the strongest evidence the pipeline produces; it is reported as a count rather than a share because it can exceed the title-linked count, precisely when it resolves dates the title left ambiguous. A low title-linked figure never means the text is wrong — it means the collection cannot yet say, from that signal alone, which publication produced that version.</p>
<div class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>TOPN <span class="op">=</span> <span class="dv">25</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>tabla <span class="op">=</span> instrumentos.head(TOPN)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>lineas <span class="op">=</span> [</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| Instrument | Slug | Snapshots | Span | Title-linked | Confirmed |"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"|---|---|---:|---|---:|---:|"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> fila <span class="kw">in</span> tabla.itertuples():</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    span <span class="op">=</span> (</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>fila<span class="sc">.</span>first_year<span class="sc">}</span><span class="ch">\u2013</span><span class="sc">{</span>fila<span class="sc">.</span>last_year<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> fila.first_year <span class="kw">and</span> fila.last_year <span class="kw">and</span> fila.first_year <span class="op">!=</span> fila.last_year</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span> (<span class="bu">str</span>(fila.first_year) <span class="cf">if</span> fila.first_year <span class="cf">else</span> <span class="st">"</span><span class="ch">\u2014</span><span class="st">"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    nombre <span class="op">=</span> fila.nombre <span class="cf">if</span> <span class="bu">len</span>(fila.nombre) <span class="op">&lt;=</span> <span class="dv">70</span> <span class="cf">else</span> fila.nombre[:<span class="dv">67</span>] <span class="op">+</span> <span class="st">"</span><span class="ch">\u2026</span><span class="st">"</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    lineas.append(</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"| </span><span class="sc">{</span>nombre<span class="sc">}</span><span class="ss"> | `</span><span class="sc">{</span>fila<span class="sc">.</span>slug<span class="sc">}</span><span class="ss">` | </span><span class="sc">{</span>fila<span class="sc">.</span>snapshots<span class="sc">:,}</span><span class="ss"> | </span><span class="sc">{</span>span<span class="sc">}</span><span class="ss"> | "</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>fila<span class="sc">.</span>linked <span class="op">/</span> fila<span class="sc">.</span>snapshots <span class="op">*</span> <span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">% | </span><span class="sc">{</span>fila<span class="sc">.</span>diff_confirmed<span class="sc">:,}</span><span class="ss"> |"</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>Markdown(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(lineas))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-instruments" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-instruments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The twenty-five instruments with the most snapshots. <code>Title-linked</code> is the share the title signal resolved on its own; <code>Confirmed</code>, the number of snapshots corroborated by comparing the candidate provision’s own text.
</figcaption>
<div aria-describedby="tbl-instruments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Instrument</th>
<th>Slug</th>
<th style="text-align: right;">Snapshots</th>
<th>Span</th>
<th style="text-align: right;">Title-linked</th>
<th style="text-align: right;">Confirmed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CONSTITUCIÓN Política de los Estados Unidos Mexicanos</td>
<td><code>cpeum</code></td>
<td style="text-align: right;">300</td>
<td>1917–2026</td>
<td style="text-align: right;">59%</td>
<td style="text-align: right;">165</td>
</tr>
<tr class="even">
<td>CÓDIGO Penal Federal</td>
<td><code>cpf</code></td>
<td style="text-align: right;">166</td>
<td>1931–2026</td>
<td style="text-align: right;">72%</td>
<td style="text-align: right;">118</td>
</tr>
<tr class="odd">
<td>LEY General de Salud</td>
<td><code>lgs</code></td>
<td style="text-align: right;">146</td>
<td>1984–2026</td>
<td style="text-align: right;">57%</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="even">
<td>CÓDIGO Fiscal de la Federación</td>
<td><code>cff</code></td>
<td style="text-align: right;">118</td>
<td>1981–2026</td>
<td style="text-align: right;">42%</td>
<td style="text-align: right;">61</td>
</tr>
<tr class="odd">
<td>LEY Federal de Derechos</td>
<td><code>lfd</code></td>
<td style="text-align: right;">92</td>
<td>1981–2025</td>
<td style="text-align: right;">48%</td>
<td style="text-align: right;">56</td>
</tr>
<tr class="even">
<td>LEY Orgánica de la Administración Pública Federal</td>
<td><code>loapf</code></td>
<td style="text-align: right;">82</td>
<td>1976–2026</td>
<td style="text-align: right;">85%</td>
<td style="text-align: right;">71</td>
</tr>
<tr class="odd">
<td>CÓDIGO de Comercio</td>
<td><code>ccom</code></td>
<td style="text-align: right;">74</td>
<td>1889–2026</td>
<td style="text-align: right;">74%</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td>CÓDIGO Civil Federal</td>
<td><code>ccf</code></td>
<td style="text-align: right;">62</td>
<td>1928–2025</td>
<td style="text-align: right;">68%</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="odd">
<td>LEY del Impuesto Especial sobre Producción y Servicios</td>
<td><code>lieps</code></td>
<td style="text-align: right;">60</td>
<td>1980–2025</td>
<td style="text-align: right;">45%</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>LEY Federal de Protección al Consumidor</td>
<td><code>lfpc</code></td>
<td style="text-align: right;">57</td>
<td>1992–2025</td>
<td style="text-align: right;">98%</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="odd">
<td>LEY Federal del Trabajo</td>
<td><code>lft</code></td>
<td style="text-align: right;">55</td>
<td>1970–2026</td>
<td style="text-align: right;">78%</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="even">
<td>LEY del Impuesto al Valor Agregado</td>
<td><code>liva</code></td>
<td style="text-align: right;">54</td>
<td>1978–2021</td>
<td style="text-align: right;">46%</td>
<td style="text-align: right;">42</td>
</tr>
<tr class="odd">
<td>LEY de Instituciones de Crédito</td>
<td><code>lic</code></td>
<td style="text-align: right;">53</td>
<td>1990–2025</td>
<td style="text-align: right;">75%</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="even">
<td>LEY General del Equilibrio Ecológico y la Protección al Ambiente</td>
<td><code>lgeepa</code></td>
<td style="text-align: right;">53</td>
<td>1988–2026</td>
<td style="text-align: right;">74%</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="odd">
<td>LEY de Vías Generales de Comunicación</td>
<td><code>lvgc</code></td>
<td style="text-align: right;">51</td>
<td>1940–2025</td>
<td style="text-align: right;">67%</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td>LEY Orgánica del Congreso General de los Estados Unidos Mexicanos</td>
<td><code>locg</code></td>
<td style="text-align: right;">47</td>
<td>1999–2025</td>
<td style="text-align: right;">87%</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td>LEY del Seguro Social</td>
<td><code>lss</code></td>
<td style="text-align: right;">44</td>
<td>1995–2026</td>
<td style="text-align: right;">41%</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td>LEY Monetaria de los Estados Unidos Mexicanos</td>
<td><code>lmeum</code></td>
<td style="text-align: right;">44</td>
<td>1931–2026</td>
<td style="text-align: right;">59%</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td>LEY Aduanera</td>
<td><code>ladua</code></td>
<td style="text-align: right;">40</td>
<td>1995–2025</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td>LEY de Coordinación Fiscal</td>
<td><code>lcf</code></td>
<td style="text-align: right;">40</td>
<td>1978–2024</td>
<td style="text-align: right;">48%</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="odd">
<td>REGLAMENTO de la Cámara de Diputados</td>
<td><code>reg-diputados</code></td>
<td style="text-align: right;">40</td>
<td>2010–2025</td>
<td style="text-align: right;">70%</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td>LEY Federal del Impuesto sobre Automóviles Nuevos</td>
<td><code>lfisan</code></td>
<td style="text-align: right;">34</td>
<td>1996–2025</td>
<td style="text-align: right;">41%</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td>LEY del Instituto del Fondo Nacional de la Vivienda para los Trabaj…</td>
<td><code>lifnvt</code></td>
<td style="text-align: right;">31</td>
<td>1972–2025</td>
<td style="text-align: right;">77%</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td>LEY Federal de los Trabajadores al Servicio del Estado, Reglamentar…</td>
<td><code>lftse</code></td>
<td style="text-align: right;">31</td>
<td>1963–2026</td>
<td style="text-align: right;">61%</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd">
<td>REGLAMENTO del Senado de la República</td>
<td><code>reg-senado</code></td>
<td style="text-align: right;">31</td>
<td>2010–2024</td>
<td style="text-align: right;">52%</td>
<td style="text-align: right;">19</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-tail-summary" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>The distribution behind the table’s long tail</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>un_solo <span class="op">=</span> <span class="bu">int</span>((instrumentos[<span class="st">"snapshots"</span>] <span class="op">==</span> <span class="dv">1</span>).<span class="bu">sum</span>())</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>todo_enlazado <span class="op">=</span> <span class="bu">int</span>((instrumentos[<span class="st">"snapshots"</span>] <span class="op">==</span> instrumentos[<span class="st">"linked"</span>]).<span class="bu">sum</span>())</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sin_enlace <span class="op">=</span> <span class="bu">int</span>((instrumentos[<span class="st">"linked"</span>] <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mediana <span class="op">=</span> <span class="bu">int</span>(instrumentos[<span class="st">"snapshots"</span>].median())</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>Markdown(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Beyond the top of the table the distribution is very uneven: the median "</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"instrument has </span><span class="sc">{</span>mediana<span class="sc">}</span><span class="ss"> snapshots, </span><span class="sc">{</span>un_solo<span class="sc">}</span><span class="ss"> of the </span><span class="sc">{</span>CON_DIRECTORIO<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"instruments have exactly one — laws never reformed since they were enacted, "</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"or enacted so recently that the Court's table holds a single row — "</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>todo_enlazado<span class="sc">}</span><span class="ss"> have every one of their snapshots resolved by the title signal "</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"alone, and </span><span class="sc">{</span>sin_enlace<span class="sc">}</span><span class="ss"> have none resolved by it at all."</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tail-summary" class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
<p>Beyond the top of the table the distribution is very uneven: the median instrument has 5 snapshots, 66 of the 315 instruments have exactly one — laws never reformed since they were enacted, or enacted so recently that the Court’s table holds a single row — 119 have every one of their snapshots resolved by the title signal alone, and 9 have none resolved by it at all.</p>
</div>
</div>
</section>
</section>
<section id="cases-the-pipeline-could-not-handle-on-its-own" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="cases-the-pipeline-could-not-handle-on-its-own"><span class="header-section-number">5</span> Cases the pipeline could not handle on its own</h2>
<p>The crawl runs unattended for the great majority of the catalogue: 313 of the 316 entries have a directory built entirely by the general pipeline. Four entries did not come for free — one of them (<code>lisipl</code>) only after the pipeline itself was changed, two (<code>lfca</code>, <code>lfiiedb</code>) by scripts written for that single law, and one (<code>oga</code>) not at all. Those four are the interesting part, and they are documented here rather than in a footnote, because this is where a reader can judge how the collection was actually built. Each one below is a <em>pattern</em>, not a curiosity, and each is recorded with the state it was left in.</p>
<section id="lisipl-a-catalogue-name-no-search-can-match" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="lisipl-a-catalogue-name-no-search-can-match"><span class="header-section-number">5.1</span> <code>lisipl</code> — a catalogue name no search can match</h3>
<p>The Chamber lists one tax law under a name that carries a 255-character parenthetical alternate title. Searched verbatim, it matches nothing at all in the Court’s database: full-text search does not degrade gracefully when the query is a paragraph. Rather than making the crawler guess how to shorten a name — a heuristic that would silently mis-identify other instruments — the catalogue entry accepts an optional hand-written override, <strong><code>nombre_scjn</code></strong>, naming the exact string to search for. Its whole entry in <code>catalogo.json</code> is short enough to show in full:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"nombre"</span><span class="fu">:</span> <span class="st">"IMPUESTO sobre Servicios Expresamente Declarados de Interés Público por Ley, en los que Intervengan Empresas Concesionarias de Bienes del Dominio Directo de la Nación (LEY que establece, reforma y adiciona las disposiciones relativas a diversos impuestos)"</span><span class="fu">,</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"abrev"</span><span class="fu">:</span> <span class="st">"lisipl"</span><span class="fu">,</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"nombre_scjn"</span><span class="fu">:</span> <span class="st">"LEY DEL IMPUESTO SOBRE SERVICIOS EXPRESAMENTE DECLARADOS DE INTERES PUBLICO POR LEY, EN LOS QUE INTERVENGAN EMPRESAS CONCESIONARIAS DE BIENES DEL DOMINIO DIRECTO DE LA NACION"</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The two strings name the same law: what <code>nombre_scjn</code> drops is the parenthetical <code>(LEY que establece, reforma y adiciona las disposiciones relativas a diversos impuestos)</code> that the Chamber appends, and what it keeps is the law’s own title as the Court spells it. <code>nombre_a_buscar</code> prefers it over <code>nombre</code> when it is present, so it is <code>nombre_scjn</code> — not the Chamber’s name — that ends up in the snapshot’s <code>nombre_buscado</code> header. This is the one-source’s-name-against-the-other’s pairing of the header block, with the Chamber’s half replaced by hand precisely because it was unusable as a query; the low similarity score that results is correct, and is why <code>lisipl</code> is one of the three instruments the confidence check flags. A catalogue refresh carries the override forward rather than overwriting it (<code>merge_catalog_overrides</code>), so re-seeding from the Chamber never silently loses it. One entry uses it today. The general rule this encodes is worth stating: where an automated guess would be unverifiable, the pipeline prefers an explicit, versioned, human decision.</p>
</section>
<section id="lfca-a-new-law-that-repeals-an-indexed-one" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="lfca-a-new-law-that-repeals-an-indexed-one"><span class="header-section-number">5.2</span> <code>lfca</code> — a new law that repeals an indexed one</h3>
<p>The Federal Cinema and Audiovisual Law was published in May 2026 and repealed the 1992 Federal Cinematography Law. The Court has no entry for the new law; what it does have is the repealed one, with its entire reform history. So the corpus was built in two halves: the <strong>history</strong>, crawled under the repealed law’s name, and the <strong>current text</strong>, taken directly from the <em>Diario Oficial</em> (provision <code>codNota</code> 5788357, 22 May 2026) and converted with <code>nota2md</code>. One detail is worth recording: the Court’s own last row for the repealed law is dated the day the new law appeared and announces its enactment, but its body is still the old 1992 text — so that row was discarded, and 22 May 2026 has exactly one snapshot, the gazette’s.</p>
<p>This is where the header’s <code>fuente</code> field earns its keep. Nine of this instrument’s ten snapshots read <code>fuente: scjn</code> and one reads <code>fuente: dof</code>, so the two halves are distinguishable without opening a single file, and the same field appears per entry in the instrument’s <code>indice.json</code>. Consumers must treat that index field as <strong>optional</strong>: the normal pipeline never writes it, and its absence means <code>scjn</code>.</p>
</section>
<section id="lfiiedb-the-same-pattern-without-the-history" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="lfiiedb-the-same-pattern-without-the-history"><span class="header-section-number">5.3</span> <code>lfiiedb</code> — the same pattern, without the history</h3>
<p>The Law for Promoting Investment in Strategic Infrastructure for Development with Well-being was published in April 2026 and has never been reformed. The Court does not index it, and there is no repealed predecessor to borrow a history from. Its corpus is therefore a single file taken from the gazette (<code>codNota</code> 5784517), with a link that is known by construction rather than inferred. It is the minimal case of the previous pattern.</p>
</section>
<section id="oga-outside-the-gazettes-reach" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="oga-outside-the-gazettes-reach"><span class="header-section-number">5.4</span> <code>oga</code> — outside the gazette’s reach</h3>
<p>The General Ordinance of the Navy is the one catalogue entry with no directory at all. It was published between 1 and 8 January <strong>1912</strong>, before the <em>Diario Oficial</em> as this project covers it (1917) begins, and the Court does not index it either. The two provisions its Chamber history lists are not the ordinance but later instruments that reformed it. The gap is real, it is understood, and it is deliberately left open — the alternative would be to fabricate coverage the sources do not support.</p>
</section>
<section id="what-these-cases-have-in-common" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="what-these-cases-have-in-common"><span class="header-section-number">5.5</span> What these cases have in common</h3>
<div id="cell-casos-summary" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>The flagged-confidence counts cited below</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>motivos <span class="op">=</span> {}</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datos <span class="kw">in</span> resumen[<span class="st">"confidence"</span>].values():</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    motivos[datos[<span class="st">"motivo"</span>]] <span class="op">=</span> motivos.get(datos[<span class="st">"motivo"</span>], <span class="dv">0</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>Markdown(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"A side effect worth knowing about: the hand-built cases are exactly the "</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"ones the automated confidence check flags. Of the </span><span class="sc">{</span>CON_DIRECTORIO<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"instruments with a directory, </span><span class="sc">{</span>motivos<span class="sc">.</span>get(<span class="st">'confiable'</span>, <span class="dv">0</span>)<span class="sc">}</span><span class="ss"> are classified "</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"`confiable`, </span><span class="sc">{</span>motivos<span class="sc">.</span>get(<span class="st">'sospechoso'</span>, <span class="dv">0</span>)<span class="sc">}</span><span class="ss"> `sospechoso` and "</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>motivos<span class="sc">.</span>get(<span class="st">'bajo_umbral'</span>, <span class="dv">0</span>)<span class="sc">}</span><span class="ss"> below the similarity threshold. The flagged "</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"ones are `lfca` and `lfiiedb` — whose stored title is the gazette's decree "</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"wording rather than the catalogue's law name, so a low similarity score is "</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"correct and expected — and `lisipl`, whose catalogue name carries a "</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"250-character alternate title that the Court's search never matches and which "</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"is therefore searched under a hand-written override. Three flags, three "</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"explanations, no unexplained ones: that is the state the collection is in, and "</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"the check is worth keeping precisely because it is loud."</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="casos-summary" class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<p>A side effect worth knowing about: the hand-built cases are exactly the ones the automated confidence check flags. Of the 315 instruments with a directory, 312 are classified <code>confiable</code>, 2 <code>sospechoso</code> and 1 below the similarity threshold. The flagged ones are <code>lfca</code> and <code>lfiiedb</code> — whose stored title is the gazette’s decree wording rather than the catalogue’s law name, so a low similarity score is correct and expected — and <code>lisipl</code>, whose catalogue name carries a 250-character alternate title that the Court’s search never matches and which is therefore searched under a hand-written override. Three flags, three explanations, no unexplained ones: that is the state the collection is in, and the check is worth keeping precisely because it is loud.</p>
</div>
</div>
<p>Two of the three resolved cases are the same situation — a recent law the Court has not indexed yet, closed by taking the text from the gazette — and both are <strong>reversible</strong>. When the Court indexes the law, the hand-built directory should be reviewed and replaced by an ordinary crawl, and the single-purpose script that built it retired. The refresh logic already cooperates: an instrument with no snapshots is retried on every run, so the only manual act left is deleting the hand-built directory once the normal path works.</p>
<p><a href="#fig-decision" class="quarto-xref">Figure&nbsp;4</a> states the pattern as a rule, so the next law of this shape is handled by consulting a diagram instead of improvising.</p>
<div id="fig-decision" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-decision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    Q{SCJN indexes&lt;br/&gt;the law?} --&gt;|yes| N[normal crawl]
    Q --&gt;|no| H{Does it abrogate&lt;br/&gt;an indexed law?}
    H --&gt;|yes| B["history: crawl the abrogated law&lt;br/&gt;current text: DOF codNota"]
    H --&gt;|no| O{Published&lt;br/&gt;after 1917?}
    O --&gt;|yes| S[single DOF snapshot]
    O --&gt;|no| X[out of scope]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-decision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The rule for an instrument the Court’s database does not have. <code>lfca</code> takes the middle branch, <code>lfiiedb</code> the single-snapshot branch, <code>oga</code> the last one.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="how-this-collection-is-published" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="how-this-collection-is-published"><span class="header-section-number">6</span> How this collection is published</h2>
<p>The corpus is published, since August 2026, as the <a href="https://github.com/INGEOTEC/LegalIA/releases/tag/scjn-leyes"><code>scjn-leyes</code></a> GitHub release.</p>
<p><strong>One reproducible tarball per instrument.</strong> The packaging step writes one <code>&lt;slug&gt;.tgz</code> for each instrument rather than a single archive for the whole collection, because a consumer almost always wants one law, and a later run then has to re-upload only the laws that changed. Every member is prefixed with the instrument’s slug, so a tarball unpacks anywhere without stepping on anything:</p>
<pre><code>&lt;slug&gt;/&lt;date&gt;.md            the snapshots, each with its provenance header
&lt;slug&gt;/indice.json          the codNota link and the signals behind it
&lt;slug&gt;/notas/nota-&lt;cod&gt;.md  the DOF text of every candidate considered</code></pre>
<p>The gazette notes travel <em>with</em> the snapshots on purpose: they are the text each link was decided against, so shipping both makes a link auditable without going back to the network. Two small text assets accompany the tarballs — a <code>MANIFEST.md</code> ranking every instrument by confidence, and a <code>SHA256SUMS.txt</code>. Each tarball is <strong>byte-reproducible</strong>: gzip is stamped with a zero timestamp, members are added in sorted order, and their times, modes and ownership are fixed. Identical data therefore yields an identical file, which is what makes it possible to tell an unchanged instrument from a changed one by comparing bytes rather than guessing — the same property the <code>historial-legislativo</code> release relies on.</p>
<p><strong>Published as GitHub release assets</strong>, like the DOF notes archive and the reform-history collection, and for the same reason: data is never committed to this repository.</p>
<p><strong>Published by hand, always, by design.</strong> This is the one operational difference between this collection and the others, and it is a statement about the source rather than a gap in automation. The notes archive is rebuilt and republished monthly by a workflow with no human in the loop, because its source is the gazette’s own service and an error there is the gazette’s error. The Court’s search, by contrast, can return a completely wrong document, and a wrong document would enter the corpus looking exactly like a right one — so the packaging script never invokes <code>gh</code>, no workflow may publish this collection, and <code>MANIFEST.md</code> is read in full before anything is uploaded. Separating packaging from publishing keeps the human judgement where the risk actually is.</p>
<p><strong>Reading it back.</strong> Because one instrument is one asset, downloading a law needs no library at all:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gh</span> release download scjn-leyes <span class="at">--repo</span> INGEOTEC/LegalIA <span class="at">--pattern</span> <span class="st">'lft.tgz'</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tar</span> xzf lft.tgz          <span class="co"># -&gt; lft/&lt;date&gt;.md, lft/indice.json, lft/notas/</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A download function in the same family as the ones already serving the other collections — so that reading the corpus from Python is a call rather than an exercise — is still to be written.</p>
<p><strong>Licensing and attribution are still open.</strong> The snapshots are the Supreme Court’s editorial work over public legal texts, and the terms on which they may be redistributed have yet to be settled; this page is where the answer will be recorded. Nothing about the pipeline depends on that answer — the scripts reconstruct the corpus from the sources on any machine — but what the release carries does.</p>
</section>


<div id="quarto-appendix" class="default"><section id="methodological-note" class="level2 unnumbered appendix"><h2 class="anchored quarto-appendix-heading">Methodological note</h2><div class="quarto-appendix-contents">

<p>The material described here is built by four scripts in <a href="https://github.com/INGEOTEC/LegalIA/tree/master/scripts"><code>scripts/</code></a> — <code>extract_scjn_titles.py</code>, <code>fetch_scjn_legislacion.py</code>, <code>enlaza_scjn_legislacion.py</code> and <code>empaqueta_scjn_leyes.py</code> — plus two single-law scripts for the hand-built cases, <code>construye_lfca.py</code> and <code>fetch_lfiiedb_dof.py</code>. The SCJN-specific logic they share lives in <code>nota2md.scjn</code>; the <em>Diario Oficial</em> side comes from <a href="https://pypi.org/project/dofjson/"><code>dofjson</code></a> and <a href="https://pypi.org/project/nota2md/"><code>nota2md</code></a>, both on PyPI.</p>
<p>The corpus is published as release assets and is never committed to git, so this page does not read it directly — downloading 315 tarballs to draw two figures would be a poor trade. It reads <a href="https://github.com/INGEOTEC/LegalIA/blob/master/website/pages/data/scjn-leyes-summary.json"><code>data/scjn-leyes-summary.json</code></a>, an aggregate summary produced by <code>scripts/resume_scjn_leyes.py</code> from the crawl that the August 2026 release was packaged from: headline counts, snapshots per year, the title-link states crossed with content confirmation, and one row per instrument. That script reuses the very function <code>empaqueta_scjn_leyes.py</code> uses to build <code>MANIFEST.md</code>, so the numbers on this page, the numbers a human reads before publishing, and the manifest shipped with the release cannot drift apart. Regenerating the summary after a fresh crawl is one command:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">./scripts/resume_scjn_leyes.py</span> <span class="at">--outdir</span> scripts/scjn <span class="dt">\</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--destino</span> website/pages/data/scjn-leyes-summary.json</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This page was written by the LegalIA team together with Claude, Anthropic’s coding assistant, through <a href="https://claude.com/claude-code">Claude Code</a>: the assistant implemented the summary step, produced the figures and drafted the accompanying text. The authors verified the numbers against the corpus on disk and are responsible for the interpretations advanced here.</p>


</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ingeotec\.github\.io\/LegalIA\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>LegalIA · <a href="https://github.com/INGEOTEC">INGEOTEC</a> · Code under the Apache 2.0 license</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>