#!/usr/bin/env python3
"""Reduce the crawled `leyes` corpus to the small aggregate summary the
website's *Federal Laws* page reads (issue #147).

The corpus itself (`scripts/scjn/leyes/`, 315 instrument directories and
3,724 Markdown snapshots) is never committed to git, and while it is now
published (issue #128) it is published as one tarball per law — 380 MB in
all — so the page still cannot compute its figures live the way
`dataset.ipynb` does against the GitHub API. What it reads instead is the
JSON this script writes: counts, per-year totals and one row per instrument
— a few tens of kilobytes, versioned with the page, regenerated by re-running
this script after a crawl.

    ./scripts/resume_scjn_leyes.py --outdir scripts/scjn \\
        --destino website/pages/data/scjn-leyes-summary.json

Nothing here re-crawls the SCJN, re-links a codNota or touches the corpus: it
only reads each instrument's own snapshot headers and `indice.json`, exactly
as `empaqueta_scjn_leyes.py` does for `MANIFEST.md` — whose per-instrument
summary (`resume_coleccion`) is reused directly instead of recomputed, so the
page and the manifest can never disagree about an instrument's confidence
classification or link percentage.
"""

import argparse
import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path

_RAIZ = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_RAIZ / "packages" / "nota2md"))
sys.path.insert(0, str(_RAIZ / "packages" / "scjn"))

from scjn.catalog import slug_instrumento  # noqa: E402
from scjn.header import lee_cabecera, versiones_de_directorio  # noqa: E402

COLECCION = "leyes"

# `empaqueta_scjn_leyes.py` is a script, not a module on the import path, so
# load it by file. Reusing its `resume_coleccion` is the point: the manifest a
# human reads before publishing and the table the page shows are then two
# renderings of one computation.
_spec = importlib.util.spec_from_file_location(
    "empaqueta_scjn_leyes", Path(__file__).resolve().parent / "empaqueta_scjn_leyes.py"
)
_empaqueta = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_empaqueta)


def _fuentes_por_instrumento(directorio: Path) -> Counter:
    """How many of an instrument's snapshots came from each source, read from
    the `fuente:` line of each file's own provenance header. The header is
    authoritative here rather than `indice.json`'s optional `fuente` field:
    `fetch_lfiiedb_dof.py` writes the header but not the index field, and
    `enlaza_scjn_legislacion.py` never writes the field at all (absent means
    `scjn`)."""
    fuentes = Counter()
    for version in versiones_de_directorio(directorio):
        fuentes[lee_cabecera(version.archivo).get("fuente", "scjn")] += 1
    return fuentes


def resume(outdir: Path) -> dict:
    """Every number the page shows, in one JSON-serializable dict."""
    base = outdir / COLECCION
    # Issue #210: `catalogo.json` is gone, so the same corpus-directory
    # enumeration `empaqueta_scjn_leyes.py` already needed is reused here
    # instead of a second read of a file that no longer exists.
    catalogo = _empaqueta._load_catalog(outdir)
    resumenes, nunca_rastreados = _empaqueta.resume_coleccion(outdir)

    por_anio = Counter()
    # Snapshots neither signal could tie to a codNota, by year: the page reads
    # this to say *where* the unidentified ones sit instead of assuming they are
    # the oldest — they are not.
    sin_identificar_por_anio = Counter()
    estados = Counter()
    fuentes_totales = Counter()
    # (title_link_status, content diff confirmed?) -> snapshots. This is what
    # shows how much the second signal adds over the first: an `ambiguous`
    # snapshot the diff confirms is a date the title alone could not resolve.
    estado_por_confirmacion = Counter()
    instrumentos = []
    snapshots_totales = 0
    enlazados_titulo = 0
    confirmados_contenido = 0

    for entrada in catalogo:
        slug = slug_instrumento(entrada)
        directorio = base / slug
        if not directorio.is_dir():
            continue
        fuentes = _fuentes_por_instrumento(directorio)
        fuentes_totales.update(fuentes)

        indice_path = directorio / "indice.json"
        indice = (
            json.loads(indice_path.read_text(encoding="utf-8"))
            if indice_path.is_file()
            else []
        )
        enlazados = 0
        confirmados = 0
        for e in indice:
            anio = int(e["fecha_publicacion"].split("-")[-1])
            por_anio[anio] += 1
            estado = e.get("title_link_status")
            confirmado = e.get("content_diff_confirmed_codNota") is not None
            estados[estado] += 1
            estado_por_confirmacion[f"{estado}|{'confirmed' if confirmado else 'unconfirmed'}"] += 1
            enlazados += e.get("codNota") is not None
            confirmados += confirmado
            if e.get("codNota") is None and not confirmado:
                sin_identificar_por_anio[anio] += 1

        snapshots_totales += sum(fuentes.values())
        enlazados_titulo += enlazados
        confirmados_contenido += confirmados
        instrumentos.append(
            {
                "slug": slug,
                "nombre": entrada["nombre"],
                "snapshots": sum(fuentes.values()),
                "linked": enlazados,
                "diff_confirmed": confirmados,
                "fuentes": dict(sorted(fuentes.items())),
                "first_year": min((int(e["fecha_publicacion"].split("-")[-1]) for e in indice), default=None),
                "last_year": max((int(e["fecha_publicacion"].split("-")[-1]) for e in indice), default=None),
            }
        )

    return {
        "collection": COLECCION,
        "catalogue_entries": len(catalogo),
        "instruments_with_directory": len(instrumentos),
        "never_crawled": nunca_rastreados,
        "snapshots": snapshots_totales,
        "linked_by_title": enlazados_titulo,
        "content_diff_confirmed": confirmados_contenido,
        "title_link_status": dict(estados),
        "title_link_status_by_confirmation": dict(estado_por_confirmacion),
        "snapshots_by_source": dict(sorted(fuentes_totales.items())),
        "snapshots_per_year": {str(a): n for a, n in sorted(por_anio.items())},
        "unidentified_per_year": {
            str(a): n for a, n in sorted(sin_identificar_por_anio.items())
        },
        "instruments": sorted(instrumentos, key=lambda r: -r["snapshots"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", type=Path, default=Path("scripts/scjn"),
                        help="directory holding <outdir>/leyes/ (default: scripts/scjn)")
    parser.add_argument("--destino", type=Path,
                        default=Path("website/pages/data/scjn-leyes-summary.json"),
                        help="JSON file to write")
    args = parser.parse_args()

    resumen = resume(args.outdir)
    args.destino.parent.mkdir(parents=True, exist_ok=True)
    args.destino.write_text(
        json.dumps(resumen, ensure_ascii=False, indent=1) + "\n", encoding="utf-8"
    )
    print(
        f"{args.destino}: {resumen['instruments_with_directory']} instrumentos, "
        f"{resumen['snapshots']} snapshots, "
        f"{resumen['linked_by_title']} enlazados por título"
    )


if __name__ == "__main__":
    main()
