"""The website's Atlas page (issue #245), in a real browser.

    uv run --group viz playwright install chromium     # once
    uv run --group viz pytest scripts/embeddings/tests/test_atlas_page.py -q

The page is a hand-written D3 application (`website/pages/atlas/atlas.js`,
`atlas.css`) over the committed `website/pages/atlas/atlas.json` (issue #244),
wrapped by `website/pages/atlas.qmd`. Quarto is not installed where these
tests run, so the browser tests load a harness page instead: an HTML file
served next to `website/pages/atlas/` whose body is the qmd's own
`<!-- atlas:app -->` block, copied verbatim — so what is clicked here is the
markup the site publishes, not a look-alike.

The static checks at the top always run. The browser tests skip, with the
reason, when Playwright or its Chromium is missing.
"""

import functools
import http.server
import json
import re
import statistics
import threading
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[3]
WEBSITE = REPO / "website"
PAGES = WEBSITE / "pages"
QMD = PAGES / "atlas.qmd"
APP_JS = PAGES / "atlas" / "atlas.js"
APP_CSS = PAGES / "atlas" / "atlas.css"
DATA = PAGES / "atlas" / "atlas.json"
SCREENSHOT = REPO / "output" / "atlas-chapingo.png"

TITLE = "An Atlas of Mexican Federal Law: Laws, Regulations and Guidelines"
SUBTITLE = ("315 laws, 1,082 regulations and 126 guidelines, placed by where their "
            "provisions' closest texts live")
PALETTE = {"leyes": "#2a78d6", "reglamentos": "#008300", "lineamientos": "#e87ba4"}
CONSTITUTION = "CONSTITUCIÓN Política de los Estados Unidos Mexicanos"
CHAPINGO = "LEY que crea la Universidad Autónoma Chapingo"
CHAPINGO_TARGETS = [
    ("13.0", "LEY Orgánica de la Universidad Autónoma Agraria Antonio Narro"),
    ("11.3", "LEY Orgánica de la Universidad Autónoma Metropolitana"),
    ("2.0", "REGLAMENTO INTERIOR DEL COLEGIO DE POSTGRADUADOS"),
    ("1.0", "LEY Agraria"),
    ("1.0", "LEY Federal de Producción, Certificación y Comercio de Semillas"),
]

#: What the page must never say: the Python side's word for a provision, the
#: HTML word for the element the page replaced, the parameter's own name, and
#: the #242 page's provenance footer.
FORBIDDEN = [re.compile(r"\bunits?\b", re.I), re.compile("tooltip", re.I),
             re.compile("n_neighbors"), re.compile("Generated by"),
             re.compile("build_instrument_umap_html")]


def app_block(text: str) -> str:
    match = re.search(r"<!-- atlas:app -->.*?<!-- /atlas:app -->", text, re.S)
    assert match, "atlas.qmd has no <!-- atlas:app --> block"
    return match.group(0)


def front_matter(text: str) -> dict:
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    assert match, "atlas.qmd has no front matter"
    fields = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip().strip('"')
    return fields


def forbidden_in(text: str) -> list[str]:
    return [pattern.pattern for pattern in FORBIDDEN if pattern.search(text)]


# -- static checks, always run -------------------------------------------- #

def test_the_qmd_has_the_agreed_front_matter_and_no_code():
    text = QMD.read_text(encoding="utf-8")
    fields = front_matter(text)
    assert fields["title"] == TITLE
    assert fields["subtitle"] == SUBTITLE
    assert fields["page-layout"] == "full"
    assert fields["toc"] == "false"
    assert fields["number-sections"] == "false"
    # No code cells: nothing to execute, so nothing to freeze.
    assert "```" not in text


def test_the_qmd_mounts_the_application_with_relative_paths():
    block = app_block(QMD.read_text(encoding="utf-8"))
    assert '<link rel="stylesheet" href="atlas/atlas.css">' in block
    assert '<div id="atlas" class="atlas" data-src="atlas/atlas.json"></div>' in block
    assert '<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>' in block
    assert '<script src="atlas/atlas.js"></script>' in block


def test_the_qmd_prose_names_the_method_once_and_nothing_forbidden():
    text = QMD.read_text(encoding="utf-8")
    assert forbidden_in(text) == []
    assert text.count("UMAP") == 1
    assert "Qwen/Qwen3-Embedding-0.6B" in text


def test_the_application_files_say_nothing_forbidden():
    for path in (APP_JS, APP_CSS):
        text = path.read_text(encoding="utf-8")
        assert forbidden_in(text) == [], path
        assert "UMAP" not in text, path
    # D3 v7, and no other library.
    assert "d3." in APP_JS.read_text(encoding="utf-8")
    for color in PALETTE.values():
        assert color in APP_JS.read_text(encoding="utf-8")


def test_the_navbar_puts_atlas_right_after_federal_laws_and_ships_its_files():
    text = (WEBSITE / "_quarto.yml").read_text(encoding="utf-8")
    entries = re.findall(r"- href: (\S+)\n\s+text: (.+)", text)
    names = [name.strip() for _, name in entries]
    assert names[:5] == ["Home", "Archive", "Federal Laws", "Atlas", "DOF Titles"]
    assert ("pages/atlas.qmd", "Atlas") in [(h, n.strip()) for h, n in entries]
    assert re.search(r'resources:\s*\n\s*-\s*"pages/atlas/\*\*"', text)


def test_the_data_file_is_the_244_export():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    assert len(data["instruments"]) == data["meta"]["instruments"] == 1523
    assert sorted(data["projections"], key=int) == ["4", "8", "16", "32"]


# -- the browser ------------------------------------------------------------- #

HARNESS = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Atlas harness</title>
<style>body {{ margin: 0; padding: 0 16px; background: #fdfdfb; }}</style>
</head>
<body>
<main>
{app}
</main>
</body>
</html>
"""


@pytest.fixture(scope="module")
def server(tmp_path_factory):
    """`website/pages` over HTTP (Chromium blocks `fetch` from `file://`),
    plus the harness at `/harness.html`, written into a temporary directory
    and served from there."""
    harness = tmp_path_factory.mktemp("atlas") / "harness.html"
    harness.write_text(HARNESS.format(app=app_block(QMD.read_text(encoding="utf-8"))),
                       encoding="utf-8")

    class Handler(http.server.SimpleHTTPRequestHandler):
        def do_GET(self):
            if self.path.split("?")[0] == "/harness.html":
                body = harness.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
                return
            super().do_GET()

        def log_message(self, *args):
            pass

    httpd = http.server.ThreadingHTTPServer(
        ("127.0.0.1", 0), functools.partial(Handler, directory=str(PAGES)))
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    yield f"http://127.0.0.1:{httpd.server_address[1]}/harness.html"
    httpd.shutdown()
    httpd.server_close()


@pytest.fixture(scope="module")
def browser():
    sync_api = pytest.importorskip("playwright.sync_api")
    playwright = sync_api.sync_playwright().start()
    try:
        chromium = playwright.chromium.launch()
    except Exception as error:  # a missing browser or system library
        playwright.stop()
        pytest.skip(f"Chromium cannot launch here: {error}")
    yield chromium
    chromium.close()
    playwright.stop()


def open_page(browser, server, width=1280, height=900):
    page = browser.new_page(viewport={"width": width, "height": height})
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.goto(server)
    page.wait_for_selector('#atlas[data-ready="true"]', timeout=30000)
    assert errors == []
    return page


@pytest.fixture
def page(browser, server):
    page = open_page(browser, server)
    yield page
    page.close()


def search(page, query):
    page.fill("#atlas-search", query)
    page.wait_for_selector("#atlas-suggestions li")
    return page.locator("#atlas-suggestions li")


def select_by_search(page, query, name):
    search(page, query).filter(has_text=name).first.dispatch_event("mousedown")
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name", arg=name)


def panel_title(page):
    return page.locator(".atlas-panel h2").inner_text()


def test_every_instrument_is_one_circle_in_the_sites_palette(page):
    circles = page.locator("circle.atlas-point")
    assert circles.count() == 1523
    fills = set(page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('fill'))"))
    assert fills == set(PALETTE.values())
    for clave, collection in (("cpeum", "leyes"), ("luach", "leyes")):
        assert page.get_attribute(f'circle[data-k="{clave}"]', "fill") == PALETTE[collection]


def test_circle_area_is_proportional_to_provisions(page):
    radii = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => Number(n.getAttribute('r')))")
    constitution = float(page.get_attribute('circle[data-k="cpeum"]', "r"))
    assert constitution >= 4 * statistics.median(radii)
    assert len(set(radii)) > 100
    assert min(radii) >= 2.5


def test_constitucion_finds_the_constitution_first_and_enter_selects_it(page):
    suggestions = search(page, "constitucion")
    assert CONSTITUTION in suggestions.first.inner_text()
    page.press("#atlas-search", "Enter")
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name",
        arg=CONSTITUTION)
    assert "2,276 provisions" in page.locator(".atlas-panel").inner_text()
    # Brought into view: after the pan, its centre is inside the map.
    page.wait_for_timeout(900)
    box = page.locator("svg.atlas-map").bounding_box()
    circle = page.locator('circle[data-k="cpeum"]').bounding_box()
    centre = (circle["x"] + circle["width"] / 2, circle["y"] + circle["height"] / 2)
    assert box["x"] <= centre[0] <= box["x"] + box["width"]
    assert box["y"] <= centre[1] <= box["y"] + box["height"]
    assert page.locator("circle.atlas-ring").count() == 1


def test_search_folds_accents_and_case_and_reads_the_abbreviation(page):
    for query in ("CONSTITUCIÓN", "Constitución política", "cpeum"):
        assert CONSTITUTION in search(page, query).first.inner_text(), query


def test_chapingo_shows_all_five_closest_instruments_and_five_lines(page):
    select_by_search(page, "chapingo", CHAPINGO)
    rows = page.locator(".atlas-out .atlas-target")
    assert rows.count() == 5
    weights = rows.locator(".atlas-weight").all_inner_texts()
    names = rows.locator(".atlas-target-name").all_inner_texts()
    assert list(zip(weights, names)) == CHAPINGO_TARGETS
    assert page.locator(".atlas-inc .atlas-target").count() == 5
    panel = page.locator(".atlas-panel").inner_text()
    assert "35 provisions" in panel
    assert "abbreviation luach" in panel
    assert "28 provisions of other instruments" in panel
    assert page.locator("line.atlas-link").count() == 5
    badges = page.locator("g.atlas-badge text").all_text_contents()
    assert sorted(badges) == ["1", "2", "3", "4", "5"]
    # Nothing clipped: every row is fully rendered.
    for n in range(5):
        assert rows.nth(n).is_visible()


def test_a_name_in_the_panel_selects_that_instrument(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator(".atlas-out .atlas-target-name").first.click()
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name",
        arg=CHAPINGO_TARGETS[0][1])
    assert page.locator("circle.atlas-ring").count() == 1


def test_a_regulation_is_named_by_its_scjn_id(page):
    page.locator('circle.atlas-point[fill="#008300"]').first.dispatch_event("click")
    assert "SCJN id" in page.locator(".atlas-panel").inner_text()
    assert page.locator(".atlas-panel .atlas-badge-label").inner_text().lower() == "regulation"


def test_the_neighbourhood_control_moves_the_points_and_keeps_the_selection(page):
    group = page.locator('[role="radiogroup"]')
    assert group.get_attribute("aria-labelledby") == "atlas-neighbourhood-label"
    assert page.locator("#atlas-neighbourhood-label").inner_text().lower() \
        == "neighbourhood size"
    buttons = group.locator('[role="radio"]')
    assert buttons.all_inner_texts() == ["4", "8", "16", "32"]
    assert group.locator('[aria-checked="true"]').inner_text() == "16"
    assert "The layout changes, the data does not." in page.locator(".atlas").inner_text()

    select_by_search(page, "chapingo", CHAPINGO)
    page.wait_for_timeout(700)
    before = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    group.locator('[data-value="8"]').click()
    assert group.locator('[data-value="8"]').get_attribute("aria-checked") == "true"
    assert group.locator('[data-value="16"]').get_attribute("aria-checked") == "false"
    page.wait_for_timeout(250)
    # Mid-transition the points are moving ...
    during = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    page.wait_for_timeout(900)
    after = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    assert during != before and during != after
    assert after != before
    # ... and the selection survives the new layout.
    assert panel_title(page) == CHAPINGO
    assert page.locator("circle.atlas-ring").count() == 1
    assert page.locator("line.atlas-link").count() == 5


def test_a_collection_button_dims_the_other_two(page):
    law = 'circle[data-k="cpeum"]'
    regulation = 'circle.atlas-point[fill="#008300"]'
    assert page.get_attribute(law, "opacity") == "0.8"
    assert page.locator(regulation).first.get_attribute("opacity") == "0.8"
    laws = page.locator('.atlas-collection[data-c="leyes"]')
    assert "315 laws" in laws.inner_text()
    assert "1,082 regulations" in page.locator(".atlas-collections").inner_text()
    assert "126 guidelines" in page.locator(".atlas-collections").inner_text()
    laws.click()
    assert laws.get_attribute("aria-pressed") == "true"
    assert page.get_attribute(law, "opacity") == "0.8"
    assert float(page.locator(regulation).first.get_attribute("opacity")) < 0.2
    laws.click()
    assert laws.get_attribute("aria-pressed") == "false"
    assert page.locator(regulation).first.get_attribute("opacity") == "0.8"


def test_escape_and_an_empty_click_clear_the_selection(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator("svg.atlas-map").click(position={"x": 3, "y": 3})
    assert page.locator(".atlas-panel h2").count() == 0
    assert "Search for an instrument or click a point" in \
        page.locator(".atlas-panel").inner_text()
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator("svg.atlas-map").hover(position={"x": 3, "y": 3})
    page.keyboard.press("Escape")   # the first Escape closes nothing: the list is shut
    page.locator("body").press("Escape")
    assert page.locator("circle.atlas-ring").count() == 0


def test_hover_shows_a_name_label_the_page_owns(page):
    page.locator('circle[data-k="cpeum"]').hover(force=True)
    label = page.locator(".atlas-label")
    assert label.is_visible()
    assert label.inner_text() == CONSTITUTION


def test_the_rendered_page_says_nothing_forbidden(page):
    select_by_search(page, "chapingo", CHAPINGO)
    html = page.content()
    assert forbidden_in(html) == []
    commit = json.loads(DATA.read_text(encoding="utf-8"))["meta"]["commit"]
    assert commit not in html
    assert "UMAP" not in html


@pytest.mark.parametrize("width", [1280, 390])
def test_the_page_fits_the_width_and_stacks_on_a_phone(browser, server, width):
    page = open_page(browser, server, width=width, height=844 if width < 900 else 900)
    try:
        overflow = page.evaluate(
            "() => document.documentElement.scrollWidth - document.documentElement.clientWidth")
        assert overflow <= 0
        select_by_search(page, "chapingo", CHAPINGO)
        overflow = page.evaluate(
            "() => document.documentElement.scrollWidth - document.documentElement.clientWidth")
        assert overflow <= 0
        mapbox = page.locator(".atlas-map-wrap").bounding_box()
        panel = page.locator(".atlas-panel").bounding_box()
        if width < 900:
            assert panel["y"] >= mapbox["y"] + mapbox["height"]      # stacked
            assert panel["width"] <= width
        else:
            assert panel["x"] >= mapbox["x"] + mapbox["width"]       # side by side
            assert 300 <= panel["width"] <= 380
    finally:
        page.close()


def test_a_screenshot_with_chapingo_selected(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.wait_for_timeout(900)
    SCREENSHOT.parent.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(SCREENSHOT), full_page=True)
    assert SCREENSHOT.stat().st_size > 10_000
