"""The website's Atlas page (issue #245), in a real browser.

    uv run --group viz playwright install chromium     # once
    uv run --group viz pytest scripts/embeddings/tests/test_atlas_page.py -q

The page is a hand-written D3 application (`website/pages/atlas/atlas.js`,
`atlas.css`) over the committed `website/pages/atlas/atlas.json` (issue #244),
wrapped by `website/pages/atlas.qmd`. Most browser tests load a harness
page: an HTML file served next to `website/pages/atlas/` whose body is the
qmd's own `<!-- atlas:app -->` block, copied verbatim — so what is clicked
here is the markup the site publishes, not a look-alike. It is fast and needs
no Quarto, but it carries only `atlas.css`, not the site's own stylesheet.

That is how issue #247 got published: Quarto's CSS sends every `aside` to the
page margin with `grid-column: body-end/page-end !important`, and the panel
was an `<aside>`, so on the real page the map's grid track was 0 px wide. The
`rendered_*` tests at the bottom therefore render `pages/atlas.qmd` with
Quarto into `website/_site/` (gitignored) and drive the page Quarto wrote.

Issue #250's explanation dialog is tested twice: over a toy site (the
six-instrument corpus of `test_instrument_matrix.py`, exported by
`export_atlas_data.py` and `export_atlas_pairs.py` into a temporary directory
laid out like `website/pages/`, with the real `atlas.js`/`atlas.css`), and,
when `website/pages/atlas/pairs/` has been installed, over the real
Constitution -> LGIPE pair.

The static checks at the top always run. The browser tests skip, with the
reason, when Playwright or its Chromium is missing; the rendered-page tests
also skip when no Quarto binary is found (on `PATH`, else the newest
`~/.local/opt/quarto-*/bin/quarto`).
"""

import functools
import http.server
import json
import re
import shutil
import statistics
import subprocess
import sys
import threading
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from test_instrument_matrix import (  # noqa: E402,F401
    cache, index_of, prepared, stub_umap, with_matrix)

REPO = Path(__file__).resolve().parents[3]
WEBSITE = REPO / "website"
PAGES = WEBSITE / "pages"
QMD = PAGES / "atlas.qmd"
APP_JS = PAGES / "atlas" / "atlas.js"
APP_CSS = PAGES / "atlas" / "atlas.css"
DATA = PAGES / "atlas" / "atlas.json"
SCREENSHOT = REPO / "output" / "atlas-chapingo.png"
SITE = WEBSITE / "_site"
PAIRS = PAGES / "atlas" / "pairs"
WORKFLOW = REPO / ".github" / "workflows" / "website.yml"
EXPLAIN_SCREENSHOT = REPO / "output" / "atlas-explain-cpeum-lgipe.png"
LGIPE = "LEY General de Instituciones y Procedimientos Electorales"
NOT_AVAILABLE = "The explanation for this pair is not available."
OTHER_VERSION = "The explanation was built for a different version of the map."
RENDERED_SCREENSHOT = REPO / "output" / "atlas-rendered.png"
RENDERED_CHAPINGO_SCREENSHOT = REPO / "output" / "atlas-rendered-chapingo.png"
#: Quarto's margin text colour, `#636056`: what an `aside` on the site gets.
QUARTO_MARGIN_COLOR = "rgb(99, 96, 86)"

TITLE = "An Atlas of Mexican Federal Law: Laws, Regulations and Guidelines"
SUBTITLE = ("315 laws, 1,082 regulations and 126 guidelines, placed by where their "
            "provisions' closest texts live")
PALETTE = {"leyes": "#2a78d6", "reglamentos": "#008300", "lineamientos": "#e87ba4"}
CONSTITUTION = "CONSTITUCIÓN Política de los Estados Unidos Mexicanos"
CHAPINGO = "LEY que crea la Universidad Autónoma Chapingo"
CHAPINGO_TARGETS = [
    ("13.0", "LEY Orgánica de la Universidad Autónoma Agraria Antonio Narro"),
    ("11.3", "LEY Orgánica de la Universidad Autónoma Metropolitana"),
    ("2.0", "REGLAMENTO INTERIOR DEL COLEGIO DE POSTGRADUADOS"),
    ("1.0", "LEY Agraria"),
    ("1.0", "LEY Federal de Producción, Certificación y Comercio de Semillas"),
]

#: What the page must never say: the Python side's word for a provision, the
#: HTML word for the element the page replaced, the parameter's own name, and
#: the #242 page's provenance footer.
FORBIDDEN = [re.compile(r"\bunits?\b", re.I), re.compile("tooltip", re.I),
             re.compile("n_neighbors"), re.compile("Generated by"),
             re.compile("build_instrument_umap_html")]


def app_block(text: str) -> str:
    match = re.search(r"<!-- atlas:app -->.*?<!-- /atlas:app -->", text, re.S)
    assert match, "atlas.qmd has no <!-- atlas:app --> block"
    return match.group(0)


def front_matter(text: str) -> dict:
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    assert match, "atlas.qmd has no front matter"
    fields = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip().strip('"')
    return fields


def forbidden_in(text: str) -> list[str]:
    return [pattern.pattern for pattern in FORBIDDEN if pattern.search(text)]


# -- static checks, always run -------------------------------------------- #

def test_the_qmd_has_the_agreed_front_matter_and_no_code():
    text = QMD.read_text(encoding="utf-8")
    fields = front_matter(text)
    assert fields["title"] == TITLE
    assert fields["subtitle"] == SUBTITLE
    assert fields["page-layout"] == "full"
    assert fields["toc"] == "false"
    assert fields["number-sections"] == "false"
    # No code cells: nothing to execute, so nothing to freeze.
    assert "```" not in text


def test_the_qmd_mounts_the_application_with_relative_paths():
    block = app_block(QMD.read_text(encoding="utf-8"))
    assert '<link rel="stylesheet" href="atlas/atlas.css">' in block
    assert ('<div id="atlas" class="atlas" data-src="atlas/atlas.json" '
            'data-pairs="atlas/pairs/"></div>') in block
    assert '<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>' in block
    assert '<script src="atlas/atlas.js"></script>' in block


def test_the_qmd_prose_names_the_method_once_and_nothing_forbidden():
    text = QMD.read_text(encoding="utf-8")
    assert forbidden_in(text) == []
    assert text.count("UMAP") == 1
    assert "Qwen/Qwen3-Embedding-0.6B" in text


def test_the_application_files_say_nothing_forbidden():
    for path in (APP_JS, APP_CSS):
        text = path.read_text(encoding="utf-8")
        assert forbidden_in(text) == [], path
        assert "UMAP" not in text, path
    # D3 v7, and no other library.
    assert "d3." in APP_JS.read_text(encoding="utf-8")
    for color in PALETTE.values():
        assert color in APP_JS.read_text(encoding="utf-8")


def test_the_navbar_puts_atlas_right_after_federal_laws_and_ships_its_files():
    text = (WEBSITE / "_quarto.yml").read_text(encoding="utf-8")
    entries = re.findall(r"- href: (\S+)\n\s+text: (.+)", text)
    names = [name.strip() for _, name in entries]
    assert names[:5] == ["Home", "Archive", "Federal Laws", "Atlas", "DOF Titles"]
    assert ("pages/atlas.qmd", "Atlas") in [(h, n.strip()) for h, n in entries]
    assert re.search(r'resources:\s*\n\s*-\s*"pages/atlas/\*\*"', text)


def test_the_publish_workflow_fetches_the_pair_explanations_before_publishing():
    text = WORKFLOW.read_text(encoding="utf-8")
    step = text.index("name: Fetch the Atlas pair explanations")
    assert step < text.index("quarto-dev/quarto-actions/publish")
    body = text[step:text.index("quarto-dev/quarto-actions/publish")]
    assert "gh release download atlas-pairs" in body
    assert "--pattern 'atlas-pairs.tar.gz'" in body and "--pattern 'SHA256SUMS.txt'" in body
    assert "sha256sum -c --ignore-missing SHA256SUMS.txt" in body
    assert "set -euo pipefail" in body                 # a missing asset fails the job
    assert "website/pages/atlas/pairs" in body
    assert "GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}" in body
    assert "Hallazgo C" in text


def test_the_installed_pairs_are_never_committed():
    lines = (REPO / ".gitignore").read_text(encoding="utf-8").splitlines()
    assert "/website/pages/atlas/pairs/" in lines
    tracked = subprocess.run(["git", "-C", str(REPO), "ls-files", "website/pages/atlas/pairs"],
                             capture_output=True, text=True, check=True).stdout
    assert tracked == ""


def test_the_qmd_describes_the_explanation_and_its_example():
    text = QMD.read_text(encoding="utf-8")
    assert "opens a table of\nthe provisions behind that number" in text
    for number in ("116.6", "170 provisions", "35.6", "153"):
        assert number in text, number


def test_the_application_carries_the_dialog_and_its_two_messages():
    js = APP_JS.read_text(encoding="utf-8")
    for needle in (NOT_AVAILABLE, OTHER_VERSION, "showModal", "mount.dataset.pairs",
                   "mount.dataset.pageSize", "atlas-why"):
        assert needle in js, needle
    assert ".atlas-explain::backdrop" in APP_CSS.read_text(encoding="utf-8")


def test_the_data_file_is_the_244_export():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    assert len(data["instruments"]) == data["meta"]["instruments"] == 1523
    assert sorted(data["projections"], key=int) == ["4", "8", "16", "32"]


# -- the browser ------------------------------------------------------------- #

HARNESS = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Atlas harness</title>
<style>body {{ margin: 0; padding: 0 16px; background: #fdfdfb; }}</style>
</head>
<body>
<main>
{app}
</main>
</body>
</html>
"""


def serve(directory):
    """Start a quiet HTTP server over `directory` on a free port."""

    class Handler(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *args):
            pass

    httpd = http.server.ThreadingHTTPServer(
        ("127.0.0.1", 0), functools.partial(Handler, directory=str(directory)))
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


@pytest.fixture(scope="module")
def server(tmp_path_factory):
    """`website/pages` over HTTP (Chromium blocks `fetch` from `file://`),
    plus the harness at `/harness.html`, written into a temporary directory
    and served from there."""
    harness = tmp_path_factory.mktemp("atlas") / "harness.html"
    harness.write_text(HARNESS.format(app=app_block(QMD.read_text(encoding="utf-8"))),
                       encoding="utf-8")

    class Handler(http.server.SimpleHTTPRequestHandler):
        def do_GET(self):
            if self.path.split("?")[0] == "/harness.html":
                body = harness.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
                return
            super().do_GET()

        def log_message(self, *args):
            pass

    httpd = http.server.ThreadingHTTPServer(
        ("127.0.0.1", 0), functools.partial(Handler, directory=str(PAGES)))
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    yield f"http://127.0.0.1:{httpd.server_address[1]}/harness.html"
    httpd.shutdown()
    httpd.server_close()


@pytest.fixture(scope="module")
def browser():
    sync_api = pytest.importorskip("playwright.sync_api")
    playwright = sync_api.sync_playwright().start()
    try:
        chromium = playwright.chromium.launch()
    except Exception as error:  # a missing browser or system library
        playwright.stop()
        pytest.skip(f"Chromium cannot launch here: {error}")
    yield chromium
    chromium.close()
    playwright.stop()


def open_page(browser, server, width=1280, height=900):
    page = browser.new_page(viewport={"width": width, "height": height})
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.goto(server)
    page.wait_for_selector('#atlas[data-ready="true"]', timeout=30000)
    assert errors == []
    return page


@pytest.fixture
def page(browser, server):
    page = open_page(browser, server)
    yield page
    page.close()


def search(page, query):
    page.fill("#atlas-search", query)
    page.wait_for_selector("#atlas-suggestions li")
    return page.locator("#atlas-suggestions li")


def select_by_search(page, query, name):
    search(page, query).filter(has_text=name).first.dispatch_event("mousedown")
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name", arg=name)


def panel_title(page):
    return page.locator(".atlas-panel h2").inner_text()


def test_every_instrument_is_one_circle_in_the_sites_palette(page):
    circles = page.locator("circle.atlas-point")
    assert circles.count() == 1523
    fills = set(page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('fill'))"))
    assert fills == set(PALETTE.values())
    for clave, collection in (("cpeum", "leyes"), ("luach", "leyes")):
        assert page.get_attribute(f'circle[data-k="{clave}"]', "fill") == PALETTE[collection]


def test_circle_area_is_proportional_to_provisions(page):
    radii = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => Number(n.getAttribute('r')))")
    constitution = float(page.get_attribute('circle[data-k="cpeum"]', "r"))
    assert constitution >= 4 * statistics.median(radii)
    assert len(set(radii)) > 100
    assert min(radii) >= 2.5


def test_constitucion_finds_the_constitution_first_and_enter_selects_it(page):
    suggestions = search(page, "constitucion")
    assert CONSTITUTION in suggestions.first.inner_text()
    page.press("#atlas-search", "Enter")
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name",
        arg=CONSTITUTION)
    assert "2,276 provisions" in page.locator(".atlas-panel").inner_text()
    # Brought into view: after the pan, its centre is inside the map.
    page.wait_for_timeout(900)
    box = page.locator("svg.atlas-map").bounding_box()
    circle = page.locator('circle[data-k="cpeum"]').bounding_box()
    centre = (circle["x"] + circle["width"] / 2, circle["y"] + circle["height"] / 2)
    assert box["x"] <= centre[0] <= box["x"] + box["width"]
    assert box["y"] <= centre[1] <= box["y"] + box["height"]
    assert page.locator("circle.atlas-ring").count() == 1


def test_search_folds_accents_and_case_and_reads_the_abbreviation(page):
    for query in ("CONSTITUCIÓN", "Constitución política", "cpeum"):
        assert CONSTITUTION in search(page, query).first.inner_text(), query


def test_chapingo_shows_all_five_closest_instruments_and_five_lines(page):
    select_by_search(page, "chapingo", CHAPINGO)
    rows = page.locator(".atlas-out .atlas-target")
    assert rows.count() == 5
    weights = rows.locator(".atlas-weight").all_inner_texts()
    names = rows.locator(".atlas-target-name").all_inner_texts()
    assert list(zip(weights, names)) == CHAPINGO_TARGETS
    assert page.locator(".atlas-inc .atlas-target").count() == 5
    panel = page.locator(".atlas-panel").inner_text()
    assert "35 provisions" in panel
    assert "abbreviation luach" in panel
    assert "28 provisions of other instruments" in panel
    assert page.locator("line.atlas-link").count() == 5
    badges = page.locator("g.atlas-badge text").all_text_contents()
    assert sorted(badges) == ["1", "2", "3", "4", "5"]
    # Nothing clipped: every row is fully rendered.
    for n in range(5):
        assert rows.nth(n).is_visible()


def test_a_name_in_the_panel_selects_that_instrument(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator(".atlas-out .atlas-target-name").first.click()
    page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name",
        arg=CHAPINGO_TARGETS[0][1])
    assert page.locator("circle.atlas-ring").count() == 1


def test_a_regulation_is_named_by_its_scjn_id(page):
    page.locator('circle.atlas-point[fill="#008300"]').first.dispatch_event("click")
    assert "SCJN id" in page.locator(".atlas-panel").inner_text()
    assert page.locator(".atlas-panel .atlas-badge-label").inner_text().lower() == "regulation"


def test_the_neighbourhood_control_moves_the_points_and_keeps_the_selection(page):
    group = page.locator('[role="radiogroup"]')
    assert group.get_attribute("aria-labelledby") == "atlas-neighbourhood-label"
    assert page.locator("#atlas-neighbourhood-label").inner_text().lower() \
        == "neighbourhood size"
    buttons = group.locator('[role="radio"]')
    assert buttons.all_inner_texts() == ["4", "8", "16", "32"]
    assert group.locator('[aria-checked="true"]').inner_text() == "16"
    assert "The layout changes, the data does not." in page.locator(".atlas").inner_text()

    select_by_search(page, "chapingo", CHAPINGO)
    page.wait_for_timeout(700)
    before = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    group.locator('[data-value="8"]').click()
    assert group.locator('[data-value="8"]').get_attribute("aria-checked") == "true"
    assert group.locator('[data-value="16"]').get_attribute("aria-checked") == "false"
    page.wait_for_timeout(250)
    # Mid-transition the points are moving ...
    during = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    page.wait_for_timeout(900)
    after = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    assert during != before and during != after
    assert after != before
    # ... and the selection survives the new layout.
    assert panel_title(page) == CHAPINGO
    assert page.locator("circle.atlas-ring").count() == 1
    assert page.locator("line.atlas-link").count() == 5


def test_a_collection_button_dims_the_other_two(page):
    law = 'circle[data-k="cpeum"]'
    regulation = 'circle.atlas-point[fill="#008300"]'
    assert page.get_attribute(law, "opacity") == "0.8"
    assert page.locator(regulation).first.get_attribute("opacity") == "0.8"
    laws = page.locator('.atlas-collection[data-c="leyes"]')
    assert "315 laws" in laws.inner_text()
    assert "1,082 regulations" in page.locator(".atlas-collections").inner_text()
    assert "126 guidelines" in page.locator(".atlas-collections").inner_text()
    laws.click()
    assert laws.get_attribute("aria-pressed") == "true"
    assert page.get_attribute(law, "opacity") == "0.8"
    assert float(page.locator(regulation).first.get_attribute("opacity")) < 0.2
    laws.click()
    assert laws.get_attribute("aria-pressed") == "false"
    assert page.locator(regulation).first.get_attribute("opacity") == "0.8"


def test_escape_and_an_empty_click_clear_the_selection(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator("svg.atlas-map").click(position={"x": 3, "y": 3})
    assert page.locator(".atlas-panel h2").count() == 0
    assert "Search for an instrument or click a point" in \
        page.locator(".atlas-panel").inner_text()
    select_by_search(page, "chapingo", CHAPINGO)
    page.locator("svg.atlas-map").hover(position={"x": 3, "y": 3})
    page.keyboard.press("Escape")   # the first Escape closes nothing: the list is shut
    page.locator("body").press("Escape")
    assert page.locator("circle.atlas-ring").count() == 0


def test_hover_shows_a_name_label_the_page_owns(page):
    page.locator('circle[data-k="cpeum"]').hover(force=True)
    label = page.locator(".atlas-label")
    assert label.is_visible()
    assert label.inner_text() == CONSTITUTION


def test_the_rendered_page_says_nothing_forbidden(page):
    select_by_search(page, "chapingo", CHAPINGO)
    html = page.content()
    assert forbidden_in(html) == []
    commit = json.loads(DATA.read_text(encoding="utf-8"))["meta"]["commit"]
    assert commit not in html
    assert "UMAP" not in html


@pytest.mark.parametrize("width", [1280, 390])
def test_the_page_fits_the_width_and_stacks_on_a_phone(browser, server, width):
    page = open_page(browser, server, width=width, height=844 if width < 900 else 900)
    try:
        overflow = page.evaluate(
            "() => document.documentElement.scrollWidth - document.documentElement.clientWidth")
        assert overflow <= 0
        select_by_search(page, "chapingo", CHAPINGO)
        overflow = page.evaluate(
            "() => document.documentElement.scrollWidth - document.documentElement.clientWidth")
        assert overflow <= 0
        mapbox = page.locator(".atlas-map-wrap").bounding_box()
        panel = page.locator(".atlas-panel").bounding_box()
        if width < 900:
            assert panel["y"] >= mapbox["y"] + mapbox["height"]      # stacked
            assert panel["width"] <= width
        else:
            assert panel["x"] >= mapbox["x"] + mapbox["width"]       # side by side
            assert 300 <= panel["width"] <= 380
    finally:
        page.close()


def test_a_screenshot_with_chapingo_selected(page):
    select_by_search(page, "chapingo", CHAPINGO)
    page.wait_for_timeout(900)
    SCREENSHOT.parent.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(SCREENSHOT), full_page=True)
    assert SCREENSHOT.stat().st_size > 10_000


# -- the page Quarto renders (issue #247) ------------------------------------ #

def find_quarto():
    """Quarto on `PATH`, else the newest one installed under `~/.local/opt`."""
    found = shutil.which("quarto")
    if found:
        return found
    installed = sorted(Path.home().glob(".local/opt/quarto-*/bin/quarto"),
                       key=lambda path: [int(part) if part.isdigit() else part
                                         for part in re.split(r"[.-]", path.parts[-3])])
    return str(installed[-1]) if installed else None


@pytest.fixture(scope="module")
def rendered_site():
    """`pages/atlas.qmd` rendered by Quarto into `website/_site/`, served over
    HTTP; the URL of the rendered Atlas page."""
    quarto = find_quarto()
    if quarto is None:
        pytest.skip("Quarto not found: put it on PATH or install it under "
                    "~/.local/opt/quarto-<version>/bin/quarto (CI uses 1.9.38)")
    subprocess.run([quarto, "render", "pages/atlas.qmd"], cwd=WEBSITE, check=True,
                   capture_output=True, timeout=300)
    assert (SITE / "pages" / "atlas.html").exists()
    assert (SITE / "pages" / "atlas" / "atlas.js").read_text(encoding="utf-8") \
        == APP_JS.read_text(encoding="utf-8")
    httpd = serve(SITE)
    yield f"http://127.0.0.1:{httpd.server_address[1]}/pages/atlas.html"
    httpd.shutdown()
    httpd.server_close()


@pytest.fixture
def rendered_page(browser, rendered_site):
    page = open_page(browser, rendered_site)
    yield page
    page.close()


def rendered_svg_box(page):
    return page.locator("svg.atlas-map").bounding_box()


def visible_circles_inside(page, box):
    """Circles with a non-zero box whose centre lies inside `box` (both in
    viewport coordinates, as Playwright's `bounding_box` reports them)."""
    return page.eval_on_selector_all(
        "circle.atlas-point",
        """(nodes, box) => nodes.filter(node => {
             const r = node.getBoundingClientRect();
             const cx = r.x + r.width / 2, cy = r.y + r.height / 2;
             return r.width > 0 && r.height > 0
               && cx >= box.x && cx <= box.x + box.width
               && cy >= box.y && cy <= box.y + box.height;
           }).length""",
        box)


def test_rendered_map_has_width_and_visible_points(rendered_page):
    box = rendered_svg_box(rendered_page)
    assert box["width"] > 600
    assert visible_circles_inside(rendered_page, box) >= 1400
    tracks = rendered_page.evaluate(
        "() => getComputedStyle(document.querySelector('.atlas-main'))"
        ".gridTemplateColumns")
    widths = [float(track.removesuffix("px")) for track in tracks.split()]
    assert len(widths) == 2, tracks
    assert all(width > 0 for width in widths), tracks
    RENDERED_SCREENSHOT.parent.mkdir(parents=True, exist_ok=True)
    rendered_page.screenshot(path=str(RENDERED_SCREENSHOT), full_page=True)
    assert RENDERED_SCREENSHOT.stat().st_size > 10_000


def test_rendered_panel_is_not_in_quartos_margin(rendered_page):
    assert rendered_page.locator("#atlas aside").count() == 0
    panel = rendered_page.locator(".atlas-panel")
    assert panel.get_attribute("role") == "complementary"
    style = panel.evaluate(
        "node => { const s = getComputedStyle(node);"
        " return {column: s.gridColumnStart + ' / ' + s.gridColumnEnd, color: s.color}; }")
    assert style["column"] == "auto / auto"
    assert style["color"] != QUARTO_MARGIN_COLOR
    assert style["color"] == "rgb(31, 30, 27)"            # --atlas-ink
    # Quarto's heading rule and serif font do not reach the panel's headings.
    select_by_search(rendered_page, "chapingo", CHAPINGO)
    assert rendered_page.eval_on_selector(
        ".atlas-panel h2", "n => getComputedStyle(n).borderBottomWidth") == "0px"
    assert "sans-serif" in rendered_page.eval_on_selector(
        ".atlas-panel h3", "n => getComputedStyle(n).fontFamily")


def test_rendered_page_at_phone_width(browser, rendered_site):
    page = open_page(browser, rendered_site, width=390, height=800)
    try:
        box = rendered_svg_box(page)
        assert box["width"] > 300
        panel = page.locator(".atlas-panel").bounding_box()
        assert panel["y"] >= box["y"] + box["height"]
        assert page.evaluate("() => document.documentElement.scrollWidth") <= 390
    finally:
        page.close()


def test_rendered_selection_draws_five_lines(rendered_page):
    search(rendered_page, "chapingo")
    rendered_page.press("#atlas-search", "Enter")
    rendered_page.wait_for_function(
        "name => document.querySelector('.atlas-panel h2')?.textContent === name",
        arg=CHAPINGO)
    assert rendered_page.locator(".atlas-out .atlas-target").count() == 5
    rendered_page.wait_for_timeout(900)
    box = rendered_svg_box(rendered_page)
    lines = rendered_page.locator("line.atlas-link")
    assert lines.count() == 5
    for n in range(5):
        line = lines.nth(n).bounding_box()
        assert line is not None
        assert box["x"] - 1 <= line["x"] and line["x"] + line["width"] <= box["x"] + box["width"] + 1
        assert box["y"] - 1 <= line["y"] and line["y"] + line["height"] <= box["y"] + box["height"] + 1
    RENDERED_CHAPINGO_SCREENSHOT.parent.mkdir(parents=True, exist_ok=True)
    rendered_page.screenshot(path=str(RENDERED_CHAPINGO_SCREENSHOT), full_page=True)
    assert RENDERED_CHAPINGO_SCREENSHOT.stat().st_size > 10_000


# -- the explanation dialog over a toy site (issue #250) ---------------------- #

def quiet(*args):
    pass


@pytest.fixture
def toy_site(with_matrix, stub_umap, cache, tmp_path):
    """A directory laid out like `website/pages/`: the real `atlas.js` and
    `atlas.css`, and the toy corpus' own `atlas.json` and `atlas/pairs/`."""
    import export_atlas_data
    import export_atlas_pairs

    site = tmp_path / "site"
    (site / "atlas").mkdir(parents=True)
    shutil.copy(APP_JS, site / "atlas" / "atlas.js")
    shutil.copy(APP_CSS, site / "atlas" / "atlas.css")
    export_atlas_data.export(with_matrix, site / "atlas" / "atlas.json", log=quiet)
    out_dir = tmp_path / "atlas-pairs"
    export_atlas_pairs.export(with_matrix, out_dir=out_dir, cache_dir=cache, log=quiet)
    export_atlas_pairs.install(out_dir, site / "atlas" / "pairs", log=quiet)
    return {"site": site, "index": index_of(with_matrix),
            "atlas": json.loads((site / "atlas" / "atlas.json").read_text(encoding="utf-8"))}


class Toy:
    """One page over the toy site, with every request it made."""

    def __init__(self, browser, toy_site, page_size=None, width=1280, height=900):
        block = app_block(QMD.read_text(encoding="utf-8"))
        if page_size is not None:
            block = block.replace('data-pairs="atlas/pairs/"',
                                  f'data-pairs="atlas/pairs/" data-page-size="{page_size}"')
        site = toy_site["site"]
        (site / "harness.html").write_text(HARNESS.format(app=block), encoding="utf-8")
        self.index = toy_site["index"]
        self.site = site
        self.httpd = serve(site)
        self.requests = []
        self.errors = []
        self.page = browser.new_page(viewport={"width": width, "height": height})
        self.page.on("request", lambda request: self.requests.append(request.url))
        self.page.on("pageerror", lambda error: self.errors.append(str(error)))
        self.page.goto(f"http://127.0.0.1:{self.httpd.server_address[1]}/harness.html")
        self.page.wait_for_selector('#atlas[data-ready="true"]', timeout=30000)

    def pair_file(self, source, target):
        return self.site / "atlas" / "pairs" / f"{self.index[source]}-{self.index[target]}.json"

    def pair(self, source, target):
        return json.loads(self.pair_file(source, target).read_text(encoding="utf-8"))

    def pair_requests(self):
        return [url for url in self.requests if "/atlas/pairs/" in url]

    def select(self, clave, name):
        self.page.locator(f'circle[data-k="{clave}"]').dispatch_event("click")
        self.page.wait_for_function(
            "name => document.querySelector('.atlas-panel h2')?.textContent === name",
            arg=name)

    def why(self, target):
        return self.page.locator(f'.atlas-out .atlas-why[data-i="{self.index[target]}"]')

    def open(self, target):
        self.why(target).click()
        self.page.wait_for_selector("dialog.atlas-explain[open]")
        self.page.wait_for_function(
            "() => !document.querySelector('.atlas-explain-status')"
            " || document.querySelector('.atlas-explain-status').textContent !== 'Loading\u2026'")

    def is_open(self):
        return self.page.evaluate("() => document.querySelector('dialog.atlas-explain').open")

    def close(self):
        self.page.close()
        self.httpd.shutdown()
        self.httpd.server_close()


@pytest.fixture
def toy(browser, toy_site):
    toy = Toy(browser, toy_site)
    yield toy
    toy.close()


def weights_in_table(page):
    total = 0.0
    for text in page.locator(".atlas-explain-table tbody .atlas-explain-fraction").all_inner_texts():
        numerator, _, denominator = text.partition("/")
        total += float(numerator) / float(denominator or 1)
    return total


def test_toy_weight_opens_the_provisions_behind_it(toy):
    """`b -> a` (2.8): four unit rows — the shared transitorio twice, the tie
    and the three-owner boilerplate — whose weights add up to the panel's
    number."""
    toy.select("b", "Ley B")
    panel_weight = toy.why("a").inner_text()
    assert panel_weight == "2.8"
    toy.open("a")
    page = toy.page
    assert page.locator("#atlas-explain-title").inner_text() == "Why Ley B is close to Ley A"
    pair = toy.pair("b", "a")
    rows = page.locator(".atlas-explain-table tbody tr")
    assert rows.count() == pair["provisions"] == 4
    lead = page.locator(".atlas-explain-lead").inner_text()
    assert lead == ("4 provisions of Ley B have their closest text outside it in Ley A; "
                    "they add up to 2.8 of its 4 provisions.")
    assert weights_in_table(page) == pytest.approx(float(panel_weight), abs=0.05)
    fractions = page.locator(".atlas-explain-fraction").all_inner_texts()
    assert fractions.count("1") == 2 and "1/2" in fractions and "1/3" in fractions
    assert "this text is shared by 3 instruments" in page.locator(".atlas-explain-table").inner_text()
    assert page.locator(".atlas-explain-similarity").nth(1).inner_text() == "1.000"
    # Both sides, in full.
    first = page.locator(".atlas-explain-table tbody tr").first
    assert "transitorio compartido" in first.locator(".atlas-explain-source").inner_text()
    assert "transitorio compartido" in first.locator(".atlas-explain-target").inner_text()
    assert page.locator(".atlas-explain-count").inner_text() == "Showing 4 of 4"
    assert not page.locator(".atlas-explain-more").is_visible()
    assert toy.errors == []


@pytest.mark.parametrize("how", ["escape", "button", "backdrop"])
def test_toy_dialog_closes_and_leaves_the_map_alone(toy, how):
    toy.select("b", "Ley B")
    page = toy.page
    page.wait_for_timeout(300)
    positions = page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))")
    links = page.locator("line.atlas-link").count()
    toy.open("a")
    if how == "escape":
        page.keyboard.press("Escape")
    elif how == "button":
        page.locator(".atlas-explain-close").click()
    else:
        page.mouse.click(5, 5)
    page.wait_for_function("() => !document.querySelector('dialog.atlas-explain').open")
    assert panel_title(page) == "Ley B"
    assert page.locator("circle.atlas-ring").count() == 1
    assert page.locator("line.atlas-link").count() == links
    assert page.eval_on_selector_all(
        "circle.atlas-point", "nodes => nodes.map(n => n.getAttribute('cx'))") == positions
    assert page.evaluate(
        "i => document.activeElement.classList.contains('atlas-why')"
        " && document.activeElement.dataset.i === String(i)", toy.index["a"])
    assert toy.errors == []


def test_toy_points_here_weights_are_plain_numbers(toy):
    toy.select("a", "Ley A")
    page = toy.page
    assert page.locator(".atlas-inc .atlas-target").count() > 0
    assert page.locator(".atlas-inc .atlas-why").count() == 0
    assert page.locator(".atlas-inc button.atlas-weight").count() == 0
    page.locator(".atlas-inc .atlas-weight").first.click()
    page.wait_for_timeout(200)
    assert not toy.is_open()
    assert toy.pair_requests() == []
    # Every closest instrument's weight is a button.
    assert page.locator(".atlas-out .atlas-why").count() == \
        page.locator(".atlas-out .atlas-target").count() == 4


def test_toy_fetches_on_click_only_and_once_per_pair(toy):
    toy.select("b", "Ley B")
    assert toy.pair_requests() == []
    for _ in range(2):
        toy.open("a")
        toy.page.keyboard.press("Escape")
    toy.open("900")
    toy.page.keyboard.press("Escape")
    requested = sorted(url.rsplit("/", 1)[1] for url in toy.pair_requests())
    assert requested == sorted([f"{toy.index['b']}-{toy.index['a']}.json",
                                f"{toy.index['b']}-{toy.index['900']}.json"])


def test_toy_missing_pair_says_not_available_and_the_page_keeps_working(toy):
    toy.pair_file("b", "a").unlink()
    toy.select("b", "Ley B")
    toy.open("a")
    page = toy.page
    assert page.locator(".atlas-explain-status").inner_text() == NOT_AVAILABLE
    assert page.locator("#atlas-explain-title").inner_text() == "Why Ley B is close to Ley A"
    page.keyboard.press("Escape")
    toy.select("c", "Ley C")
    assert page.locator("circle.atlas-ring").count() == 1
    toy.open("a")
    assert page.locator(".atlas-explain-table tbody tr").count() == toy.pair("c", "a")["provisions"]
    assert toy.errors == []


def test_toy_pair_built_for_another_map_says_so(toy):
    path = toy.pair_file("b", "a")
    pair = json.loads(path.read_text(encoding="utf-8"))
    pair["source"]["k"] = "zzz"
    path.write_text(json.dumps(pair, ensure_ascii=False), encoding="utf-8")
    toy.select("b", "Ley B")
    toy.open("a")
    assert toy.page.locator(".atlas-explain-status").inner_text() == OTHER_VERSION
    assert toy.page.locator(".atlas-explain-table").count() == 0
    assert toy.errors == []


def test_toy_table_pages_by_the_mounts_page_size(browser, toy_site):
    toy = Toy(browser, toy_site, page_size=3)
    try:
        toy.select("b", "Ley B")
        toy.open("a")
        page = toy.page
        rows = page.locator(".atlas-explain-table tbody tr")
        assert rows.count() == 3
        assert page.locator(".atlas-explain-count").inner_text() == "Showing 3 of 4"
        more = page.locator(".atlas-explain-more")
        assert more.inner_text() == "Show 1 more (1 left)"
        more.click()
        assert rows.count() == 4
        assert page.locator(".atlas-explain-count").inner_text() == "Showing 4 of 4"
        assert not more.is_visible()
        assert rows.locator(".atlas-explain-n").all_inner_texts() == ["1", "2", "3", "4"]
    finally:
        toy.close()


def test_toy_text_renders_bold_and_paragraphs_and_nothing_else(toy):
    path = toy.pair_file("b", "a")
    pair = json.loads(path.read_text(encoding="utf-8"))
    first = pair["rows"][0]
    pair["texts"][str(first["text"])] = "**Primero.-** Uno <b>dos</b> **suelto\n\nTres"
    path.write_text(json.dumps(pair, ensure_ascii=False), encoding="utf-8")
    toy.select("b", "Ley B")
    toy.open("a")
    cell = toy.page.locator(".atlas-explain-table tbody tr").first.locator(".atlas-explain-source")
    paragraphs = cell.locator("p.atlas-explain-text")
    assert paragraphs.count() == 2
    assert paragraphs.first.locator("strong").all_inner_texts() == ["Primero.-"]
    assert paragraphs.first.inner_text() == "Primero.- Uno <b>dos</b> **suelto"
    assert cell.locator("b").count() == 0
    assert paragraphs.nth(1).inner_text() == "Tres"


def test_toy_dialog_fills_a_phone_and_stacks_its_rows(browser, toy_site):
    toy = Toy(browser, toy_site, width=390, height=844)
    try:
        toy.select("b", "Ley B")
        toy.why("a").scroll_into_view_if_needed()
        toy.open("a")
        page = toy.page
        box = page.locator("dialog.atlas-explain").bounding_box()
        assert box["width"] == pytest.approx(390, abs=1)
        assert box["height"] == pytest.approx(844, abs=1)
        cells = page.locator(".atlas-explain-table tbody tr").first.locator("td")
        tops = [cells.nth(n).bounding_box()["y"] for n in range(cells.count())]
        assert tops == sorted(tops) and len(set(tops)) == len(tops)      # stacked
        assert page.evaluate("() => document.documentElement.scrollWidth") <= 390
        assert page.evaluate(
            "() => { const d = document.querySelector('dialog.atlas-explain');"
            " return d.scrollWidth <= d.clientWidth; }")
    finally:
        toy.close()


# -- the real Constitution -> LGIPE pair, when installed ---------------------- #

def test_the_constitution_explains_its_lgipe_weight(page):
    if not PAIRS.is_dir():
        pytest.skip(f"{PAIRS} is not installed: run export_atlas_pairs.py --install "
                    "website/pages/atlas/pairs, or unpack the atlas-pairs release there")
    requests = []
    page.on("request", lambda request: requests.append(request.url))
    select_by_search(page, "constitucion", CONSTITUTION)
    assert not [url for url in requests if "/atlas/pairs/" in url]
    row = page.locator(".atlas-out .atlas-target").filter(has_text=LGIPE)
    button = row.locator(".atlas-why")
    assert button.inner_text() == "116.6"
    button.click()
    page.wait_for_selector(".atlas-explain-table tbody tr")
    title = page.locator("#atlas-explain-title").inner_text()
    assert CONSTITUTION in title and LGIPE in title
    lead = page.locator(".atlas-explain-lead").inner_text()
    assert lead.startswith("170 provisions of ")
    assert "they add up to 116.6 of its 2,276 provisions" in lead
    rows = page.locator(".atlas-explain-table tbody tr")
    assert rows.count() == 50
    more = page.locator(".atlas-explain-more")
    assert more.inner_text() == "Show 50 more (120 left)"
    for shown in (100, 150, 170):
        more.click()
        assert rows.count() == shown
    assert not more.is_visible()
    assert page.locator(".atlas-explain-count").inner_text() == "Showing 170 of 170"
    assert weights_in_table(page) == pytest.approx(116.6, abs=0.05)
    fractions = page.locator(".atlas-explain-fraction").all_inner_texts()
    assert "1/101" in fractions and "1" in fractions
    table = page.locator(".atlas-explain-table").inner_text()
    assert "this text is shared by 101 instruments" in table
    # The whole text, both sides: the file's own, rendered without its `**`.
    claves = [entry["k"] for entry in json.loads(DATA.read_text(encoding="utf-8"))["instruments"]]
    name = f"{claves.index('cpeum')}-{button.get_attribute('data-i')}.json"
    assert [url.rsplit("/", 1)[1] for url in requests if "/atlas/pairs/" in url] == [name]
    pair = json.loads((PAIRS / name).read_text(encoding="utf-8"))
    longest = max(pair["rows"], key=lambda r: len(pair["texts"][str(r["text"])]))
    expected = pair["texts"][str(longest["text"])].replace("**", "")
    assert expected[-60:] in table
    assert forbidden_in(page.content()) == []
    page.locator(".atlas-explain-close").click()
    page.wait_for_function("() => !document.querySelector('dialog.atlas-explain').open")
    assert panel_title(page) == CONSTITUTION
    button.click()
    page.wait_for_selector(".atlas-explain-table tbody tr")
    page.wait_for_timeout(300)
    EXPLAIN_SCREENSHOT.parent.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(EXPLAIN_SCREENSHOT))
    assert EXPLAIN_SCREENSHOT.stat().st_size > 10_000
    assert len([url for url in requests if "/atlas/pairs/" in url]) == 1


def test_rendered_dialog_heading_has_no_quarto_rule(rendered_page):
    """The #247 lesson, for the dialog: Quarto's h2 rule must not reach it."""
    select_by_search(rendered_page, "chapingo", CHAPINGO)
    rendered_page.locator(".atlas-out .atlas-why").first.click()
    rendered_page.wait_for_selector("dialog.atlas-explain[open] h2")
    assert rendered_page.eval_on_selector(
        ".atlas-explain h2", "n => getComputedStyle(n).borderBottomWidth") == "0px"
    box = rendered_page.locator("dialog.atlas-explain").bounding_box()
    assert box["width"] > 600
    rendered_page.keyboard.press("Escape")
    rendered_page.wait_for_function("() => !document.querySelector('dialog.atlas-explain').open")
    assert panel_title(rendered_page) == CHAPINGO
